[tool.poetry]
name = "ceres"
version = "0.1.0"
description = ""
authors = ["Jake Ploskey <jploskey@uw.edu>"]
include = ["./ceres/**/*.py", "./ceres/static/**/*", "./ceres/py.typed"]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.0"
aiosmtplib = "^1.1.0"
apscheduler = "^3.9.0"
asgiref = "^3.7.0"
fastapi = ">=0.95.0"
jinja2 = "^3.1.0"
mistune = ">=3.0.0rc5"
netcdf4 = "^1.6.0"
numpy = "^1.24.0"
pydantic = "^1.10.0"
pyyaml = "^6.0.0"
setproctitle = "^1.0.0"
sqlalchemy = "^2.0.0"
sqlparse = ">=0.4.0"
typer = { version = ">=0.6.0", extras = ["all"] }
uvicorn = ">=0.14.0"
watchfiles = ">=0.10.0"
websockets = "^10.0.0"

launchd = { version = "0.3.0", platform = "darwin" }


psycopg = { version = "^3.1.0", extras = ["binary"], optional = true }

aiosqlite = { version = ">=0.17.0", optional = true }

uvloop = { version = ">=0.17.0", optional = true }

[tool.poetry.extras]
postgres = ["psycopg"]
sqlite = ["aiosqlite"]
uvloop = ["uvloop"]
all = ["psycopg", "aiosqlite", "uvloop"]

[tool.poetry.group.dev.dependencies]
black = "22.12.0"
pyright = "1.1.317"
pytest = "7.4.0"
pytest-asyncio = "0.21.1"
ruff = "0.0.278"
types-pyyaml = "^6.0.12.11"

[tool.poetry.scripts]
ceres = "ceres:main"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
ignore = ["F402"]

[tool.pyright]
include = ["ceres", "tests"]
reportImportCycles = false
reportMissingTypeStubs = false
reportPrivateUsage = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnnecessaryIsInstance = false
reportUntypedFunctionDecorator = false
reportUnusedFunction = false
typeCheckingMode = "strict"
useLibraryCodeForTypes = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = "ignore:.*pkg_resources.*:DeprecationWarning"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
