# Generated by scripts/update-models.py. Run 'make models' to update.

"""Generated models for the `alerts` table."""

from typing import TYPE_CHECKING, ClassVar, Literal

from pydantic import Field

from ceres.__internal__.record import (
    BaseRecordCreate,
    BaseRecordField,
    BaseRecordFilter,
    BaseRecordFilterArgs,
    BaseRecordOrder,
    BaseRecordUpdate,
)
from ceres.data import (
    FromYAML,
    JSONSerializableDict,
    MaybeSequence,
)
from ceres.level import Level

if TYPE_CHECKING:
    # The filters name them only as forward references.
    from ceres.alert import Alert  # noqa: F401

__all__ = [
    "AlertCreate",
    "AlertField",
    "AlertFilter",
    "AlertFilterArgs",
    "AlertOrder",
    "AlertUpdate",
]


type AlertField = (
    BaseRecordField
    | Literal[
        "level",
        "type",
        "data",
    ]
)
"""Field names selectable in `Alert` queries."""

type AlertOrder = (
    BaseRecordOrder
    | Literal[
        "level",
        "level:asc",
        "level:desc",
        "type",
        "type:asc",
        "type:desc",
    ]
)
"""Ordering keys accepted by `Alert` queries."""


class AlertFilterArgs(BaseRecordFilterArgs[AlertField, AlertOrder], total=False):
    """Keyword-argument form of `AlertFilter` for ergonomic call sites."""

    level: MaybeSequence[Level] | None
    min_level: Level | None
    max_level: Level | None
    type: MaybeSequence[str] | None
    type_contains: MaybeSequence[str] | None
    type_prefix: MaybeSequence[str] | None
    type_suffix: MaybeSequence[str] | None
    data_contains: MaybeSequence[str] | None
    data_prefix: MaybeSequence[str] | None
    data_suffix: MaybeSequence[str] | None


class AlertFilter(BaseRecordFilter["Alert", AlertField, AlertOrder]):
    """Filter for selecting `Alert` records."""

    __table__: ClassVar[str] = "alerts"

    level: MaybeSequence[Level] | None = None
    """Filter by `level` being equal to one or more given levels."""
    min_level: Level | None = None
    """Filter by `level` being greater than or equal to the given level value."""
    max_level: Level | None = None
    """Filter by `level` being less than or equal to the given level value."""
    type: MaybeSequence[str] | None = None
    """Filter by `type` being equal to one or more given types."""
    type_contains: MaybeSequence[str] | None = None
    """Filter by `type` containing one or more given substrings."""
    type_prefix: MaybeSequence[str] | None = None
    """Filter by `type` starting with one or more given prefixes."""
    type_suffix: MaybeSequence[str] | None = None
    """Filter by `type` ending with one or more given suffixes."""
    data_contains: MaybeSequence[str] | None = None
    """Filter by whether or not the JSON text of `data` contains one or more given substrings."""
    data_prefix: MaybeSequence[str] | None = None
    """Filter by whether or not the JSON text of `data` starts with one or more given prefixes."""
    data_suffix: MaybeSequence[str] | None = None
    """Filter by whether or not the JSON text of `data` ends with one or more given suffixes."""


class AlertCreate(BaseRecordCreate, slots=True):
    """Payload for creating a new `Alert` record."""

    level: Level
    """Severity level of the alert."""
    type: str
    """Discriminator string identifying the kind of alert."""
    data: FromYAML[JSONSerializableDict] = Field(default_factory=dict)
    """Optional structured payload providing additional context for the alert."""


class AlertUpdate(BaseRecordUpdate, total=False):
    """Partial update for an existing `Alert` record."""

    level: Level
    type: str
    data: FromYAML[JSONSerializableDict]


# Present the models as part of the public module that re-exports them.
for _model in (AlertCreate, AlertFilter, AlertFilterArgs, AlertUpdate):
    _model.__module__ = "ceres.alert"
