# Generated by scripts/update-models.py. Run 'make models' to update.

"""Generated models for the `groups`, `group_memberships` tables."""

from typing import TYPE_CHECKING, ClassVar, Literal, TypedDict
from uuid import UUID

from ceres.__internal__.entity import (
    BaseEntityCreate,
    BaseEntityFilter,
    BaseEntityFilterArgs,
    BaseUUIDEntityCreate,
    BaseUUIDEntityField,
    BaseUUIDEntityFilter,
    BaseUUIDEntityFilterArgs,
    BaseUUIDEntityOrder,
)
from ceres.data import (
    MaybeSequence,
    Name,
)

if TYPE_CHECKING:
    # The filters name them only as forward references.
    from ceres.group import Group, GroupMembership  # noqa: F401

__all__ = [
    "GroupCreate",
    "GroupField",
    "GroupFilter",
    "GroupFilterArgs",
    "GroupMembershipCreate",
    "GroupMembershipField",
    "GroupMembershipFilter",
    "GroupMembershipFilterArgs",
    "GroupMembershipOrder",
    "GroupMembershipUpdate",
    "GroupOrder",
    "GroupUpdate",
]


type GroupField = (
    BaseUUIDEntityField
    | Literal[
        "name",
        "description",
    ]
)
"""Field names selectable in `Group` queries."""

type GroupOrder = (
    BaseUUIDEntityOrder
    | Literal[
        "name",
        "name:asc",
        "name:desc",
    ]
)
"""Ordering keys accepted by `Group` queries."""


class GroupFilterArgs(BaseUUIDEntityFilterArgs[GroupField, GroupOrder], total=False):
    """Keyword-argument form of `GroupFilter` for ergonomic call sites."""

    name: MaybeSequence[str] | None
    name_contains: MaybeSequence[str] | None
    name_prefix: MaybeSequence[str] | None
    name_suffix: MaybeSequence[str] | None


class GroupFilter(BaseUUIDEntityFilter["Group", GroupField, GroupOrder]):
    """Filter for selecting `Group` records."""

    __table__: ClassVar[str] = "groups"

    name: MaybeSequence[str] | None = None
    """Filter by `name` being equal to one or more given names."""
    name_contains: MaybeSequence[str] | None = None
    """Filter by `name` containing one or more given substrings."""
    name_prefix: MaybeSequence[str] | None = None
    """Filter by `name` starting with one or more given prefixes."""
    name_suffix: MaybeSequence[str] | None = None
    """Filter by `name` ending with one or more given suffixes."""


class GroupCreate(BaseUUIDEntityCreate, slots=True):
    """Payload for creating a new `Group` record."""

    name: Name
    """Unique name identifying the group in the system."""
    description: str = ""
    """Human-readable description of the group's purpose."""


class GroupUpdate(TypedDict, total=False):
    """Partial update for an existing `Group` record."""

    name: Name
    description: str


type GroupMembershipField = Literal[
    "user_id",
    "group_id",
]
"""Field names selectable in `GroupMembership` queries."""

type GroupMembershipOrder = Literal[
    "user_id",
    "user_id:asc",
    "user_id:desc",
    "group_id",
    "group_id:asc",
    "group_id:desc",
]
"""Ordering keys accepted by `GroupMembership` queries."""


class GroupMembershipFilterArgs(
    BaseEntityFilterArgs[GroupMembershipField, GroupMembershipOrder], total=False
):
    """Keyword-argument form of `GroupMembershipFilter` for ergonomic call sites."""

    user_id: MaybeSequence[UUID] | None
    group_id: MaybeSequence[UUID] | None


class GroupMembershipFilter(
    BaseEntityFilter["GroupMembership", GroupMembershipField, GroupMembershipOrder]
):
    """Filter for selecting `GroupMembership` records."""

    __table__: ClassVar[str] = "group_memberships"

    user_id: MaybeSequence[UUID] | None = None
    """Filter by `user_id` being equal to one or more given UUIDs."""
    group_id: MaybeSequence[UUID] | None = None
    """Filter by `group_id` being equal to one or more given UUIDs."""


class GroupMembershipCreate(BaseEntityCreate, slots=True):
    """Payload for creating a new `GroupMembership` record."""

    user_id: UUID
    """ID of the user being added to the group."""
    group_id: UUID
    """ID of the group the user is joining."""


class GroupMembershipUpdate(TypedDict, total=False):
    """Partial update for an existing `GroupMembership` record.

    The record is only created or deleted, so this update payload has no mutable fields.
    """


# Present the models as part of the public module that re-exports them.
for _model in (
    GroupCreate,
    GroupFilter,
    GroupFilterArgs,
    GroupUpdate,
    GroupMembershipCreate,
    GroupMembershipFilter,
    GroupMembershipFilterArgs,
    GroupMembershipUpdate,
):
    _model.__module__ = "ceres.group"
