# @generated by scripts/update-models.py. Run 'make models' to update.

"""Generated models for the `logs` table."""

from typing import TYPE_CHECKING, ClassVar, Literal

from ceres.__internal__.record import (
    BaseRecordCreate,
    BaseRecordField,
    BaseRecordFilter,
    BaseRecordFilterArgs,
    BaseRecordOrder,
    BaseRecordUpdate,
)
from ceres.data import (
    MaybeSequence,
)
from ceres.level import Level

if TYPE_CHECKING:
    # The filters name them only as forward references.
    from ceres.logs import LogEntry  # noqa: F401

__all__ = [
    "LogEntryCreate",
    "LogEntryField",
    "LogEntryFilter",
    "LogEntryFilterArgs",
    "LogEntryOrder",
    "LogEntryUpdate",
]


type LogEntryField = (
    BaseRecordField
    | Literal[
        "level",
        "content",
    ]
)
"""Field names selectable in `LogEntry` queries."""

type LogEntryOrder = (
    BaseRecordOrder
    | Literal[
        "level",
        "level:asc",
        "level:desc",
        "content",
        "content:asc",
        "content:desc",
    ]
)
"""Ordering keys accepted by `LogEntry` queries."""


class LogEntryFilterArgs(BaseRecordFilterArgs[LogEntryField, LogEntryOrder], total=False):
    """Keyword-argument form of `LogEntryFilter` for ergonomic call sites."""

    level: MaybeSequence[Level] | None
    min_level: Level | None
    max_level: Level | None
    content: MaybeSequence[str] | None
    contains: MaybeSequence[str] | None
    prefix: MaybeSequence[str] | None
    suffix: MaybeSequence[str] | None


class LogEntryFilter(BaseRecordFilter["LogEntry", LogEntryField, LogEntryOrder]):
    """Filter for selecting `LogEntry` records."""

    __table__: ClassVar[str] = "logs"

    level: MaybeSequence[Level] | None = None
    """Filter by `level` being equal to one or more given levels."""
    min_level: Level | None = None
    """Filter by `level` being greater than or equal to the given level value."""
    max_level: Level | None = None
    """Filter by `level` being less than or equal to the given level value."""
    content: MaybeSequence[str] | None = None
    """Filter by `content` being equal to one or more given strings."""
    contains: MaybeSequence[str] | None = None
    """Filter by `content` containing one or more given substrings."""
    prefix: MaybeSequence[str] | None = None
    """Filter by `content` starting with one or more given prefixes."""
    suffix: MaybeSequence[str] | None = None
    """Filter by `content` ending with one or more given suffixes."""


class LogEntryCreate(BaseRecordCreate, slots=True):
    """Payload for creating a new `LogEntry` record."""

    level: Level
    """Severity level of the log entry."""
    content: str
    """Rendered textual content of the log entry."""


class LogEntryUpdate(BaseRecordUpdate, total=False):
    """Partial update for an existing `LogEntry` record."""

    level: Level
    content: str


# Present the models as part of the public module that re-exports them.
for _model in (LogEntryCreate, LogEntryFilter, LogEntryFilterArgs, LogEntryUpdate):
    _model.__module__ = "ceres.logs"
