# @generated by ceres-models. Run 'make models' to update.

"""Generated models for the `messages` table."""

from typing import TYPE_CHECKING, Annotated, ClassVar, Literal

from ceres.__internal__.record import (
    BaseRecordCreate,
    BaseRecordField,
    BaseRecordFilter,
    BaseRecordFilterArgs,
    BaseRecordOrder,
    BaseRecordUpdate,
)
from ceres.data import (
    BytesFromString,
    BytesToString,
    MaybeSequence,
    StrEnum,
)

if TYPE_CHECKING:
    # The filters name them only as forward references.
    from ceres.message import Message  # noqa: F401

__all__ = [
    "MessageCreate",
    "MessageData",
    "MessageDirection",
    "MessageDirectionInput",
    "MessageDirectionRaw",
    "MessageField",
    "MessageFilter",
    "MessageFilterArgs",
    "MessageOrder",
    "MessageUpdate",
]


class MessageDirection(StrEnum):
    """Direction of a message on a connection, either outbound or inbound."""

    SEND = "send"
    RECEIVE = "receive"


type MessageDirectionRaw = Literal["send", "receive"]
"""Raw string form of `MessageDirection` accepted as input."""

type MessageDirectionInput = MessageDirection | MessageDirectionRaw
"""Either a `MessageDirection` enum or its raw string form."""


type MessageData = Annotated[
    bytes,
    BytesFromString("latin-1", "ignore"),
    BytesToString("latin-1", "ignore"),
]
"""Raw message payload bytes, serialized to and from `latin-1` strings for transport."""


type MessageField = (
    BaseRecordField
    | Literal[
        "connection",
        "direction",
        "data",
    ]
)
"""Field names selectable in `Message` queries."""

type MessageOrder = (
    BaseRecordOrder
    | Literal[
        "connection",
        "connection:asc",
        "connection:desc",
        "direction",
        "direction:asc",
        "direction:desc",
        "data",
        "data:asc",
        "data:desc",
    ]
)
"""Ordering keys accepted by `Message` queries."""


class MessageFilterArgs(BaseRecordFilterArgs[MessageField, MessageOrder], total=False):
    """Keyword-argument form of `MessageFilter` for ergonomic call sites."""

    connection: MaybeSequence[str] | None
    connection_contains: MaybeSequence[str] | None
    connection_prefix: MaybeSequence[str] | None
    connection_suffix: MaybeSequence[str] | None
    direction: MaybeSequence[MessageDirectionInput] | None
    data: MaybeSequence[MessageData] | None
    contains: MaybeSequence[MessageData] | None
    prefix: MaybeSequence[MessageData] | None
    suffix: MaybeSequence[MessageData] | None


class MessageFilter(BaseRecordFilter["Message", MessageField, MessageOrder]):
    """Filter for selecting `Message` records."""

    __table__: ClassVar[str] = "messages"

    connection: MaybeSequence[str] | None = None
    """Filter by `connection` being equal to one or more given connections."""
    connection_contains: MaybeSequence[str] | None = None
    """Filter by `connection` containing one or more given substrings."""
    connection_prefix: MaybeSequence[str] | None = None
    """Filter by `connection` starting with one or more given prefixes."""
    connection_suffix: MaybeSequence[str] | None = None
    """Filter by `connection` ending with one or more given suffixes."""
    direction: MaybeSequence[MessageDirection] | None = None
    """Filter by `direction` being equal to one or more given values."""
    data: MaybeSequence[MessageData] | None = None
    """Filter by `data` being equal to one or more given byte sequences."""
    contains: MaybeSequence[MessageData] | None = None
    """Filter by `data` containing one or more given byte substrings."""
    prefix: MaybeSequence[MessageData] | None = None
    """Filter by `data` starting with one or more given byte prefixes."""
    suffix: MaybeSequence[MessageData] | None = None
    """Filter by `data` ending with one or more given byte suffixes."""


class MessageCreate(BaseRecordCreate, slots=True):
    """Payload for creating a new `Message` record."""

    connection: str | None = None
    """Optional name of the connection that produced the message."""
    direction: MessageDirection
    """Whether the message was sent or received on a connection of the local component."""
    data: MessageData
    """Raw payload bytes."""


class MessageUpdate(BaseRecordUpdate, total=False):
    """Partial update for an existing `Message` record."""

    connection: str | None
    direction: MessageDirection
    data: MessageData


# Present the models as part of the public module that re-exports them.
for _model in (MessageDirection, MessageCreate, MessageFilter, MessageFilterArgs, MessageUpdate):
    _model.__module__ = "ceres.message"
