# @generated by scripts/update-models.py. Run 'make models' to update.

"""Generated models for the `settings` table."""

from typing import TYPE_CHECKING, ClassVar, Literal, TypedDict
from uuid import UUID

from ceres.__internal__.entity import (
    BaseEntityCreate,
    BaseEntityFilter,
    BaseEntityFilterArgs,
)
from ceres.data import (
    JSONSerializable,
    MaybeSequence,
)

if TYPE_CHECKING:
    # The filters name them only as forward references.
    from ceres.setting import Setting  # noqa: F401

__all__ = [
    "SettingCreate",
    "SettingField",
    "SettingFilter",
    "SettingFilterArgs",
    "SettingOrder",
    "SettingUpdate",
]


type SettingField = Literal[
    "user_id",
    "name",
    "value",
]
"""Field names selectable in `Setting` queries."""

type SettingOrder = Literal[
    "user_id",
    "user_id:asc",
    "user_id:desc",
    "name",
    "name:asc",
    "name:desc",
]
"""Ordering keys accepted by `Setting` queries."""


class SettingFilterArgs(BaseEntityFilterArgs[SettingField, SettingOrder], total=False):
    """Keyword-argument form of `SettingFilter` for ergonomic call sites."""

    user_id: MaybeSequence[UUID] | None
    name: MaybeSequence[str] | None
    name_contains: MaybeSequence[str] | None
    name_prefix: MaybeSequence[str] | None
    name_suffix: MaybeSequence[str] | None


class SettingFilter(BaseEntityFilter["Setting", SettingField, SettingOrder]):
    """Filter for selecting `Setting` records."""

    __table__: ClassVar[str] = "settings"

    user_id: MaybeSequence[UUID] | None = None
    """Filter by `user_id` being equal to one or more given UUIDs."""
    name: MaybeSequence[str] | None = None
    """Filter by `name` being equal to one or more given names."""
    name_contains: MaybeSequence[str] | None = None
    """Filter by `name` containing one or more given substrings."""
    name_prefix: MaybeSequence[str] | None = None
    """Filter by `name` starting with one or more given prefixes."""
    name_suffix: MaybeSequence[str] | None = None
    """Filter by `name` ending with one or more given suffixes."""


class SettingCreate(BaseEntityCreate, slots=True):
    """Payload for creating a new `Setting` record."""

    user_id: UUID
    """Identifier of the user that owns this setting."""
    name: str
    """Name of the setting, unique per user."""
    value: JSONSerializable
    """Arbitrary JSON-serializable value stored for this setting."""


class SettingUpdate(TypedDict, total=False):
    """Partial update for an existing `Setting` record."""

    name: str
    value: JSONSerializable


# Present the models as part of the public module that re-exports them.
for _model in (SettingCreate, SettingFilter, SettingFilterArgs, SettingUpdate):
    _model.__module__ = "ceres.setting"
