# Generated by scripts/update-models.py. Run 'make models' to update.

"""Generated models for the `users` table."""

from typing import Any, ClassVar, Literal, TypedDict
from uuid import UUID

from ceres.__internal__.entity import (
    BaseUUIDEntityCreate,
    BaseUUIDEntityField,
    BaseUUIDEntityFilter,
    BaseUUIDEntityFilterArgs,
    BaseUUIDEntityOrder,
)
from ceres.data import (
    EmailAddress,
    MaybeSequence,
    Password,
    PasswordHash,
    Username,
)

__all__ = [
    "UserCreate",
    "UserField",
    "UserFilter",
    "UserFilterArgs",
    "UserOrder",
    "UserUpdate",
]


type UserField = (
    BaseUUIDEntityField
    | Literal[
        "username",
        "email",
        "admin",
        "disabled",
    ]
)
"""Field names selectable in `User` queries."""

type UserOrder = (
    BaseUUIDEntityOrder
    | Literal[
        "username",
        "username:asc",
        "username:desc",
        "email",
        "email:asc",
        "email:desc",
        "admin",
        "admin:asc",
        "admin:desc",
        "disabled",
        "disabled:asc",
        "disabled:desc",
    ]
)
"""Ordering keys accepted by `User` queries."""


class UserFilterArgs(BaseUUIDEntityFilterArgs[UserField, UserOrder], total=False):
    """Keyword-argument form of `UserFilter` for ergonomic call sites."""

    username: MaybeSequence[str] | None
    username_contains: MaybeSequence[str] | None
    username_prefix: MaybeSequence[str] | None
    username_suffix: MaybeSequence[str] | None
    email: MaybeSequence[EmailAddress] | None
    email_contains: MaybeSequence[str] | None
    email_prefix: MaybeSequence[str] | None
    email_suffix: MaybeSequence[str] | None
    admin: bool | None
    disabled: bool | None


class UserFilter(BaseUUIDEntityFilter["User", UserField, UserOrder]):
    """Filter for selecting `User` records."""

    __table__: ClassVar[str] = "users"

    username: MaybeSequence[str] | None = None
    """Filter by `username`."""
    username_contains: MaybeSequence[str] | None = None
    """Filter by `username` containing one or more given substrings."""
    username_prefix: MaybeSequence[str] | None = None
    """Filter by `username` starting with one or more given prefixes."""
    username_suffix: MaybeSequence[str] | None = None
    """Filter by `username` ending with one or more given suffixes."""
    email: MaybeSequence[EmailAddress] | None = None
    """The account's email address, whose operations fold case the way the Python filter's do."""
    email_contains: MaybeSequence[str] | None = None
    """Filter by `email` containing one or more given substrings."""
    email_prefix: MaybeSequence[str] | None = None
    """Filter by `email` starting with one or more given prefixes."""
    email_suffix: MaybeSequence[str] | None = None
    """Filter by `email` ending with one or more given suffixes."""
    admin: bool | None = None
    """Filter by `admin`."""
    disabled: bool | None = None
    """Filter by `disabled`."""


class UserCreate(BaseUUIDEntityCreate, slots=True):
    """Payload for creating a new `User` record."""

    username: str
    """The username of the user."""
    email: EmailAddress
    """The account's email address, whose operations fold case the way the Python filter's do."""
    password: Password | PasswordHash
    """The Argon2 hash of the account's password."""
    admin: bool = False
    """The admin of the user."""
    disabled: bool = False
    """The disabled of the user."""


class UserUpdate(TypedDict, total=False):
    """Partial update for an existing `User` record."""

    username: str
    email: EmailAddress
    password: Password | PasswordHash
    admin: bool
    disabled: bool
