# Generated by scripts/update-models.py. Run 'make models' to update.

"""Generated models for the `variables` table."""

from typing import TYPE_CHECKING, ClassVar, Literal, TypedDict

from ceres.__internal__.entity import (
    BaseAddressEntityCreate,
    BaseAddressEntityField,
    BaseAddressEntityFilter,
    BaseAddressEntityFilterArgs,
    BaseAddressEntityOrder,
)
from ceres.data import (
    FromYAML,
    JSONSerializable,
    MaybeSequence,
)

if TYPE_CHECKING:
    # The filters name them only as forward references.
    from ceres.variable import Variable  # noqa: F401

__all__ = [
    "VariableCreate",
    "VariableField",
    "VariableFilter",
    "VariableFilterArgs",
    "VariableOrder",
    "VariableUpdate",
]


type VariableField = (
    BaseAddressEntityField
    | Literal[
        "name",
        "value",
    ]
)
"""Field names selectable in `Variable` queries."""

type VariableOrder = (
    BaseAddressEntityOrder
    | Literal[
        "name",
        "name:asc",
        "name:desc",
        "value",
        "value:asc",
        "value:desc",
    ]
)
"""Ordering keys accepted by `Variable` queries."""


class VariableFilterArgs(BaseAddressEntityFilterArgs[VariableField, VariableOrder], total=False):
    """Keyword-argument form of `VariableFilter` for ergonomic call sites."""

    name: MaybeSequence[str] | None
    name_contains: MaybeSequence[str] | None
    name_prefix: MaybeSequence[str] | None
    name_suffix: MaybeSequence[str] | None
    internal: bool | None
    value: JSONSerializable | None


class VariableFilter(BaseAddressEntityFilter["Variable", VariableField, VariableOrder]):
    """Filter for selecting `Variable` records."""

    __table__: ClassVar[str] = "variables"

    name: MaybeSequence[str] | None = None
    """Filter by `name` being equal to one or more given names."""
    name_contains: MaybeSequence[str] | None = None
    """Filter by `name` containing one or more given substrings."""
    name_prefix: MaybeSequence[str] | None = None
    """Filter by `name` starting with one or more given prefixes."""
    name_suffix: MaybeSequence[str] | None = None
    """Filter by `name` ending with one or more given suffixes."""
    internal: bool | None = None
    """Filter variables based on whether they are internal or not. Internal variables are those that
    start with and end with two underscores, for example `__enabled__`. If `None`, both internal and
    non-internal variables will be matched.
    """
    __nullable_filters__: ClassVar[frozenset[str]] = frozenset({"value"})

    value: FromYAML[JSONSerializable] | None = None
    """Filter by `value` being exactly equal to the given JSON-serializable value.

    The value reads as YAML, matching how the create and update models take it, so a command line
    comparing against a number or a boolean compares against that rather than against its text.
    """


class VariableCreate(BaseAddressEntityCreate, slots=True):
    """Payload for creating a new `Variable` record."""

    name: str
    """Name of the variable, unique per owning address."""
    value: FromYAML[JSONSerializable]
    """Arbitrary JSON-serializable value stored for this variable."""


class VariableUpdate(TypedDict, total=False):
    """Partial update for an existing `Variable` record."""

    name: str
    value: FromYAML[JSONSerializable]
