# @generated by scripts/update-models.py. Run 'make models' to update.

"""Generated models for the `workspace_edits`, `workspaces` tables."""

from typing import TYPE_CHECKING, ClassVar, Literal, TypedDict
from uuid import UUID

from pydantic import Field

from ceres.__internal__.entity import (
    BaseEntityCreate,
    BaseEntityFilter,
    BaseEntityFilterArgs,
    BaseUUIDEntityCreate,
    BaseUUIDEntityField,
    BaseUUIDEntityFilter,
    BaseUUIDEntityFilterArgs,
    BaseUUIDEntityOrder,
)
from ceres.address import Address
from ceres.data import (
    JSONSerializableDict,
    MaybeSequence,
    NonEmptyStr,
)

if TYPE_CHECKING:
    # The filters name them only as forward references.
    from ceres.workspace import Workspace, WorkspaceEdit  # noqa: F401

__all__ = [
    "WorkspaceCreate",
    "WorkspaceEditCreate",
    "WorkspaceEditField",
    "WorkspaceEditFilter",
    "WorkspaceEditFilterArgs",
    "WorkspaceEditOrder",
    "WorkspaceEditUpdate",
    "WorkspaceField",
    "WorkspaceFilter",
    "WorkspaceFilterArgs",
    "WorkspaceOrder",
    "WorkspaceUpdate",
]


type WorkspaceEditField = Literal[
    "user_id",
    "workspace_id",
    "data",
]
"""Field names selectable in `WorkspaceEdit` queries."""

type WorkspaceEditOrder = Literal[
    "user_id",
    "user_id:asc",
    "user_id:desc",
    "workspace_id",
    "workspace_id:asc",
    "workspace_id:desc",
]
"""Ordering keys accepted by `WorkspaceEdit` queries."""


class WorkspaceEditFilterArgs(
    BaseEntityFilterArgs[WorkspaceEditField, WorkspaceEditOrder], total=False
):
    """Keyword-argument form of `WorkspaceEditFilter` for ergonomic call sites."""

    user_id: MaybeSequence[UUID] | None
    workspace_id: MaybeSequence[UUID] | None


class WorkspaceEditFilter(
    BaseEntityFilter["WorkspaceEdit", WorkspaceEditField, WorkspaceEditOrder]
):
    """Filter for selecting `WorkspaceEdit` records."""

    __table__: ClassVar[str] = "workspace_edits"

    user_id: MaybeSequence[UUID] | None = None
    """Filter by `user_id` being equal to one or more given UUIDs."""
    workspace_id: MaybeSequence[UUID] | None = None
    """Filter by `workspace_id` being equal to one or more given UUIDs."""


class WorkspaceEditCreate(BaseEntityCreate, slots=True):
    """Payload for creating a new `WorkspaceEdit` record."""

    user_id: UUID
    """ID of the user whose draft edit this is."""
    workspace_id: UUID
    """ID of the workspace being edited."""
    data: JSONSerializableDict
    """In-progress edit payload, serialized as JSON."""


class WorkspaceEditUpdate(TypedDict, total=False):
    """Partial update for an existing `WorkspaceEdit` record."""

    data: JSONSerializableDict


type WorkspaceField = (
    BaseUUIDEntityField
    | Literal[
        "name",
        "scope",
        "owner_id",
        "show_when_logged_out",
        "data",
    ]
)
"""Field names selectable in `Workspace` queries."""

type WorkspaceOrder = (
    BaseUUIDEntityOrder
    | Literal[
        "name",
        "name:asc",
        "name:desc",
        "scope",
        "scope:asc",
        "scope:desc",
        "owner_id",
        "owner_id:asc",
        "owner_id:desc",
        "show_when_logged_out",
        "show_when_logged_out:asc",
        "show_when_logged_out:desc",
    ]
)
"""Ordering keys accepted by `Workspace` queries."""


class WorkspaceFilterArgs(BaseUUIDEntityFilterArgs[WorkspaceField, WorkspaceOrder], total=False):
    """Keyword-argument form of `WorkspaceFilter` for ergonomic call sites."""

    name: MaybeSequence[str] | None
    name_contains: MaybeSequence[str] | None
    name_prefix: MaybeSequence[str] | None
    name_suffix: MaybeSequence[str] | None
    scope: MaybeSequence[Address] | None
    owner_id: MaybeSequence[UUID] | None
    show_when_logged_out: bool | None
    placed_on_engine: bool | None
    owned: bool | None


class WorkspaceFilter(BaseUUIDEntityFilter["Workspace", WorkspaceField, WorkspaceOrder]):
    """Filter for selecting `Workspace` records."""

    __table__: ClassVar[str] = "workspaces"

    name: MaybeSequence[str] | None = None
    """Filter by `name` being equal to one or more given names."""
    name_contains: MaybeSequence[str] | None = None
    """Filter by `name` containing one or more given substrings."""
    name_prefix: MaybeSequence[str] | None = None
    """Filter by `name` starting with one or more given prefixes."""
    name_suffix: MaybeSequence[str] | None = None
    """Filter by `name` ending with one or more given suffixes."""
    scope: MaybeSequence[Address] | None = None
    """Filter by `scope` being equal to one or more given addresses."""
    owner_id: MaybeSequence[UUID] | None = None
    """Filter by `owner_id` being equal to one or more given UUIDs."""
    show_when_logged_out: bool | None = None
    """Filter by `show_when_logged_out` being either `True` or `False`."""
    placed_on_engine: bool | None = None
    """Filter by whether the workspace is placed on the engine root rather than a component."""
    owned: bool | None = None
    """Filter by whether the workspace is private to an owner at all."""


class WorkspaceCreate(BaseUUIDEntityCreate, slots=True):
    """Payload for creating a new `Workspace` record."""

    name: NonEmptyStr
    """Human-readable name of the workspace."""
    scope: Address = Address("~")
    """Address this workspace is placed on. `~` is the engine root, anything else a component."""
    owner_id: UUID | None = None
    """Owning user when this workspace is private, `None` when it is shared."""
    show_when_logged_out: bool = False
    """Whether this workspace is part of the set an unauthenticated visitor sees."""
    data: JSONSerializableDict = Field(default_factory=dict)
    """Free-form structured payload attached to the workspace."""


class WorkspaceUpdate(TypedDict, total=False):
    """Partial update for an existing `Workspace` record."""

    name: NonEmptyStr
    scope: Address
    owner_id: UUID | None
    show_when_logged_out: bool
    data: JSONSerializableDict


# Present the models as part of the public module that re-exports them.
for _model in (
    WorkspaceEditCreate,
    WorkspaceEditFilter,
    WorkspaceEditFilterArgs,
    WorkspaceEditUpdate,
    WorkspaceCreate,
    WorkspaceFilter,
    WorkspaceFilterArgs,
    WorkspaceUpdate,
):
    _model.__module__ = "ceres.workspace"
