[tool.poetry]
name = "ceres"
version = "0.9.0"
description = "APL - Ceres"
authors = ["Jake Ploskey <jploskey@uw.edu>"]
include = ["./ceres/**/*.py", "./ceres/static/**/*", "./ceres/py.typed"]

[tool.poetry.dependencies]
python = "^3.12"
aiohttp = "^3.8.0"
aiosmtplib = "^1.1.0"
aiosqlite = ">=0.17.0"
anyio = "^4.0.0"
apscheduler = "^3.9.0"
argon2-cffi = "^23.1.0"
asgiref = "^3.7.0"
asyncpg = "^0.28.0"
bcrypt = "^4.1.0"
email-validator = "^2.1.0"
fastapi = ">=0.101.1"
humanize = "^4.9.0"
hypercorn = "^0.16.0"
jinja2 = "^3.1.0"
launchd = { version = "0.3.0", platform = "darwin" }
mistune = ">=3.0.0rc5"
psycopg = { version = "^3.1.0", extras = ["binary"] }
pydantic = "^2.1.0"
pydantic-extra-types = "^2.0.0"
pyjwt = "^2.8.0"
pyyaml = "^6.0.0"
setproctitle = "^1.0.0"
sqlalchemy = { version = "^2.0.0", extras = ["asyncio"] }
sqlparse = ">=0.4.0"
typer = { version = ">=0.6.0", extras = ["all"] }
uvloop = ">=0.17.0"
watchfiles = ">=0.10.0"
websockets = "^10.0.0"

[tool.poetry.group.dev.dependencies]
black = "24.4.2"
pyright = "1.1.365"
pytest = "7.4.0"
pytest-asyncio = "0.21.1"
ruff = "0.4.7"
types-pyyaml = "^6.0.12.11"

[tool.poetry.group.docs.dependencies]
mike = "2.0.0"
mkdocs-material = "9.5.11"
mkdocstrings = { extras = ["python"], version = "0.24.1" }

[tool.poetry.scripts]
ceres = "ceres._internal.cli:main"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100

lint.ignore = ["F402"]

[tool.pyright]
include = ["ceres", "tests"]
# reportAttributeAccessIssue = false         # TODO: Remove this once TypeForm[T] exists.
reportImplicitOverride = true
reportIncompatibleVariableOverride = false
reportMissingTypeStubs = false
reportPrivateUsage = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnnecessaryIsInstance = false
reportUntypedFunctionDecorator = false
reportUnusedFunction = false
typeCheckingMode = "strict"
useLibraryCodeForTypes = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = "ignore:.*pkg_resources.*:DeprecationWarning"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
