const icons = {
  add: 'add',
  arrowRight: 'arrow_right',
  cancel: 'cancel',
  clearLocalStorage: 'delete_sweep',
  close: 'close',
  darkMode: 'dark_mode',
  dashboard: 'space_dashboard',
  delete: 'delete',
  dropDown: 'arrow_drop_down',
  dropUp: 'arrow_drop_up',
  help: 'help',
  job: 'build',
  json: 'data_object',
  lightMode: 'light_mode',
  menu: 'menu',
  remove: 'remove',
  reset: 'refresh',
  script: 'code',
  search: 'search',
  send: 'send',
  settings: 'settings',
  tools: 'construction',
  unit: 'fiber_manual_record',
  units: 'workspaces',
  user: 'person',
} as const

export default icons
