# This file is generated by ceres-stubs. Do not edit it directly.

from collections.abc import Sequence
from datetime import datetime, timedelta
from enum import Enum
from os import PathLike
from pathlib import Path
from typing import Any, Self, final

from pydantic import SecretStr

__all__ = [
    "Argon2HashingConfig",
    "BCryptHashingConfig",
    "ConsoleConfig",
    "DatabaseConfigHooks",
    "EntityTable",
    "JsonParameter",
    "LoggingConfig",
    "NativeFilter",
    "NativeServer",
    "PackingProgram",
    "PostgresDatabaseConfig",
    "RecordBatch",
    "RecordChunks",
    "RecordFetcher",
    "RecordTable",
    "RecordWriter",
    "RowChunks",
    "SQLiteDatabaseConfig",
    "ServerAuthenticationConfig",
    "ServerCORSConfig",
    "ServerCompressionConfig",
    "ServerConfig",
    "ServerSSLConfig",
    "ServiceConfig",
    "Store",
    "TursoDatabaseConfig",
    "entity_filter_keys",
    "hash_argon2",
    "hash_bcrypt",
    "insert_compiled",
    "normalize_email",
    "openapi_schema",
    "record_filter_keys",
    "special_use_domains",
    "verify_argon2",
    "verify_bcrypt",
    "verify_password",
]

class Argon2HashingConfig:
    r"""
    Configuration for the Argon2id password hashing algorithm.

    Default parameters mirror `argon2.profiles.RFC_9106_LOW_MEMORY`, callers can tune
    them to trade memory and CPU cost against latency.
    """
    @property
    def time_cost(self) -> int:
        r"""
        Number of iterations Argon2 performs.
        """
    @property
    def memory_cost(self) -> int:
        r"""
        Memory budget in KiB.
        """
    @property
    def parallelism(self) -> int:
        r"""
        Number of parallel lanes used during hashing.
        """
    @property
    def hash_length(self) -> int:
        r"""
        Length of the produced hash in bytes.
        """
    @property
    def salt_length(self) -> int:
        r"""
        Length of the random salt in bytes.
        """
    @property
    def type(self) -> str:
        r"""
        The algorithm selector for this configuration.
        """
    def __new__(
        cls,
        *,
        time_cost: int | None = None,
        memory_cost: int | None = None,
        parallelism: int | None = None,
        hash_length: int | None = None,
        salt_length: int | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class BCryptHashingConfig:
    r"""
    Configuration for the bcrypt password hashing algorithm.
    """
    @property
    def rounds(self) -> int:
        r"""
        Cost factor controlling how expensive each hash is to compute.
        """
    @property
    def type(self) -> str:
        r"""
        The algorithm selector for this configuration.
        """
    def __new__(cls, *, rounds: int | None = None) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ConsoleConfig:
    r"""
    Branding and layout options for the engine's web console.
    """
    @property
    def title(self) -> str | None:
        r"""
        Title shown in the console's browser tab and header.
        """
    @property
    def favicon(self) -> Path | None:
        r"""
        Path to a favicon image served by the console.
        """
    def __new__(
        cls, *, title: str | None = None, favicon: str | PathLike[str] | Path | None = None
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class DatabaseConfigHooks:
    r"""
    SQL statements executed at well-known points in the database lifecycle.
    """
    @property
    def init(self) -> list[str] | None:
        r"""
        Statements run once when the database is first created.
        """
    @property
    def connect(self) -> list[str] | None:
        r"""
        Statements run on every new connection.
        """
    @property
    def close(self) -> list[str] | None:
        r"""
        Statements run before a connection is closed.
        """
    def __new__(
        cls,
        *,
        init: Sequence[str] | None = None,
        connect: Sequence[str] | None = None,
        close: Sequence[str] | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

@final
class JsonParameter:
    r"""
    A whole JSON document as one statement parameter.

    The columns that store a document bind it as one value, and PostgreSQL's `jsonb` refuses
    a text bind, so the fact that a parameter is a document has to survive the trip out to
    Python and back rather than arriving as a string nobody can tell apart from a name.
    """
    def __repr__(self) -> str:
        r"""
        The document's serialized form, which is what a text column stores.
        """

class LoggingConfig:
    r"""
    Per-component or per-engine logging configuration.

    `output` and `store` set minimum levels for the streamed and persisted log streams, and
    the toggle fields enable optional logging of specific record types, accepting either a
    boolean or a minimum level.
    """
    @property
    def output(self) -> str:
        r"""
        Minimum severity that reaches the engine's streamed log output.
        """
    @property
    def store(self) -> str:
        r"""
        Minimum severity persisted to the engine's log store.
        """
    @property
    def events(self) -> bool | str:
        r"""
        Whether to log events, or the minimum severity to log them at.
        """
    @property
    def messages(self) -> bool | str:
        r"""
        Whether to log raw connection messages, or the minimum severity to log them at.
        """
    @property
    def particles(self) -> bool | str:
        r"""
        Whether to log parsed particles, or the minimum severity to log them at.
        """
    @property
    def alerts(self) -> bool | str:
        r"""
        Whether to log alerts, or the minimum severity to log them at.
        """
    def __new__(
        cls,
        *,
        output: str | None = None,
        store: str | None = None,
        events: bool | str | None = None,
        messages: bool | str | None = None,
        particles: bool | str | None = None,
        alerts: bool | str | None = None,
    ) -> Self: ...
    def merged(self, other: LoggingConfig) -> LoggingConfig:
        r"""
        Overlay another configuration's explicitly-set fields onto this one.
        """
    def provided(self) -> dict[str, Any]:
        r"""
        Return the explicitly-set fields as a plain dictionary.

        Supports rebuilding an equivalent configuration without turning resolved defaults
        into explicit settings.
        """
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

@final
class NativeFilter:
    r"""
    A parsed filter, held natively and reused across calls.
    """
    @property
    def limit(self) -> int | None:
        r"""
        The filter's limit, `None` when unbounded.
        """
    @property
    def offset(self) -> int | None:
        r"""
        The filter's offset, `None` when unset.
        """
    @staticmethod
    def from_pairs(table: str, pairs: Sequence[tuple[str, str]]) -> NativeFilter:
        r"""
        Parse a filter from ordered wire query pairs.
        """
    @staticmethod
    def from_json(table: str, json: str) -> NativeFilter:
        r"""
        Parse a filter from its serialized JSON form, the filter model's dump.
        """
    def where_sql(self, dialect: str, now: datetime | None = None) -> str | None:
        r"""
        The `WHERE` conditions as inline SQL for a dialect, `None` when the filter is
        unconditional.

        The text embeds into a statement the caller builds, so values render as literals
        rather than binds. The caller's clock decides age-relative conditions, so a
        session under a faked or frozen time stays authoritative.
        """
    def order_sql(self, dialect: str) -> str | None:
        r"""
        The `ORDER BY` terms as inline SQL for a dialect, including the table's default
        ordering.
        """
    def compiled(
        self, dialect: str, *, count: bool = False, now: datetime | None = None
    ) -> tuple[str, list[Any]]:
        r"""
        Compile to SQL and its parameters for a dialect, a listing statement or a count.

        The parameters arrive in placeholder order for a driver-level execute, `?` style
        for the SQLite family and `$n` for PostgreSQL. The caller's clock decides
        age-relative conditions, and the whole statement resolves it once, so `min_age`
        and `max_age` in one filter cannot straddle a tick.
        """
    def exists_compiled(self, dialect: str, now: datetime | None = None) -> tuple[str, list[Any]]:
        r"""
        Compile the existence check to SQL and its parameters for a dialect.

        The shape an `any` command runs, which stops at the first matching row.
        """
    def delete_compiled(self, dialect: str, now: datetime | None = None) -> tuple[str, list[Any]]:
        r"""
        Compile the delete to SQL and its parameters for a dialect.
        """
    def update_compiled(
        self, dialect: str, assign: str, now: datetime | None = None
    ) -> tuple[str, list[Any]]:
        r"""
        Compile an update to SQL and its parameters for a dialect.

        `assign` is the serialized JSON object of new values, and each one encodes into the
        form its column stores, so the caller cannot write a value the column did not ask
        for. A refusal carries the sentence naming the key and what it wanted.
        """
    def matches(self, record_json: str, now: datetime | None = None) -> bool:
        r"""
        Whether one serialized row matches this filter.

        Query controls and subsampling do not participate, this reads a single row the way
        live stream filtering does.
        """

@final
class NativeServer:
    r"""
    A natively-served HTTP application.

    Binds at construction, so the real port is known immediately, and serves as an
    awaitable until stopped. The web form carries the console and terminates TLS, the
    CLI form binds loopback on an ephemeral port and requires its token instead.
    """
    @property
    def port(self) -> int:
        r"""
        The port the server actually bound.
        """
    @staticmethod
    def web(
        host: Any,
        config: ServerConfig,
        console_directory: str | PathLike[str] | Path,
        favicon_ico: str | PathLike[str] | Path,
        favicon_png: str | PathLike[str] | Path,
        favicon_svg: str | PathLike[str] | Path,
        records: RecordFetcher | None = None,
    ) -> NativeServer:
        r"""
        Bind the web application, serving the console and API on the configured address.
        """
    @staticmethod
    def cli(
        host: Any, config: ServerConfig, token: str, records: RecordFetcher | None = None
    ) -> NativeServer:
        r"""
        Bind the CLI control application on an ephemeral loopback port.
        """
    def serve(self) -> Any:
        r"""
        Serve until stopped, as an awaitable.
        """
    def stop(self, grace: float = 5.0) -> None:
        r"""
        Stop the server, letting in-flight requests finish within the grace period.
        """

@final
class PackingProgram:
    r"""
    A compiled binary packing program.

    Built by `ceres.data.binary` from a packing schema tree and executed natively, packing a
    whole value into one buffer and unpacking a whole buffer into one value tree per call.
    Models unpack to plain dictionaries, validation and model construction stay with the
    caller.
    """
    @property
    def size(self) -> int:
        r"""
        The packed size in bytes.
        """
    def __new__(cls, spec: dict[str, Any]) -> Self: ...
    def pack(self, value: Any, order: str | None = None) -> bytes:
        r"""
        Pack a value into its binary representation.
        """
    def unpack(self, data: bytes, offset: int = 0, order: str | None = None) -> Any:
        r"""
        Unpack a value tree from binary data.
        """

class PostgresDatabaseConfig:
    r"""
    Configuration for a PostgreSQL-backed database.
    """
    @property
    def host(self) -> str:
        r"""
        Host the database server listens on.
        """
    @property
    def port(self) -> int | None:
        r"""
        Port the database server listens on.
        """
    @property
    def database(self) -> str:
        r"""
        Name of the database to connect to.
        """
    @property
    def user(self) -> str:
        r"""
        User to authenticate as.
        """
    @property
    def password(self) -> str | None:
        r"""
        Password to authenticate with.
        """
    @property
    def hooks(self) -> DatabaseConfigHooks:
        r"""
        SQL statements executed at well-known points in the database lifecycle.
        """
    @property
    def engine(self) -> dict[str, Any]:
        r"""
        Extra keyword arguments forwarded to the SQLAlchemy engine factory.
        """
    @property
    def hashing(self) -> BCryptHashingConfig | Argon2HashingConfig:
        r"""
        Password hashing configuration used for users stored in this database.
        """
    @property
    def query(self) -> dict[str, str | list[str]] | None:
        r"""
        Optional database-specific connection string query parameters.
        """
    @property
    def type(self) -> str:
        r"""
        The backend selector for this configuration.
        """
    def __new__(
        cls,
        *,
        host: str | None = None,
        port: int | None = None,
        database: str | None = None,
        user: str | None = None,
        password: str | SecretStr | None = None,
        hooks: DatabaseConfigHooks | dict[str, Any] | None = None,
        engine: dict[str, Any] | None = None,
        hashing: BCryptHashingConfig | Argon2HashingConfig | dict[str, Any] | None = None,
        query: dict[str, str | list[str]] | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

@final
class RecordBatch:
    r"""
    A batch of records held natively, parsed from database rows.

    Built through `parse` from the raw row mappings a query produces, and serialized with
    `to_json` as the API's wire format for a record listing.
    """
    @staticmethod
    def parse(table: RecordTable, rows: Sequence[Any]) -> RecordBatch:
        r"""
        Parse database row mappings into a native batch.

        Row values arrive through the database layer's column mappers, so they are trusted
        rather than revalidated here.
        """
    def __len__(self) -> int: ...
    @staticmethod
    def record_to_json(table: RecordTable, record: Any) -> bytes:
        r"""
        Serialize one live record entity as JSON in the API's wire format.

        Reads the entity object's attributes rather than row values, so streamed records
        serialize natively too. Raises `ValueError` for payload values richer than JSON,
        which the caller serializes through Pydantic instead.
        """
    def to_json(self) -> bytes:
        r"""
        Serialize the batch as a JSON array in the API's wire format.
        """
    def to_json_lines(self, fields: Sequence[tuple[str, str]] | None = None) -> bytes:
        r"""
        Serialize the batch as JSON lines in the wire format, one record per line.

        The shape a CLI record dump writes, so a select can produce its whole output in
        one native pass. A field projection, ordered `(field, alias)` pairs, renders
        each line as an object of the aliased wire values, unknown or absent fields
        serializing as null.
        """
    def to_csv_lines(
        self, fields: Sequence[tuple[str, str]] | None = None, *, header: bool = True
    ) -> str:
        r"""
        Render the batch as CSV lines in the wire cell forms, under a header row
        unless suppressed.

        The shape a CSV record dump writes, quoted the way the Python `csv` writer
        quotes, so a select can produce its whole output in one native pass. A field
        projection, ordered `(field, alias)` pairs, selects the columns, with the
        aliases as the header row.
        """

@final
class RecordChunks:
    r"""
    A streamed record query's chunks, taken one await at a time.

    Dropping this ends the query, because the next chunk it tries to hand over has
    nowhere to go.
    """
    def next(self) -> Any:
        r"""
        The next chunk, as an awaitable `RecordBatch`, `None` once the query is spent.

        Waiting for a chunk blocks a thread of its own rather than the event loop, so a
        slow query leaves the caller's asyncio loop free.
        """

@final
class RecordFetcher:
    r"""
    A natively-connected view of a Ceres database, serving record reads.

    Built from resolved connection parameters rather than a configuration, because the
    Python layer resolves per-instance details like temporary SQLite paths. Connections
    open lazily on first use.
    """
    @staticmethod
    def sqlite(path: str) -> RecordFetcher:
        r"""
        Open a fetcher over a SQLite database file.
        """
    @staticmethod
    def postgres(
        host: str,
        database: str,
        user: str,
        port: int | None = None,
        password: str | None = None,
        settings: Sequence[tuple[str, str]] = [],
        parameters: Sequence[tuple[str, str]] = [],
    ) -> RecordFetcher:
        r"""
        Open a fetcher over a PostgreSQL database.

        `settings` are per-connection server settings like `search_path`, matching the ones
        the query layer passes its own driver.
        """
    def fetch_sql(self, table: RecordTable, sql: str, parameters: list[Any]) -> Any:
        r"""
        Execute a compiled record query, as an awaitable `RecordBatch`.

        The statement text and parameters come from the query layer's own compiler, so any
        filter it can express runs natively with identical semantics.
        """
    def stream_sql(self, table: RecordTable, sql: str, parameters: list[Any]) -> RecordChunks:
        r"""
        Execute a compiled record query, as chunks the caller walks one at a time.

        The chunked twin of `fetch_sql`, for a dump that renders and writes as it reads.
        The query runs on its own thread and hands each decoded chunk over, so the reader
        sets the pace and neither side ever holds more than a chunk.
        """
    def fetch(self, table: RecordTable, limit: int | None = None, offset: int | None = None) -> Any:
        r"""
        Fetch a record listing ordered by timestamp, as an awaitable `RecordBatch`.
        """
    def fetch_pairs(self, table: RecordTable, pairs: Sequence[tuple[str, str]]) -> Any:
        r"""
        Fetch the records matching filter query pairs, as an awaitable `RecordBatch`.

        The pairs parse against the native filter subset, and a request outside it
        answers `None` synchronously so the caller delegates to the query layer.
        """
    def count_pairs(self, table: RecordTable, pairs: Sequence[tuple[str, str]]) -> Any:
        r"""
        Count the records matching filter query pairs, as an awaitable count.

        Like `fetch_pairs`, a request outside the native subset answers `None`
        synchronously so the caller delegates.
        """

@final
class RecordWriter:
    r"""
    A natively-connected writer for record entities.

    Entities extract into native records synchronously, then a whole flush upserts in one
    transaction on the writer's own pool. Built from resolved connection parameters like
    the fetcher, and matching the query layer's connection semantics.
    """
    @staticmethod
    def sqlite(path: str) -> RecordWriter:
        r"""
        Open a writer over a SQLite database file.
        """
    @staticmethod
    def postgres(
        host: str,
        database: str,
        user: str,
        port: int | None = None,
        password: str | None = None,
        settings: Sequence[tuple[str, str]] = [],
        parameters: Sequence[tuple[str, str]] = [],
    ) -> RecordWriter:
        r"""
        Open a writer over a PostgreSQL database, with per-connection server settings.
        """
    def write(self, groups: list[tuple[RecordTable, list[Any]]]) -> Any:
        r"""
        Upsert groups of record entities atomically, as an awaitable.

        Each group pairs a record table name with the entities to write there. Raises
        `ValueError` when an entity cannot extract natively, before anything writes.
        """

@final
class RowChunks:
    r"""
    A streamed result, handed over one chunk of rows at a time.
    """
    def next(self) -> Any:
        r"""
        The next chunk of column mappings, `None` once the query is spent.

        Waiting for a chunk blocks a thread of its own rather than the event loop, so a
        slow query leaves the caller's asyncio loop free.
        """

class SQLiteDatabaseConfig:
    r"""
    Configuration for a SQLite-backed database, the default for local deployments.
    """
    @property
    def path(self) -> Path | None:
        r"""
        Path to the SQLite file. Omit to use a temporary on-disk file.
        """
    @property
    def hooks(self) -> DatabaseConfigHooks:
        r"""
        SQL statements executed at well-known points in the database lifecycle.
        """
    @property
    def engine(self) -> dict[str, Any]:
        r"""
        Extra keyword arguments forwarded to the SQLAlchemy engine factory.
        """
    @property
    def hashing(self) -> BCryptHashingConfig | Argon2HashingConfig:
        r"""
        Password hashing configuration used for users stored in this database.
        """
    @property
    def query(self) -> dict[str, str | list[str]] | None:
        r"""
        Optional database-specific connection string query parameters.
        """
    @property
    def type(self) -> str:
        r"""
        The backend selector for this configuration.
        """
    def __new__(
        cls,
        *,
        path: str | PathLike[str] | Path | None = None,
        hooks: DatabaseConfigHooks | dict[str, Any] | None = None,
        engine: dict[str, Any] | None = None,
        hashing: BCryptHashingConfig | Argon2HashingConfig | dict[str, Any] | None = None,
        query: dict[str, str | list[str]] | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ServerAuthenticationConfig:
    r"""
    Authentication settings for the engine's HTTP server.
    """
    @property
    def secret(self) -> str:
        r"""
        Secret used to sign and verify authentication tokens.
        """
    @property
    def duration(self) -> timedelta:
        r"""
        Lifetime of an issued authentication token.
        """
    @property
    def allow_impersonate(self) -> bool:
        r"""
        Whether an administrator may take on another user's identity without their password.
        """
    def __new__(
        cls,
        *,
        secret: str | None = None,
        duration: timedelta | int | float | str | None = None,
        allow_impersonate: bool | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ServerCORSConfig:
    r"""
    Cross-origin resource sharing settings for the engine's HTTP server.
    """
    @property
    def enabled(self) -> bool:
        r"""
        Whether cross-origin resource sharing is enabled.
        """
    @property
    def allow_origins(self) -> str | list[str]:
        r"""
        Origins allowed to make cross-origin requests.
        """
    @property
    def allow_origin_regex(self) -> str | None:
        r"""
        Pattern matching additional allowed origins.
        """
    @property
    def allow_methods(self) -> str | list[str]:
        r"""
        Methods allowed for cross-origin requests.
        """
    @property
    def allow_headers(self) -> str | list[str]:
        r"""
        Headers allowed in cross-origin requests.
        """
    @property
    def allow_credentials(self) -> bool:
        r"""
        Whether credentialed cross-origin requests are allowed.
        """
    @property
    def expose_headers(self) -> str | list[str]:
        r"""
        Headers exposed to cross-origin callers.
        """
    @property
    def max_age(self) -> int:
        r"""
        How long preflight responses may be cached, in seconds.
        """
    def __new__(
        cls,
        *,
        enabled: bool | None = None,
        allow_origins: str | list[str] | None = None,
        allow_origin_regex: str | None = None,
        allow_methods: str | list[str] | None = None,
        allow_headers: str | list[str] | None = None,
        allow_credentials: bool | None = None,
        expose_headers: str | list[str] | None = None,
        max_age: int | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ServerCompressionConfig:
    r"""
    Response compression settings for the engine's HTTP server.
    """
    @property
    def enabled(self) -> bool:
        r"""
        Whether response compression is enabled.
        """
    @property
    def min_size(self) -> int:
        r"""
        Minimum response size in bytes before compression is applied.
        """
    @property
    def zstd(self) -> bool:
        r"""
        Whether zstd compression is offered.
        """
    @property
    def zstd_level(self) -> int:
        r"""
        Zstd compression level.
        """
    @property
    def brotli(self) -> bool:
        r"""
        Whether brotli compression is offered.
        """
    @property
    def brotli_quality(self) -> int:
        r"""
        Brotli compression quality.
        """
    @property
    def gzip(self) -> bool:
        r"""
        Whether gzip compression is offered.
        """
    @property
    def gzip_level(self) -> int:
        r"""
        Gzip compression level.
        """
    def __new__(
        cls,
        *,
        enabled: bool | None = None,
        min_size: int | str | None = None,
        zstd: bool | None = None,
        zstd_level: int | None = None,
        brotli: bool | None = None,
        brotli_quality: int | None = None,
        gzip: bool | None = None,
        gzip_level: int | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ServerConfig:
    r"""
    Configuration for the engine's HTTP server.
    """
    @property
    def host(self) -> str:
        r"""
        Address the server binds to.
        """
    @property
    def port(self) -> int | None:
        r"""
        Port the server listens on, omit to disable the server.
        """
    @property
    def ssl(self) -> ServerSSLConfig | None:
        r"""
        TLS settings, omit to serve plain HTTP.
        """
    @property
    def authentication(self) -> ServerAuthenticationConfig | None:
        r"""
        Authentication settings, omit to disable authentication.
        """
    @property
    def cors(self) -> ServerCORSConfig | None:
        r"""
        Cross-origin resource sharing settings.
        """
    @property
    def compression(self) -> ServerCompressionConfig | None:
        r"""
        Response compression settings.
        """
    def __new__(
        cls,
        *,
        host: str | None = None,
        port: int | None = None,
        ssl: ServerSSLConfig | dict[str, Any] | None = None,
        authentication: ServerAuthenticationConfig | dict[str, Any] | None = None,
        cors: ServerCORSConfig | dict[str, Any] | None = None,
        compression: ServerCompressionConfig | dict[str, Any] | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ServerSSLConfig:
    r"""
    TLS configuration for the engine's HTTP server.
    """
    @property
    def key(self) -> Path | None:
        r"""
        Path to the server private key file.
        """
    @property
    def key_password(self) -> str | None:
        r"""
        Password for an encrypted private key.
        """
    @property
    def cert(self) -> Path | None:
        r"""
        Path to the server certificate file.
        """
    @property
    def version(self) -> int | None:
        r"""
        `ssl` protocol constant selecting the TLS version.
        """
    @property
    def ca_certs(self) -> Path | None:
        r"""
        Path to a CA bundle used when validating client certificates.
        """
    def __new__(
        cls,
        *,
        key: str | PathLike[str] | Path | None = None,
        key_password: str | None = None,
        cert: str | PathLike[str] | Path | None = None,
        version: int | None = None,
        ca_certs: str | PathLike[str] | Path | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ServiceConfig:
    r"""
    Process-level options applied when running the engine as a system service.
    """
    @property
    def name(self) -> str | None:
        r"""
        Service name registered with the operating system.
        """
    @property
    def user(self) -> str | None:
        r"""
        User the service runs as.
        """
    @property
    def stdout(self) -> Path | None:
        r"""
        Optional path to redirect standard output to.
        """
    @property
    def stderr(self) -> Path | None:
        r"""
        Optional path to redirect standard error to.
        """
    def __new__(
        cls,
        *,
        name: str | None = None,
        user: str | None = None,
        stdout: str | PathLike[str] | Path | None = None,
        stderr: str | PathLike[str] | Path | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

@final
class Store:
    r"""
    A natively-connected database the query layer reads and writes through.
    """
    @staticmethod
    def sqlite(path: str) -> Store:
        r"""
        Open a store over a SQLite database file.
        """
    @staticmethod
    def turso(path: str, mvcc: bool) -> Store:
        r"""
        Open a store over a Turso database file.
        """
    @staticmethod
    def postgres(
        host: str,
        database: str,
        user: str,
        port: int | None = None,
        password: str | None = None,
        settings: Sequence[tuple[str, str]] = [],
        parameters: Sequence[tuple[str, str]] = [],
    ) -> Store:
        r"""
        Open a store over a PostgreSQL database.
        """
    def fetch(self, sql: str, parameters: list[Any], table: str | None = None) -> Any:
        r"""
        Execute a statement that returns rows, as an awaitable list of column mappings.

        `table` names the table the rows come from, which is what says whether a column
        of text holds a UUID, a timestamp, or a name. A statement belonging to no table,
        which is what a migration runs, passes `None` and reads values as stored.
        """
    def stream(self, sql: str, parameters: list[Any], table: str | None = None) -> RowChunks:
        r"""
        Execute a statement that returns rows, as chunks read as they arrive.

        The chunked twin of `fetch`. A caller iterating a result rather than collecting it
        holds one chunk at a time, so a query over a large table costs a chunk of memory
        rather than the whole result, and the first rows reach the caller before the last
        ones have been read.
        """
    def execute(self, sql: str, parameters: list[Any]) -> Any:
        r"""
        Execute a statement that returns no rows, as an awaitable count of rows touched.
        """
    def execute_script(self, sql: str) -> Any:
        r"""
        Run a script of `;`-separated statements, as an awaitable.
        """

class TursoDatabaseConfig(SQLiteDatabaseConfig):
    r"""
    Configuration for a Turso-backed database, a SQLite-compatible file that allows
    concurrent writers.
    """
    @property
    def path(self) -> Path | None:
        r"""
        Path to the database file. Omit to use a temporary on-disk file.
        """
    @property
    def mvcc(self) -> bool:
        r"""
        Put the database in Turso's MVCC journal mode, which is what lets writers
        overlap. This converts the database file and the conversion cannot be undone.
        """
    @property
    def hooks(self) -> DatabaseConfigHooks:
        r"""
        SQL statements executed at well-known points in the database lifecycle.
        """
    @property
    def engine(self) -> dict[str, Any]:
        r"""
        Extra keyword arguments forwarded to the SQLAlchemy engine factory.
        """
    @property
    def hashing(self) -> BCryptHashingConfig | Argon2HashingConfig:
        r"""
        Password hashing configuration used for users stored in this database.
        """
    @property
    def query(self) -> dict[str, str | list[str]] | None:
        r"""
        Optional database-specific connection string query parameters.
        """
    @property
    def type(self) -> str:
        r"""
        The backend selector for this configuration.
        """
    def __new__(
        cls,
        *,
        path: str | PathLike[str] | Path | None = None,
        mvcc: bool | None = None,
        hooks: DatabaseConfigHooks | dict[str, Any] | None = None,
        engine: dict[str, Any] | None = None,
        hashing: BCryptHashingConfig | Argon2HashingConfig | dict[str, Any] | None = None,
        query: dict[str, str | list[str]] | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

@final
class EntityTable(Enum):
    r"""
    One of the non-record entity tables the entity commands manage.
    """

    USERS = ...
    VARIABLES = ...
    SETTINGS = ...
    WORKSPACES = ...
    WORKSPACEEDITS = ...
    GROUPS = ...
    GROUPMEMBERSHIPS = ...
    USERPERMISSIONS = ...
    GROUPPERMISSIONS = ...

@final
class RecordTable(Enum):
    r"""
    One of the record tables, the selector native record operations dispatch on.
    """

    MESSAGES = ...
    PARTICLES = ...
    ALERTS = ...
    LOGS = ...

def entity_filter_keys(table: EntityTable) -> tuple[list[str], list[str]]:
    r"""
    The native filter subset's key classification for one non-record entity table.

    Answers `(supported, delegated)` like the record classification, and the same test
    holds their union to exactly the fields the Python filter models declare.
    """

def hash_argon2(
    password: str,
    time_cost: int,
    memory_cost: int,
    parallelism: int,
    hash_length: int,
    salt_length: int,
) -> str | None:
    r"""
    Hash a password with the given Argon2id parameters, `None` when they are out of range.

    A value that already reads as a stored hash passes through, which is the user
    manager's own rule.

    This is the one Argon2 implementation the system has. The Python side calls it rather
    than carrying a second one, so a hash written by a native command and a hash written
    through the entity manager cannot drift apart.

    The interpreter lock is released for the duration. Argon2 is deliberately expensive,
    tens of milliseconds against the default memory cost, and holding the lock through it
    would stall every other Python thread, the event loop included.
    """

def hash_bcrypt(password: str, rounds: int) -> str | None:
    r"""
    Hash a password with bcrypt at the given cost, `None` when the cost is out of range.

    The other half of the one hashing implementation, for a database configured to use
    bcrypt rather than the default. Releases the interpreter lock like the Argon2 pair.
    """

def insert_compiled(
    table: str, dialect: str, values: str, upsert: bool = False
) -> tuple[str, list[Any]]:
    r"""
    Compile one row's insert to SQL and its parameters for a dialect.

    This takes a table rather than a filter, because an insert names the row it writes
    instead of narrowing to rows that already exist. `values` is the serialized JSON object
    of column values, and each one encodes into the form its column stores.

    `upsert` decides what a collision on the primary key does. Left off, the collision
    reaches the caller, which is what turns a duplicate into the error naming the column it
    collided on. Turned on, every column outside the key takes the new row's value.
    """

def normalize_email(value: str) -> str | None:
    r"""
    Normalize an email address the way a native user write stores it, `None` for one
    outside the subset the native path understands.

    Exposed so the parity suite can hold the native subset against `email_validator`
    itself, which is the direction that matters. An address this accepts and that library
    rejects would be a row written natively that Python would have refused.
    """

def openapi_schema(version: str) -> str:
    r"""
    Serve the OpenAPI document describing the API, as JSON text.
    """

def record_filter_keys(table: RecordTable) -> tuple[list[str], list[str]]:
    r"""
    The native filter subset's key classification for one record table.

    Answers `(supported, delegated)`, and the classification test holds their union to
    exactly the fields the Python filter models declare.
    """

def special_use_domains() -> list[str]:
    r"""
    The reserved domain names the native email subset refuses.

    Exposed so the parity suite can hold it against the validator library's own list. A
    name added there and not here would be an address written natively that Python
    refuses.
    """

def verify_argon2(password: str, hash: str) -> bool | None:
    r"""
    Whether a password matches a stored Argon2 hash, `None` for any other algorithm.

    The parameters come out of the encoded hash, so a stored one still verifies after the
    configuration's parameters change. Releases the interpreter lock like `hash_argon2`,
    and for the same reason, verifying costs what hashing costs.
    """

def verify_bcrypt(password: str, hash: str) -> bool | None:
    r"""
    Whether a password matches a stored bcrypt hash, `None` for any other algorithm.
    """

def verify_password(password: str, hash: str) -> bool:
    r"""
    Whether a password matches a stored hash of either algorithm.

    The algorithm is read off the hash itself rather than taken from a configuration,
    which is what lets a database keep verifying rows written before its hashing was
    changed. A value that reads as neither algorithm's hash matches nothing.
    """
