# This file is generated by ceres-stubs. Do not edit it directly.

from collections.abc import Sequence
from datetime import datetime, timedelta
from enum import Enum
from os import PathLike
from pathlib import Path
from typing import Any, Self, final

from pydantic import SecretStr

__all__ = [
    "Argon2HashingConfig",
    "BCryptHashingConfig",
    "ConsoleConfig",
    "DatabaseConfigHooks",
    "LoggingConfig",
    "NativeServer",
    "PackingProgram",
    "PostgresDatabaseConfig",
    "RecordBatch",
    "RecordFetcher",
    "RecordFilter",
    "RecordTable",
    "RecordWriter",
    "SQLiteDatabaseConfig",
    "ServerAuthenticationConfig",
    "ServerCORSConfig",
    "ServerCompressionConfig",
    "ServerConfig",
    "ServerSSLConfig",
    "ServiceConfig",
    "TursoDatabaseConfig",
    "openapi_schema",
    "parse_record_filter",
    "record_filter_from_json",
    "record_filter_keys",
]

class Argon2HashingConfig:
    r"""
    Configuration for the Argon2id password hashing algorithm.

    Default parameters mirror `argon2.profiles.RFC_9106_LOW_MEMORY`, callers can tune
    them to trade memory and CPU cost against latency.
    """
    @property
    def time_cost(self) -> int:
        r"""
        Number of iterations Argon2 performs.
        """
    @property
    def memory_cost(self) -> int:
        r"""
        Memory budget in KiB.
        """
    @property
    def parallelism(self) -> int:
        r"""
        Number of parallel lanes used during hashing.
        """
    @property
    def hash_length(self) -> int:
        r"""
        Length of the produced hash in bytes.
        """
    @property
    def salt_length(self) -> int:
        r"""
        Length of the random salt in bytes.
        """
    @property
    def type(self) -> str:
        r"""
        The algorithm selector for this configuration.
        """
    def __new__(
        cls,
        *,
        time_cost: int | None = None,
        memory_cost: int | None = None,
        parallelism: int | None = None,
        hash_length: int | None = None,
        salt_length: int | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class BCryptHashingConfig:
    r"""
    Configuration for the bcrypt password hashing algorithm.
    """
    @property
    def rounds(self) -> int:
        r"""
        Cost factor controlling how expensive each hash is to compute.
        """
    @property
    def type(self) -> str:
        r"""
        The algorithm selector for this configuration.
        """
    def __new__(cls, *, rounds: int | None = None) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ConsoleConfig:
    r"""
    Branding and layout options for the engine's web console.
    """
    @property
    def title(self) -> str | None:
        r"""
        Title shown in the console's browser tab and header.
        """
    @property
    def favicon(self) -> Path | None:
        r"""
        Path to a favicon image served by the console.
        """
    def __new__(
        cls, *, title: str | None = None, favicon: str | PathLike[str] | Path | None = None
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class DatabaseConfigHooks:
    r"""
    SQL statements executed at well-known points in the database lifecycle.
    """
    @property
    def init(self) -> list[str] | None:
        r"""
        Statements run once when the database is first created.
        """
    @property
    def connect(self) -> list[str] | None:
        r"""
        Statements run on every new connection.
        """
    @property
    def close(self) -> list[str] | None:
        r"""
        Statements run before a connection is closed.
        """
    def __new__(
        cls,
        *,
        init: Sequence[str] | None = None,
        connect: Sequence[str] | None = None,
        close: Sequence[str] | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class LoggingConfig:
    r"""
    Per-component or per-engine logging configuration.

    `output` and `store` set minimum levels for the streamed and persisted log streams, and
    the toggle fields enable optional logging of specific record types, accepting either a
    boolean or a minimum level.
    """
    @property
    def output(self) -> str:
        r"""
        Minimum severity that reaches the engine's streamed log output.
        """
    @property
    def store(self) -> str:
        r"""
        Minimum severity persisted to the engine's log store.
        """
    @property
    def events(self) -> bool | str:
        r"""
        Whether to log events, or the minimum severity to log them at.
        """
    @property
    def messages(self) -> bool | str:
        r"""
        Whether to log raw connection messages, or the minimum severity to log them at.
        """
    @property
    def particles(self) -> bool | str:
        r"""
        Whether to log parsed particles, or the minimum severity to log them at.
        """
    @property
    def alerts(self) -> bool | str:
        r"""
        Whether to log alerts, or the minimum severity to log them at.
        """
    def __new__(
        cls,
        *,
        output: str | None = None,
        store: str | None = None,
        events: bool | str | None = None,
        messages: bool | str | None = None,
        particles: bool | str | None = None,
        alerts: bool | str | None = None,
    ) -> Self: ...
    def merged(self, other: LoggingConfig) -> LoggingConfig:
        r"""
        Overlay another configuration's explicitly-set fields onto this one.
        """
    def provided(self) -> dict[str, Any]:
        r"""
        Return the explicitly-set fields as a plain dictionary.

        Supports rebuilding an equivalent configuration without turning resolved defaults
        into explicit settings.
        """
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

@final
class NativeServer:
    r"""
    A natively-served HTTP application.

    Binds at construction, so the real port is known immediately, and serves as an
    awaitable until stopped. The web form carries the console and terminates TLS, the
    CLI form binds loopback on an ephemeral port and requires its token instead.
    """
    @property
    def port(self) -> int:
        r"""
        The port the server actually bound.
        """
    @staticmethod
    def web(
        host: Any,
        config: ServerConfig,
        console_directory: str | PathLike[str] | Path,
        favicon_ico: str | PathLike[str] | Path,
        favicon_png: str | PathLike[str] | Path,
        favicon_svg: str | PathLike[str] | Path,
        records: RecordFetcher | None = None,
    ) -> NativeServer:
        r"""
        Bind the web application, serving the console and API on the configured address.
        """
    @staticmethod
    def cli(
        host: Any, config: ServerConfig, token: str, records: RecordFetcher | None = None
    ) -> NativeServer:
        r"""
        Bind the CLI control application on an ephemeral loopback port.
        """
    def serve(self) -> Any:
        r"""
        Serve until stopped, as an awaitable.
        """
    def stop(self, grace: float = 5.0) -> None:
        r"""
        Stop the server, letting in-flight requests finish within the grace period.
        """

@final
class PackingProgram:
    r"""
    A compiled binary packing program.

    Built by `ceres.data.binary` from a packing schema tree and executed natively, packing a
    whole value into one buffer and unpacking a whole buffer into one value tree per call.
    Models unpack to plain dictionaries, validation and model construction stay with the
    caller.
    """
    @property
    def size(self) -> int:
        r"""
        The packed size in bytes.
        """
    def __new__(cls, spec: dict[str, Any]) -> Self: ...
    def pack(self, value: Any, order: str | None = None) -> bytes:
        r"""
        Pack a value into its binary representation.
        """
    def unpack(self, data: bytes, offset: int = 0, order: str | None = None) -> Any:
        r"""
        Unpack a value tree from binary data.
        """

class PostgresDatabaseConfig:
    r"""
    Configuration for a PostgreSQL-backed database.
    """
    @property
    def host(self) -> str:
        r"""
        Host the database server listens on.
        """
    @property
    def port(self) -> int | None:
        r"""
        Port the database server listens on.
        """
    @property
    def database(self) -> str:
        r"""
        Name of the database to connect to.
        """
    @property
    def user(self) -> str:
        r"""
        User to authenticate as.
        """
    @property
    def password(self) -> str | None:
        r"""
        Password to authenticate with.
        """
    @property
    def hooks(self) -> DatabaseConfigHooks:
        r"""
        SQL statements executed at well-known points in the database lifecycle.
        """
    @property
    def engine(self) -> dict[str, Any]:
        r"""
        Extra keyword arguments forwarded to the SQLAlchemy engine factory.
        """
    @property
    def hashing(self) -> BCryptHashingConfig | Argon2HashingConfig:
        r"""
        Password hashing configuration used for users stored in this database.
        """
    @property
    def query(self) -> dict[str, str | list[str]] | None:
        r"""
        Optional database-specific connection string query parameters.
        """
    @property
    def type(self) -> str:
        r"""
        The backend selector for this configuration.
        """
    def __new__(
        cls,
        *,
        host: str | None = None,
        port: int | None = None,
        database: str | None = None,
        user: str | None = None,
        password: str | SecretStr | None = None,
        hooks: DatabaseConfigHooks | dict[str, Any] | None = None,
        engine: dict[str, Any] | None = None,
        hashing: BCryptHashingConfig | Argon2HashingConfig | dict[str, Any] | None = None,
        query: dict[str, str | list[str]] | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

@final
class RecordBatch:
    r"""
    A batch of records held natively, parsed from database rows.

    Built through `parse` from the raw row mappings a query produces, and serialized with
    `to_json` as the API's wire format for a record listing.
    """
    @staticmethod
    def parse(table: RecordTable, rows: Sequence[Any]) -> RecordBatch:
        r"""
        Parse database row mappings into a native batch.

        Row values arrive through the database layer's column mappers, so they are trusted
        rather than revalidated here.
        """
    def __len__(self) -> int: ...
    @staticmethod
    def record_to_json(table: RecordTable, record: Any) -> bytes:
        r"""
        Serialize one live record entity as JSON in the API's wire format.

        Reads the entity object's attributes rather than row values, so streamed records
        serialize natively too. Raises `ValueError` for payload values richer than JSON,
        which the caller serializes through Pydantic instead.
        """
    def to_json(self) -> bytes:
        r"""
        Serialize the batch as a JSON array in the API's wire format.
        """
    def to_json_lines(self) -> bytes:
        r"""
        Serialize the batch as JSON lines in the wire format, one record per line.

        The shape a CLI record dump writes, so a select can produce its whole output in
        one native pass.
        """
    def to_csv_lines(self) -> str:
        r"""
        Render the batch as CSV lines under a header row, in the wire cell forms.

        The shape a CSV record dump writes, quoted the way the Python `csv` writer
        quotes, so a select can produce its whole output in one native pass.
        """

@final
class RecordFetcher:
    r"""
    A natively-connected view of a Ceres database, serving record reads.

    Built from resolved connection parameters rather than a configuration, because the
    Python layer resolves per-instance details like temporary SQLite paths. Connections
    open lazily on first use.
    """
    @staticmethod
    def sqlite(path: str) -> RecordFetcher:
        r"""
        Open a fetcher over a SQLite database file.
        """
    @staticmethod
    def postgres(
        host: str,
        database: str,
        user: str,
        port: int | None = None,
        password: str | None = None,
        settings: Sequence[tuple[str, str]] = [],
    ) -> RecordFetcher:
        r"""
        Open a fetcher over a PostgreSQL database.

        `settings` are per-connection server settings like `search_path`, matching the ones
        the query layer passes its own driver.
        """
    def fetch_sql(self, table: RecordTable, sql: str, parameters: list[Any]) -> Any:
        r"""
        Execute a compiled record query, as an awaitable `RecordBatch`.

        The statement text and parameters come from the query layer's own compiler, so any
        filter it can express runs natively with identical semantics.
        """
    def fetch(self, table: RecordTable, limit: int | None = None, offset: int | None = None) -> Any:
        r"""
        Fetch a record listing ordered by timestamp, as an awaitable `RecordBatch`.
        """
    def fetch_pairs(self, table: RecordTable, pairs: Sequence[tuple[str, str]]) -> Any:
        r"""
        Fetch the records matching filter query pairs, as an awaitable `RecordBatch`.

        The pairs parse against the native filter subset, and a request outside it
        answers `None` synchronously so the caller delegates to the query layer.
        """
    def count_pairs(self, table: RecordTable, pairs: Sequence[tuple[str, str]]) -> Any:
        r"""
        Count the records matching filter query pairs, as an awaitable count.

        Like `fetch_pairs`, a request outside the native subset answers `None`
        synchronously so the caller delegates.
        """

@final
class RecordFilter:
    r"""
    A parsed record filter, held natively and reused across calls.
    """
    @property
    def limit(self) -> int | None:
        r"""
        The filter's limit, `None` when unbounded.
        """
    @property
    def offset(self) -> int | None:
        r"""
        The filter's offset, `None` when unset.
        """
    def where_sql(self, dialect: str, now: datetime | None = None) -> str | None:
        r"""
        The `WHERE` conditions as inline SQL for a dialect, `None` when the filter is
        unconditional.

        The text embeds into a statement the Python session builds, so values render
        as literals rather than binds.
        The caller's clock decides age-relative conditions, so a session under a faked
        or frozen time stays authoritative.
        """
    def order_sql(self, dialect: str) -> str | None:
        r"""
        The `ORDER BY` terms as inline SQL for a dialect, including the table's
        default ordering.
        """
    def compiled(self, dialect: str, *, count: bool = False) -> tuple[str, list[Any]]:
        r"""
        Compile to SQL and its parameters for a dialect, a listing statement or a
        count.

        The parameters arrive in placeholder order for a driver-level execute, `?`
        style for the SQLite family and `$n` for PostgreSQL.
        """
    def matches(self, record_json: str, now: datetime | None = None) -> bool:
        r"""
        Whether one serialized record matches this filter.

        Query controls and subsampling do not participate, this reads a single record
        the way live stream filtering does.
        """

@final
class RecordWriter:
    r"""
    A natively-connected writer for record entities.

    Entities extract into native records synchronously, then a whole flush upserts in one
    transaction on the writer's own pool. Built from resolved connection parameters like
    the fetcher, and matching the query layer's connection semantics.
    """
    @staticmethod
    def sqlite(path: str) -> RecordWriter:
        r"""
        Open a writer over a SQLite database file.
        """
    @staticmethod
    def postgres(
        host: str,
        database: str,
        user: str,
        port: int | None = None,
        password: str | None = None,
        settings: Sequence[tuple[str, str]] = [],
    ) -> RecordWriter:
        r"""
        Open a writer over a PostgreSQL database, with per-connection server settings.
        """
    def write(self, groups: list[tuple[RecordTable, list[Any]]]) -> Any:
        r"""
        Upsert groups of record entities atomically, as an awaitable.

        Each group pairs a record table name with the entities to write there. Raises
        `ValueError` when an entity cannot extract natively, before anything writes.
        """

class SQLiteDatabaseConfig:
    r"""
    Configuration for a SQLite-backed database, the default for local deployments.
    """
    @property
    def path(self) -> Path | None:
        r"""
        Path to the SQLite file. Omit to use a temporary on-disk file, or set to
        `:memory:` (see `in_memory`) for a private in-memory database.
        """
    @property
    def hooks(self) -> DatabaseConfigHooks:
        r"""
        SQL statements executed at well-known points in the database lifecycle.
        """
    @property
    def engine(self) -> dict[str, Any]:
        r"""
        Extra keyword arguments forwarded to the SQLAlchemy engine factory.
        """
    @property
    def hashing(self) -> BCryptHashingConfig | Argon2HashingConfig:
        r"""
        Password hashing configuration used for users stored in this database.
        """
    @property
    def query(self) -> dict[str, str | list[str]] | None:
        r"""
        Optional database-specific connection string query parameters.
        """
    @property
    def type(self) -> str:
        r"""
        The backend selector for this configuration.
        """
    @property
    def is_memory(self) -> bool:
        r"""
        Whether `path` is the special `:memory:` sentinel used by `in_memory`.
        """
    def __new__(
        cls,
        *,
        path: str | PathLike[str] | Path | None = None,
        hooks: DatabaseConfigHooks | dict[str, Any] | None = None,
        engine: dict[str, Any] | None = None,
        hashing: BCryptHashingConfig | Argon2HashingConfig | dict[str, Any] | None = None,
        query: dict[str, str | list[str]] | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    @classmethod
    def in_memory(cls) -> Self:
        r"""
        Build a config for a private in-memory database scoped to this process.

        The returned database exists only in memory for the lifetime of its engine, useful
        for tests and other short-lived, detached databases that should never touch disk.
        """

class ServerAuthenticationConfig:
    r"""
    Authentication settings for the engine's HTTP server.
    """
    @property
    def secret(self) -> str:
        r"""
        Secret used to sign and verify authentication tokens.
        """
    @property
    def duration(self) -> timedelta:
        r"""
        Lifetime of an issued authentication token.
        """
    @property
    def allow_impersonate(self) -> bool:
        r"""
        Whether an administrator may take on another user's identity without their password.
        """
    def __new__(
        cls,
        *,
        secret: str | None = None,
        duration: timedelta | int | float | str | None = None,
        allow_impersonate: bool | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ServerCORSConfig:
    r"""
    Cross-origin resource sharing settings for the engine's HTTP server.
    """
    @property
    def enabled(self) -> bool:
        r"""
        Whether cross-origin resource sharing is enabled.
        """
    @property
    def allow_origins(self) -> str | list[str]:
        r"""
        Origins allowed to make cross-origin requests.
        """
    @property
    def allow_origin_regex(self) -> str | None:
        r"""
        Pattern matching additional allowed origins.
        """
    @property
    def allow_methods(self) -> str | list[str]:
        r"""
        Methods allowed for cross-origin requests.
        """
    @property
    def allow_headers(self) -> str | list[str]:
        r"""
        Headers allowed in cross-origin requests.
        """
    @property
    def allow_credentials(self) -> bool:
        r"""
        Whether credentialed cross-origin requests are allowed.
        """
    @property
    def expose_headers(self) -> str | list[str]:
        r"""
        Headers exposed to cross-origin callers.
        """
    @property
    def max_age(self) -> int:
        r"""
        How long preflight responses may be cached, in seconds.
        """
    def __new__(
        cls,
        *,
        enabled: bool | None = None,
        allow_origins: str | list[str] | None = None,
        allow_origin_regex: str | None = None,
        allow_methods: str | list[str] | None = None,
        allow_headers: str | list[str] | None = None,
        allow_credentials: bool | None = None,
        expose_headers: str | list[str] | None = None,
        max_age: int | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ServerCompressionConfig:
    r"""
    Response compression settings for the engine's HTTP server.
    """
    @property
    def enabled(self) -> bool:
        r"""
        Whether response compression is enabled.
        """
    @property
    def min_size(self) -> int:
        r"""
        Minimum response size in bytes before compression is applied.
        """
    @property
    def zstd(self) -> bool:
        r"""
        Whether zstd compression is offered.
        """
    @property
    def zstd_level(self) -> int:
        r"""
        Zstd compression level.
        """
    @property
    def brotli(self) -> bool:
        r"""
        Whether brotli compression is offered.
        """
    @property
    def brotli_quality(self) -> int:
        r"""
        Brotli compression quality.
        """
    @property
    def gzip(self) -> bool:
        r"""
        Whether gzip compression is offered.
        """
    @property
    def gzip_level(self) -> int:
        r"""
        Gzip compression level.
        """
    def __new__(
        cls,
        *,
        enabled: bool | None = None,
        min_size: int | str | None = None,
        zstd: bool | None = None,
        zstd_level: int | None = None,
        brotli: bool | None = None,
        brotli_quality: int | None = None,
        gzip: bool | None = None,
        gzip_level: int | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ServerConfig:
    r"""
    Configuration for the engine's HTTP server.
    """
    @property
    def host(self) -> str:
        r"""
        Address the server binds to.
        """
    @property
    def port(self) -> int | None:
        r"""
        Port the server listens on, omit to disable the server.
        """
    @property
    def ssl(self) -> ServerSSLConfig | None:
        r"""
        TLS settings, omit to serve plain HTTP.
        """
    @property
    def authentication(self) -> ServerAuthenticationConfig | None:
        r"""
        Authentication settings, omit to disable authentication.
        """
    @property
    def cors(self) -> ServerCORSConfig | None:
        r"""
        Cross-origin resource sharing settings.
        """
    @property
    def compression(self) -> ServerCompressionConfig | None:
        r"""
        Response compression settings.
        """
    def __new__(
        cls,
        *,
        host: str | None = None,
        port: int | None = None,
        ssl: ServerSSLConfig | dict[str, Any] | None = None,
        authentication: ServerAuthenticationConfig | dict[str, Any] | None = None,
        cors: ServerCORSConfig | dict[str, Any] | None = None,
        compression: ServerCompressionConfig | dict[str, Any] | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ServerSSLConfig:
    r"""
    TLS configuration for the engine's HTTP server.
    """
    @property
    def key(self) -> Path | None:
        r"""
        Path to the server private key file.
        """
    @property
    def key_password(self) -> str | None:
        r"""
        Password for an encrypted private key.
        """
    @property
    def cert(self) -> Path | None:
        r"""
        Path to the server certificate file.
        """
    @property
    def version(self) -> int | None:
        r"""
        `ssl` protocol constant selecting the TLS version.
        """
    @property
    def ca_certs(self) -> Path | None:
        r"""
        Path to a CA bundle used when validating client certificates.
        """
    def __new__(
        cls,
        *,
        key: str | PathLike[str] | Path | None = None,
        key_password: str | None = None,
        cert: str | PathLike[str] | Path | None = None,
        version: int | None = None,
        ca_certs: str | PathLike[str] | Path | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class ServiceConfig:
    r"""
    Process-level options applied when running the engine as a system service.
    """
    @property
    def name(self) -> str | None:
        r"""
        Service name registered with the operating system.
        """
    @property
    def user(self) -> str | None:
        r"""
        User the service runs as.
        """
    @property
    def stdout(self) -> Path | None:
        r"""
        Optional path to redirect standard output to.
        """
    @property
    def stderr(self) -> Path | None:
        r"""
        Optional path to redirect standard error to.
        """
    def __new__(
        cls,
        *,
        name: str | None = None,
        user: str | None = None,
        stdout: str | PathLike[str] | Path | None = None,
        stderr: str | PathLike[str] | Path | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

class TursoDatabaseConfig(SQLiteDatabaseConfig):
    r"""
    Configuration for a Turso-backed database, a SQLite-compatible file that allows
    concurrent writers.
    """
    @property
    def path(self) -> Path | None:
        r"""
        Path to the database file. Omit to use a temporary on-disk file, or set to
        `:memory:` (see `in_memory`) for a private in-memory database.
        """
    @property
    def mvcc(self) -> bool:
        r"""
        Put the database in Turso's MVCC journal mode, which is what lets writers
        overlap. This converts the database file and the conversion cannot be undone.
        """
    @property
    def hooks(self) -> DatabaseConfigHooks:
        r"""
        SQL statements executed at well-known points in the database lifecycle.
        """
    @property
    def engine(self) -> dict[str, Any]:
        r"""
        Extra keyword arguments forwarded to the SQLAlchemy engine factory.
        """
    @property
    def hashing(self) -> BCryptHashingConfig | Argon2HashingConfig:
        r"""
        Password hashing configuration used for users stored in this database.
        """
    @property
    def query(self) -> dict[str, str | list[str]] | None:
        r"""
        Optional database-specific connection string query parameters.
        """
    @property
    def type(self) -> str:
        r"""
        The backend selector for this configuration.
        """
    @property
    def is_memory(self) -> bool:
        r"""
        Whether `path` is the special `:memory:` sentinel used by `in_memory`.
        """
    def __new__(
        cls,
        *,
        path: str | PathLike[str] | Path | None = None,
        mvcc: bool | None = None,
        hooks: DatabaseConfigHooks | dict[str, Any] | None = None,
        engine: dict[str, Any] | None = None,
        hashing: BCryptHashingConfig | Argon2HashingConfig | dict[str, Any] | None = None,
        query: dict[str, str | list[str]] | None = None,
    ) -> Self: ...
    def __to_dict__(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...

@final
class RecordTable(Enum):
    r"""
    One of the record tables, the selector native record operations dispatch on.
    """

    MESSAGES = ...
    PARTICLES = ...
    ALERTS = ...
    LOGS = ...

def openapi_schema(version: str) -> str:
    r"""
    Serve the OpenAPI document describing the API, as JSON text.
    """

def parse_record_filter(table: RecordTable, pairs: Sequence[tuple[str, str]]) -> RecordFilter:
    r"""
    Parse a record filter from ordered wire query pairs.
    """

def record_filter_from_json(table: RecordTable, json: str) -> RecordFilter:
    r"""
    Parse a record filter from its serialized JSON form, the filter model's dump.
    """

def record_filter_keys(table: RecordTable) -> tuple[list[str], list[str]]:
    r"""
    The native filter subset's key classification for one record table.

    Answers `(supported, delegated)`, and the classification test holds their union to
    exactly the fields the Python filter models declare.
    """
