# This file is generated by stub_gen. Do not edit it directly.

from os import PathLike
from pathlib import Path
from typing import Any, Self

__all__ = [
    "ConsoleConfig",
    "ServiceConfig",
]

class ConsoleConfig:
    r"""
    Branding and layout options for the engine's web console.
    """
    @property
    def title(self) -> str | None:
        r"""
        Title shown in the console's browser tab and header.
        """
    @property
    def favicon(self) -> Path | None:
        r"""
        Path to a favicon image served by the console.
        """
    def to_dict(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.
        """
    @staticmethod
    def json_schema() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __new__(
        cls, *, title: str | None = None, favicon: str | PathLike[str] | Path | None = None
    ) -> Self: ...

class ServiceConfig:
    r"""
    Process-level options applied when running the engine as a system service.
    """
    @property
    def name(self) -> str | None:
        r"""
        Service name registered with the operating system.
        """
    @property
    def user(self) -> str | None:
        r"""
        User the service runs as.
        """
    @property
    def stdout(self) -> Path | None:
        r"""
        Optional path to redirect standard output to.
        """
    @property
    def stderr(self) -> Path | None:
        r"""
        Optional path to redirect standard error to.
        """
    def to_dict(self) -> dict[str, Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.
        """
    @staticmethod
    def json_schema() -> dict[str, Any]:
        r"""
        Return the JSON Schema describing this configuration section.
        """
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __new__(
        cls,
        *,
        name: str | None = None,
        user: str | None = None,
        stdout: str | PathLike[str] | Path | None = None,
        stderr: str | PathLike[str] | Path | None = None,
    ) -> Self: ...
