// The polish pass rewriting generated stubs into the project's Python style.
//
// The generator's raw output qualifies every type with its module and spells unions as
// `typing.Optional`. Polishing rewrites the stubs into the style the rest of the project
// uses on Python 3.14, direct imports and `|` unions.

/// The typing constructs the polish pass rewrites, as (qualified form, replacement) pairs.
///
/// Raw-identifier method names leak into the generated stubs verbatim, so the `r#` prefix
/// keyword methods carry in Rust is stripped here. `typing.` prefixes are handled
/// generically rather than listed, every `typing.Name` becomes a direct import.
const REWRITES: [(&str, &str); 6] = [
    ("builtins.", ""),
    ("os.PathLike", "PathLike[str]"),
    ("pathlib.Path", "Path"),
    ("datetime.timedelta", "timedelta"),
    ("pydantic.SecretStr", "SecretStr"),
    ("def r#", "def "),
];

/// The imports the polished stub may need, as (name, import line) pairs.
///
/// These names can appear bare in the polished body, `Self` through the `__new__` rewrite
/// and the rest through `REWRITES`, so they are detected by use rather than collected while
/// stripping `typing.` prefixes.
const IMPORTS: [(&str, &str); 6] = [
    ("timedelta", "from datetime import timedelta"),
    ("PathLike", "from os import PathLike"),
    ("Path", "from pathlib import Path"),
    ("SecretStr", "from pydantic import SecretStr"),
    ("Any", "from typing import Any"),
    ("Self", "from typing import Self"),
];

/// Names `typing` re-exports whose home is `collections.abc`, imported from there instead.
const COLLECTIONS_ABC: [&str; 12] = [
    "AsyncIterable",
    "AsyncIterator",
    "Awaitable",
    "Callable",
    "Coroutine",
    "Generator",
    "Hashable",
    "Iterable",
    "Iterator",
    "Mapping",
    "MutableMapping",
    "Sequence",
];

/// Rewrite generated stubs into direct imports and modern union syntax.
pub fn polish(content: &str) -> String {
    let mut body = String::new();
    let mut stripped_names = std::collections::BTreeSet::new();
    let mut skipping_header = true;

    for line in content.lines() {
        // The header's module imports are replaced with direct imports computed from what the
        // polished body actually uses.
        if skipping_header {
            let trimmed = line.trim();
            if trimmed.is_empty()
                || trimmed.starts_with('#')
                || trimmed.starts_with("import ")
                || trimmed.starts_with("from ")
            {
                continue;
            }

            skipping_header = false;
        }

        let mut line = line.to_string();
        if line.trim_start().starts_with("def __new__")
            && let Some((head, _)) = line.rsplit_once(" -> ")
        {
            line = format!("{head} -> Self: ...");
        }

        line = flatten_optionals(&line);
        line = strip_typing_prefixes(&line, &mut stripped_names);
        for (qualified, replacement) in REWRITES {
            line = line.replace(qualified, replacement);
        }

        body.push_str(&line);
        body.push('\n');
    }

    // Names detected by use join the names collected while stripping, then each name
    // imports from its home module.
    let mut lines: Vec<String> = Vec::new();
    for (name, import) in IMPORTS {
        if !uses_name(&body, name) {
            continue;
        }

        if let Some(name) = import.strip_prefix("from typing import ") {
            stripped_names.insert(name.to_string());
        } else {
            lines.push(import.to_string());
        }
    }

    let (abc_names, typing_names): (Vec<_>, Vec<_>) = stripped_names
        .iter()
        .partition(|name| COLLECTIONS_ABC.contains(&name.as_str()));
    for (module, names) in [("collections.abc", abc_names), ("typing", typing_names)] {
        if !names.is_empty() {
            let names: Vec<&str> = names.iter().map(|name| name.as_str()).collect();
            lines.push(format!("from {module} import {}", names.join(", ")));
        }
    }

    lines.sort();
    format!(
        "# This file is generated by ceres-stubs. Do not edit it directly.\n\n{}\n\n{}",
        lines.join("\n"),
        body.trim_start_matches('\n')
    )
}

/// Rewrite every `typing.Name` in a line as a bare `Name`, collecting the stripped names.
fn strip_typing_prefixes(line: &str, names: &mut std::collections::BTreeSet<String>) -> String {
    const MARKER: &str = "typing.";

    let mut result = String::new();
    let mut remaining = line;
    while let Some(position) = remaining.find(MARKER) {
        let boundary = remaining[..position]
            .chars()
            .next_back()
            .is_none_or(|c| !c.is_alphanumeric() && c != '_' && c != '.');
        let after = &remaining[position + MARKER.len()..];
        let name: String = after
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect();

        if boundary && !name.is_empty() {
            result.push_str(&remaining[..position]);
            result.push_str(&name);
            names.insert(name.clone());
            remaining = &after[name.len()..];
        } else {
            result.push_str(&remaining[..position + MARKER.len()]);
            remaining = after;
        }
    }

    result.push_str(remaining);
    result
}

/// Rewrite every `typing.Optional[X]` in a line as `X | None`.
fn flatten_optionals(line: &str) -> String {
    const MARKER: &str = "typing.Optional[";

    let mut line = line.to_string();
    while let Some(start) = line.find(MARKER) {
        let inner_start = start + MARKER.len();
        let Some(inner_end) = matching_bracket(&line, inner_start) else {
            break;
        };

        let inner = &line[inner_start..inner_end];
        line = format!("{}{inner} | None{}", &line[..start], &line[inner_end + 1..]);
    }

    line
}

/// Return the index of the `]` closing the bracket opened just before `start`.
fn matching_bracket(text: &str, start: usize) -> Option<usize> {
    let mut depth = 1;
    for (offset, character) in text[start..].char_indices() {
        match character {
            '[' => depth += 1,
            ']' => {
                depth -= 1;
                if depth == 0 {
                    return Some(start + offset);
                }
            }
            _ => {}
        }
    }

    None
}

/// Return whether the body references a bare name outside of longer identifiers.
fn uses_name(body: &str, name: &str) -> bool {
    let mut remaining = body;
    while let Some(position) = remaining.find(name) {
        let before = remaining[..position].chars().next_back();
        let after = remaining[position + name.len()..].chars().next();
        let bounded = |character: Option<char>| {
            character.is_none_or(|c| !c.is_alphanumeric() && c != '_' && c != '.')
        };

        if bounded(before) && bounded(after) {
            return true;
        }

        remaining = &remaining[position + name.len()..];
    }

    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn optionals_flatten_to_unions() {
        assert_eq!(
            flatten_optionals("def f(x: typing.Optional[builtins.str] = None) -> None: ..."),
            "def f(x: builtins.str | None = None) -> None: ..."
        );
        assert_eq!(
            flatten_optionals("x: typing.Optional[dict[str, typing.Optional[int]]]"),
            "x: dict[str, int | None] | None"
        );
    }

    #[test]
    fn polish_rewrites_types_and_imports() {
        let raw = "\
# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing

class Example:
    @property
    def name(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, path: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None) -> Example: ...
";

        let polished = polish(raw);
        assert!(polished.contains("from os import PathLike"));
        assert!(polished.contains("from pathlib import Path"));
        assert!(polished.contains("from typing import Self"));
        assert!(polished.contains("def name(self) -> str | None: ..."));
        assert!(polished.contains("path: str | PathLike[str] | Path | None = None) -> Self: ..."));
        assert!(!polished.contains("import builtins"));
    }

    #[test]
    fn typing_prefixes_strip_and_import_from_their_home_modules() {
        let raw = "\
class Example:
    def f(self, x: typing.Sequence[str], y: typing.Literal[1]) -> typing.Any: ...
";

        let polished = polish(raw);
        assert!(polished.contains("from collections.abc import Sequence"));
        assert!(polished.contains("from typing import Any, Literal"));
        assert!(polished.contains("def f(self, x: Sequence[str], y: Literal[1]) -> Any: ..."));
    }
}
