// The polish pass rewriting generated stubs into the project's Python style.
//
// The generator's raw output qualifies every type with its module and spells unions as
// `typing.Optional`. Polishing rewrites the stubs into the style the rest of the project
// uses on Python 3.14, direct imports and `|` unions.

/// The typing constructs the polish pass rewrites, as (qualified form, replacement) pairs.
const REWRITES: [(&str, &str); 6] = [
    ("builtins.", ""),
    ("typing.Any", "Any"),
    ("typing.Self", "Self"),
    ("os.PathLike", "PathLike[str]"),
    ("pathlib.Path", "Path"),
    ("datetime.timedelta", "timedelta"),
];

/// The imports the polished stub may need, as (name, import line) pairs.
const IMPORTS: [(&str, &str); 5] = [
    ("timedelta", "from datetime import timedelta"),
    ("PathLike", "from os import PathLike"),
    ("Path", "from pathlib import Path"),
    ("Any", "from typing import Any"),
    ("Self", "from typing import Self"),
];

/// Rewrite generated stubs into direct imports and modern union syntax.
pub fn polish(content: &str) -> String {
    let mut body = String::new();
    let mut skipping_header = true;

    for line in content.lines() {
        // The header's module imports are replaced with direct imports computed from what the
        // polished body actually uses.
        if skipping_header {
            let trimmed = line.trim();
            if trimmed.is_empty()
                || trimmed.starts_with('#')
                || trimmed.starts_with("import ")
                || trimmed.starts_with("from ")
            {
                continue;
            }

            skipping_header = false;
        }

        let mut line = line.to_string();
        if line.trim_start().starts_with("def __new__")
            && let Some((head, _)) = line.rsplit_once(" -> ")
        {
            line = format!("{head} -> Self: ...");
        }

        line = flatten_optionals(&line);
        for (qualified, replacement) in REWRITES {
            line = line.replace(qualified, replacement);
        }

        body.push_str(&line);
        body.push('\n');
    }

    let imports: Vec<&str> = IMPORTS
        .iter()
        .filter(|(name, _)| uses_name(&body, name))
        .map(|(_, import)| *import)
        .collect();

    let mut typing_names: Vec<&str> = Vec::new();
    let mut lines: Vec<String> = Vec::new();
    for import in imports {
        if let Some(name) = import.strip_prefix("from typing import ") {
            typing_names.push(name);
        } else {
            lines.push(import.to_string());
        }
    }

    if !typing_names.is_empty() {
        lines.push(format!("from typing import {}", typing_names.join(", ")));
    }

    format!(
        "# This file is generated by ceres-stubs. Do not edit it directly.\n\n{}\n\n{}",
        lines.join("\n"),
        body.trim_start_matches('\n')
    )
}

/// Rewrite every `typing.Optional[X]` in a line as `X | None`.
fn flatten_optionals(line: &str) -> String {
    const MARKER: &str = "typing.Optional[";

    let mut line = line.to_string();
    while let Some(start) = line.find(MARKER) {
        let inner_start = start + MARKER.len();
        let Some(inner_end) = matching_bracket(&line, inner_start) else {
            break;
        };

        let inner = &line[inner_start..inner_end];
        line = format!("{}{inner} | None{}", &line[..start], &line[inner_end + 1..]);
    }

    line
}

/// Return the index of the `]` closing the bracket opened just before `start`.
fn matching_bracket(text: &str, start: usize) -> Option<usize> {
    let mut depth = 1;
    for (offset, character) in text[start..].char_indices() {
        match character {
            '[' => depth += 1,
            ']' => {
                depth -= 1;
                if depth == 0 {
                    return Some(start + offset);
                }
            }
            _ => {}
        }
    }

    None
}

/// Return whether the body references a bare name outside of longer identifiers.
fn uses_name(body: &str, name: &str) -> bool {
    let mut remaining = body;
    while let Some(position) = remaining.find(name) {
        let before = remaining[..position].chars().next_back();
        let after = remaining[position + name.len()..].chars().next();
        let bounded = |character: Option<char>| {
            character.is_none_or(|c| !c.is_alphanumeric() && c != '_' && c != '.')
        };

        if bounded(before) && bounded(after) {
            return true;
        }

        remaining = &remaining[position + name.len()..];
    }

    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn optionals_flatten_to_unions() {
        assert_eq!(
            flatten_optionals("def f(x: typing.Optional[builtins.str] = None) -> None: ..."),
            "def f(x: builtins.str | None = None) -> None: ..."
        );
        assert_eq!(
            flatten_optionals("x: typing.Optional[dict[str, typing.Optional[int]]]"),
            "x: dict[str, int | None] | None"
        );
    }

    #[test]
    fn polish_rewrites_types_and_imports() {
        let raw = "\
# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing

class Example:
    @property
    def name(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, path: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None) -> Example: ...
";

        let polished = polish(raw);
        assert!(polished.contains("from os import PathLike"));
        assert!(polished.contains("from pathlib import Path"));
        assert!(polished.contains("from typing import Self"));
        assert!(polished.contains("def name(self) -> str | None: ..."));
        assert!(polished.contains("path: str | PathLike[str] | Path | None = None) -> Self: ..."));
        assert!(!polished.contains("import builtins"));
    }
}
