//! Record queries and row decoding.

use ceres_entities::{
    Address, Alert, Level, LogEntry, Message, MessageDirection, Particle, Records, Timestamp,
};
use chrono::{DateTime, NaiveDateTime, Utc};
use sea_query::{Alias, Asterisk, Order, Query, SelectStatement};
use serde_json::{Map, Value};
use sqlx::Row;
use sqlx::postgres::PgRow;
use sqlx::sqlite::SqliteRow;
use uuid::Uuid;

use crate::store::Error;

/// One of the record tables.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RecordTable {
    Messages,
    Particles,
    Alerts,
    Logs,
}

impl RecordTable {
    /// Select a record table by name.
    pub fn parse(table: &str) -> Result<Self, Error> {
        match table {
            "messages" => Ok(Self::Messages),
            "particles" => Ok(Self::Particles),
            "alerts" => Ok(Self::Alerts),
            "logs" => Ok(Self::Logs),
            other => Err(Error::UnknownTable(other.to_string())),
        }
    }

    /// Every column the table stores, with the family that decides how it decodes.
    pub fn columns(&self) -> &'static [ceres_entities::FilterField] {
        self.schema().columns
    }

    /// The table's name, which is also the API route its records are served on.
    pub fn name(&self) -> &'static str {
        match self {
            Self::Messages => "messages",
            Self::Particles => "particles",
            Self::Alerts => "alerts",
            Self::Logs => "logs",
        }
    }

    /// The cap a listing route applies to this table's `limit`, which also fills in
    /// for an absent one. Held to the route layer's values by a parity test there.
    pub fn listing_cap(&self) -> u64 {
        match self {
            Self::Particles => 5000,
            Self::Messages | Self::Alerts | Self::Logs => 1000,
        }
    }

    /// The table's filterable fields, derived from its entity struct.
    pub(crate) fn fields(&self) -> &'static [ceres_entities::FilterField] {
        use ceres_entities::Filterable;

        match self {
            Self::Messages => Message::FIELDS,
            Self::Particles => Particle::FIELDS,
            Self::Alerts => Alert::FIELDS,
            Self::Logs => LogEntry::FIELDS,
        }
    }

    /// What the compiler needs to know about this table.
    ///
    /// Every record carries a single UUID key and sorts by timestamp, and a particle's
    /// `class` filters by a Python type, which has no native form.
    pub(crate) fn schema(&self) -> Schema {
        use ceres_entities::Filterable;

        Schema {
            name: self.name(),
            fields: self.fields(),
            columns: match self {
                Self::Messages => Message::COLUMNS,
                Self::Particles => Particle::COLUMNS,
                Self::Alerts => Alert::COLUMNS,
                Self::Logs => LogEntry::COLUMNS,
            },
            delegated: match self {
                Self::Particles => &["class"],
                _ => &[],
            },
            key: &["id"],
            fixed: &["id"],
            order: &["timestamp"],
            computed: &[],
        }
    }

    /// Build the listing statement, ordered like the Python layer's record default.
    pub(crate) fn listing(&self, limit: Option<u64>, offset: Option<u64>) -> SelectStatement {
        let mut statement = Query::select();
        statement
            .column(Asterisk)
            .from(Alias::new(self.name()))
            .order_by(Alias::new("timestamp"), Order::Asc);
        if let Some(limit) = limit {
            statement.limit(limit);
        }

        if let Some(offset) = offset {
            statement.offset(offset);
        }

        statement
    }

    pub(crate) fn empty(&self) -> Records {
        match self {
            Self::Messages => Records::Messages(Vec::new()),
            Self::Particles => Records::Particles(Vec::new()),
            Self::Alerts => Records::Alerts(Vec::new()),
            Self::Logs => Records::LogEntries(Vec::new()),
        }
    }
}

/// What the filter compiler needs to know about one queryable table.
///
/// The compiler is written against this rather than against a table enum, so the same
/// grammar serves the record tables and the entity tables without a second front end.
/// Every part of it derives from the entity struct, which keeps a new field from
/// reaching the wire without reaching the compiler.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Schema {
    /// The table's name in the database.
    pub name: &'static str,
    /// The filterable fields, generated by the entity's `Filterable` derive.
    pub fields: &'static [ceres_entities::FilterField],
    /// Every column the table stores, which is what a write encodes against.
    ///
    /// A column outside the filter surface is still writable, a setting's value being
    /// one the Python filter does not expose but the update model does.
    pub columns: &'static [ceres_entities::FilterField],
    /// The wire keys the compiler knowingly refuses, leaving them to Python.
    pub delegated: &'static [&'static str],
    /// The primary key columns, which a paged write narrows on.
    pub key: &'static [&'static str],
    /// The columns an update cannot assign, which its Python model leaves out.
    ///
    /// This is the entity's identity rather than its whole key. A variable's name is
    /// half its key and still assignable, its address is not.
    pub fixed: &'static [&'static str],
    /// The columns a filter naming no order sorts by, ascending.
    pub order: &'static [&'static str],
    /// Filter keys that match a shape of a column rather than its value.
    pub computed: &'static [Computed],
}

/// One filter key with no column of its own, matching a shape of one instead.
///
/// The Python filters spell these out per entity, and each takes a boolean that reads
/// as "hold this shape" when true and "hold its opposite" when false.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Computed {
    /// The wire key.
    pub key: &'static str,
    /// The column the shape is read from.
    pub column: &'static str,
    pub shape: Shape,
}

/// The shape a computed predicate matches.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Shape {
    /// A name both opening and closing with a double underscore, which is how an
    /// internal variable is named.
    Internal,
    /// A column holding one literal value, a workspace's scope being the engine's own
    /// address when it is placed on the engine.
    Literal(&'static str),
    /// A column holding anything at all, a workspace being owned when it names an
    /// owner.
    Present,
}

impl Schema {
    /// The table's filterable fields.
    pub(crate) fn fields(&self) -> &'static [ceres_entities::FilterField] {
        self.fields
    }

    /// The table's name in the database.
    pub(crate) fn name(&self) -> &'static str {
        self.name
    }
}

/// The table a batch of records belongs to.
pub(crate) fn table_of(records: &Records) -> RecordTable {
    match records {
        Records::Messages(_) => RecordTable::Messages,
        Records::Particles(_) => RecordTable::Particles,
        Records::Alerts(_) => RecordTable::Alerts,
        Records::LogEntries(_) => RecordTable::Logs,
    }
}

/// Decode rows for a record table into natively-held records.
pub(crate) trait DecodeRecords: Row + Sized {
    fn decode(table: RecordTable, rows: Vec<Self>) -> Result<Records, Error>;
}

impl DecodeRecords for SqliteRow {
    fn decode(table: RecordTable, rows: Vec<Self>) -> Result<Records, Error> {
        match table {
            RecordTable::Messages => rows
                .iter()
                .map(|row| {
                    Ok(Message {
                        id: sqlite_id(row)?,
                        address: Address::trusted(row.try_get("address")?),
                        timestamp: sqlite_timestamp(row)?,
                        connection: row.try_get("connection")?,
                        direction: direction(row.try_get("direction")?)?,
                        data: row.try_get("data")?,
                    })
                })
                .collect::<Result<_, Error>>()
                .map(Records::Messages),
            RecordTable::Particles => rows
                .iter()
                .map(|row| {
                    Ok(Particle {
                        id: sqlite_id(row)?,
                        address: Address::trusted(row.try_get("address")?),
                        timestamp: sqlite_timestamp(row)?,
                        kind: row.try_get("type")?,
                        data: json_text(row.try_get("data")?)?,
                        span: None,
                    })
                })
                .collect::<Result<_, Error>>()
                .map(Records::Particles),
            RecordTable::Alerts => rows
                .iter()
                .map(|row| {
                    Ok(Alert {
                        id: sqlite_id(row)?,
                        address: Address::trusted(row.try_get("address")?),
                        timestamp: sqlite_timestamp(row)?,
                        level: level(row.try_get("level")?)?,
                        kind: row.try_get("type")?,
                        data: json_text(row.try_get("data")?)?,
                    })
                })
                .collect::<Result<_, Error>>()
                .map(Records::Alerts),
            RecordTable::Logs => rows
                .iter()
                .map(|row| {
                    Ok(LogEntry {
                        id: sqlite_id(row)?,
                        address: Address::trusted(row.try_get("address")?),
                        timestamp: sqlite_timestamp(row)?,
                        level: level(row.try_get("level")?)?,
                        content: row.try_get("content")?,
                    })
                })
                .collect::<Result<_, Error>>()
                .map(Records::LogEntries),
        }
    }
}

impl DecodeRecords for PgRow {
    fn decode(table: RecordTable, rows: Vec<Self>) -> Result<Records, Error> {
        match table {
            RecordTable::Messages => rows
                .iter()
                .map(|row| {
                    Ok(Message {
                        id: row.try_get("id")?,
                        address: Address::trusted(row.try_get("address")?),
                        timestamp: postgres_timestamp(row)?,
                        connection: row.try_get("connection")?,
                        direction: direction(row.try_get("direction")?)?,
                        data: row.try_get("data")?,
                    })
                })
                .collect::<Result<_, Error>>()
                .map(Records::Messages),
            RecordTable::Particles => rows
                .iter()
                .map(|row| {
                    Ok(Particle {
                        id: row.try_get("id")?,
                        address: Address::trusted(row.try_get("address")?),
                        timestamp: postgres_timestamp(row)?,
                        kind: row.try_get("type")?,
                        data: json_value(row.try_get("data")?)?,
                        span: None,
                    })
                })
                .collect::<Result<_, Error>>()
                .map(Records::Particles),
            RecordTable::Alerts => rows
                .iter()
                .map(|row| {
                    Ok(Alert {
                        id: row.try_get("id")?,
                        address: Address::trusted(row.try_get("address")?),
                        timestamp: postgres_timestamp(row)?,
                        level: level(row.try_get("level")?)?,
                        kind: row.try_get("type")?,
                        data: json_value(row.try_get("data")?)?,
                    })
                })
                .collect::<Result<_, Error>>()
                .map(Records::Alerts),
            RecordTable::Logs => rows
                .iter()
                .map(|row| {
                    Ok(LogEntry {
                        id: row.try_get("id")?,
                        address: Address::trusted(row.try_get("address")?),
                        timestamp: postgres_timestamp(row)?,
                        level: level(row.try_get("level")?)?,
                        content: row.try_get("content")?,
                    })
                })
                .collect::<Result<_, Error>>()
                .map(Records::LogEntries),
        }
    }
}

/// Decode a SQLite ID column, stored as hyphenated UUID text.
fn sqlite_id(row: &SqliteRow) -> Result<Uuid, Error> {
    let text: String = row.try_get("id")?;
    text.parse()
        .map_err(|_| Error::Decode(format!("{text:?} is not a UUID")))
}

/// Decode a SQLite timestamp column, stored as naive UTC text.
fn sqlite_timestamp(row: &SqliteRow) -> Result<Timestamp, Error> {
    let naive: NaiveDateTime = row.try_get("timestamp")?;
    Ok(Timestamp(naive.and_utc()))
}

/// Decode a Postgres timestamp column, stored as a naive UTC timestamp.
fn postgres_timestamp(row: &PgRow) -> Result<Timestamp, Error> {
    if let Ok(aware) = row.try_get::<DateTime<Utc>, _>("timestamp") {
        return Ok(Timestamp(aware));
    }

    let naive: NaiveDateTime = row.try_get("timestamp")?;
    Ok(Timestamp(naive.and_utc()))
}

pub(crate) fn direction(text: String) -> Result<MessageDirection, Error> {
    match text.as_str() {
        "send" => Ok(MessageDirection::Send),
        "receive" => Ok(MessageDirection::Receive),
        other => Err(Error::Decode(format!(
            "{other:?} is not a message direction"
        ))),
    }
}

pub(crate) fn level(text: String) -> Result<Level, Error> {
    Level::parse(&text).map_err(Error::Decode)
}

/// Decode a JSON column stored as text.
pub(crate) fn json_text(text: String) -> Result<Map<String, Value>, Error> {
    serde_json::from_str(&text).map_err(|error| Error::Decode(error.to_string()))
}

/// Decode a JSON column delivered as a value.
fn json_value(value: Value) -> Result<Map<String, Value>, Error> {
    match value {
        Value::Object(map) => Ok(map),
        other => Err(Error::Decode(format!("{other} is not a JSON object"))),
    }
}
