//! Record queries and row decoding.

use ceres_entities::{
    Address, Alert, Level, LogEntry, Message, MessageDirection, Particle, Records, Timestamp,
};
use chrono::{DateTime, NaiveDateTime, Utc};
use sea_query::{Alias, Asterisk, Order, Query, SelectStatement};
use serde_json::{Map, Value};
use sqlx::Row;
use sqlx::postgres::PgRow;
use sqlx::sqlite::SqliteRow;
use uuid::Uuid;

use crate::store::Error;

/// One of the record tables.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RecordTable {
    Messages,
    Particles,
    Alerts,
    Logs,
}

impl RecordTable {
    /// Select a record table by name.
    pub fn parse(table: &str) -> Result<Self, Error> {
        match table {
            "messages" => Ok(Self::Messages),
            "particles" => Ok(Self::Particles),
            "alerts" => Ok(Self::Alerts),
            "logs" => Ok(Self::Logs),
            other => Err(Error::UnknownTable(other.to_string())),
        }
    }

    /// Every column the table stores, with the family that decides how it decodes.
    pub fn columns(&self) -> &'static [ceres_entities::FilterField] {
        self.schema().columns
    }

    /// The table's name, which is also the API route its records are served on.
    pub fn name(&self) -> &'static str {
        match self {
            Self::Messages => "messages",
            Self::Particles => "particles",
            Self::Alerts => "alerts",
            Self::Logs => "logs",
        }
    }

    /// The cap a listing route applies to this table's `limit`, which also fills in
    /// for an absent one. Held to the route layer's values by a parity test there.
    pub fn listing_cap(&self) -> u64 {
        match self {
            Self::Particles => 5000,
            Self::Messages | Self::Alerts | Self::Logs => 1000,
        }
    }

    /// The table's filterable fields, derived from its entity struct.
    pub(crate) fn fields(&self) -> &'static [ceres_entities::FilterField] {
        use ceres_entities::Filterable;

        match self {
            Self::Messages => Message::FIELDS,
            Self::Particles => Particle::FIELDS,
            Self::Alerts => Alert::FIELDS,
            Self::Logs => LogEntry::FIELDS,
        }
    }

    /// What the compiler needs to know about this table.
    ///
    /// Every record carries a single UUID key and sorts by timestamp, and a particle's
    /// `class` filters by a Python type, which has no native form.
    pub(crate) fn schema(&self) -> Schema {
        use ceres_entities::Filterable;

        Schema {
            name: self.name(),
            fields: self.fields(),
            columns: match self {
                Self::Messages => Message::COLUMNS,
                Self::Particles => Particle::COLUMNS,
                Self::Alerts => Alert::COLUMNS,
                Self::Logs => LogEntry::COLUMNS,
            },
            delegated: match self {
                Self::Particles => &["class"],
                _ => &[],
            },
            key: &["id"],
            fixed: &["id"],
            order: &["timestamp"],
            computed: &[],
        }
    }

    /// Build the listing statement, ordered like the Python layer's record default.
    pub(crate) fn listing(&self, limit: Option<u64>, offset: Option<u64>) -> SelectStatement {
        let mut statement = Query::select();
        statement
            .column(Asterisk)
            .from(Alias::new(self.name()))
            .order_by(Alias::new("timestamp"), Order::Asc);
        if let Some(limit) = limit {
            statement.limit(limit);
        }

        if let Some(offset) = offset {
            statement.offset(offset);
        }

        statement
    }

    pub(crate) fn empty(&self) -> Records {
        match self {
            Self::Messages => Records::Messages(Vec::new()),
            Self::Particles => Records::Particles(Vec::new()),
            Self::Alerts => Records::Alerts(Vec::new()),
            Self::Logs => Records::LogEntries(Vec::new()),
        }
    }
}

/// What the filter compiler needs to know about one queryable table.
///
/// The compiler is written against this rather than against a table enum so the same
/// grammar serves the record tables and the entity tables without a second front end.
/// Every part of it derives from the entity struct, which keeps a new field from
/// reaching the wire without reaching the compiler.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Schema {
    /// The table's name in the database.
    pub name: &'static str,
    /// The filterable fields, generated by the entity's `Filterable` derive.
    pub fields: &'static [ceres_entities::FilterField],
    /// Every column the table stores, which a write encodes against.
    ///
    /// A column outside the filter surface is still writable, a setting's value being
    /// one the Python filter does not expose but the update model does.
    pub columns: &'static [ceres_entities::FilterField],
    /// The wire keys the compiler knowingly refuses, leaving them to Python.
    pub delegated: &'static [&'static str],
    /// The primary key columns, which a paged write narrows on.
    pub key: &'static [&'static str],
    /// The columns an update cannot set, which its Python model leaves out.
    ///
    /// This is the entity's identity rather than its whole key. A variable's name is
    /// half its key and still settable, its address is not.
    pub fixed: &'static [&'static str],
    /// The columns a filter naming no order sorts by, ascending.
    pub order: &'static [&'static str],
    /// Filter keys that match a shape of a column rather than its value.
    pub computed: &'static [Computed],
}

/// One filter key with no column of its own, matching a shape of one instead.
///
/// The Python filters spell these out per entity, and each takes a boolean that reads
/// as "hold this shape" when true and "hold its opposite" when false.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Computed {
    /// The wire key.
    pub key: &'static str,
    /// The column the shape is read from.
    pub column: &'static str,
    pub shape: Shape,
}

/// The shape a computed predicate matches.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Shape {
    /// A name both opening and closing with a double underscore, which is how an
    /// internal variable is named.
    Internal,
    /// A column holding one literal value, a workspace's scope being the engine's own
    /// address when it is placed on the engine.
    Literal(&'static str),
    /// A column holding anything at all, a workspace being owned when it names an
    /// owner.
    Present,
}

/// The table a batch of records belongs to.
pub(crate) fn table_of(records: &Records) -> RecordTable {
    match records {
        Records::Messages(_) => RecordTable::Messages,
        Records::Particles(_) => RecordTable::Particles,
        Records::Alerts(_) => RecordTable::Alerts,
        Records::LogEntries(_) => RecordTable::Logs,
    }
}

/// Read one row's fields by column name, in the forms this backend stores them.
///
/// This is the per-backend seam of row decoding. Each table's field mapping is written
/// once against these accessors, and the three row types implement them over their own
/// stored forms, text-held UUIDs and timestamps on the SQLite family against native
/// values on Postgres.
pub(crate) trait FieldRead {
    fn text(&self, column: &str) -> Result<String, Error>;

    fn optional_text(&self, column: &str) -> Result<Option<String>, Error>;

    fn uuid(&self, column: &str) -> Result<Uuid, Error>;

    fn optional_uuid(&self, column: &str) -> Result<Option<Uuid>, Error>;

    fn timestamp(&self, column: &str) -> Result<Timestamp, Error>;

    fn boolean(&self, column: &str) -> Result<bool, Error>;

    fn blob(&self, column: &str) -> Result<Vec<u8>, Error>;

    /// A column holding arbitrary JSON, which a variable's or a setting's value does.
    fn json(&self, column: &str) -> Result<Value, Error>;

    /// A JSON object column a record's data lands in, stored as the writer's
    /// serialized text on the SQLite family.
    fn json_object(&self, column: &str) -> Result<Map<String, Value>, Error>;

    /// A JSON object column an entity's data lands in, naming `what` was expected when
    /// the value is not an object.
    ///
    /// This differs from [`FieldRead::json_object`] only on Turso, where an entity's
    /// data column may sit in any storage class and the refusal names the entity.
    fn object(&self, column: &str, what: &str) -> Result<Map<String, Value>, Error> {
        let _ = what;
        self.json_object(column)
    }
}

/// Decode one table row into its entity, reading fields through [`FieldRead`].
pub(crate) trait FromRow: Sized {
    fn from_row<R: FieldRead>(row: &R) -> Result<Self, Error>;
}

impl FromRow for Message {
    fn from_row<R: FieldRead>(row: &R) -> Result<Self, Error> {
        Ok(Message {
            id: row.uuid("id")?,
            address: Address::trusted(row.text("address")?),
            timestamp: row.timestamp("timestamp")?,
            connection: row.optional_text("connection")?,
            direction: direction(row.text("direction")?)?,
            data: row.blob("data")?,
        })
    }
}

impl FromRow for Particle {
    fn from_row<R: FieldRead>(row: &R) -> Result<Self, Error> {
        Ok(Particle {
            id: row.uuid("id")?,
            address: Address::trusted(row.text("address")?),
            timestamp: row.timestamp("timestamp")?,
            kind: row.text("type")?,
            data: row.json_object("data")?,
            span: None,
        })
    }
}

impl FromRow for Alert {
    fn from_row<R: FieldRead>(row: &R) -> Result<Self, Error> {
        Ok(Alert {
            id: row.uuid("id")?,
            address: Address::trusted(row.text("address")?),
            timestamp: row.timestamp("timestamp")?,
            level: level(row.text("level")?)?,
            kind: row.text("type")?,
            data: row.json_object("data")?,
        })
    }
}

impl FromRow for LogEntry {
    fn from_row<R: FieldRead>(row: &R) -> Result<Self, Error> {
        Ok(LogEntry {
            id: row.uuid("id")?,
            address: Address::trusted(row.text("address")?),
            timestamp: row.timestamp("timestamp")?,
            level: level(row.text("level")?)?,
            content: row.text("content")?,
        })
    }
}

/// Decode a fetched result set for a record table into natively-held records.
pub(crate) fn decode<R: FieldRead>(table: RecordTable, rows: Vec<R>) -> Result<Records, Error> {
    match table {
        RecordTable::Messages => decoded(&rows).map(Records::Messages),
        RecordTable::Particles => decoded(&rows).map(Records::Particles),
        RecordTable::Alerts => decoded(&rows).map(Records::Alerts),
        RecordTable::Logs => decoded(&rows).map(Records::LogEntries),
    }
}

/// Decode every row of one fetched result set.
pub(crate) fn decoded<T: FromRow, R: FieldRead>(rows: &[R]) -> Result<Vec<T>, Error> {
    rows.iter().map(T::from_row).collect()
}

impl FieldRead for SqliteRow {
    fn text(&self, column: &str) -> Result<String, Error> {
        Ok(self.try_get(column)?)
    }

    fn optional_text(&self, column: &str) -> Result<Option<String>, Error> {
        Ok(self.try_get(column)?)
    }

    /// Decode an ID column, stored as hyphenated UUID text.
    fn uuid(&self, column: &str) -> Result<Uuid, Error> {
        let text: String = self.try_get(column)?;
        text.parse()
            .map_err(|_| Error::Decode(format!("{text:?} is not a UUID")))
    }

    fn optional_uuid(&self, column: &str) -> Result<Option<Uuid>, Error> {
        let Some(text) = self.try_get::<Option<String>, _>(column)? else {
            return Ok(None);
        };

        text.parse()
            .map(Some)
            .map_err(|_| Error::Decode(format!("{text:?} is not a UUID")))
    }

    /// Decode a timestamp column, stored as naive UTC text.
    fn timestamp(&self, column: &str) -> Result<Timestamp, Error> {
        let naive: NaiveDateTime = self.try_get(column)?;
        Ok(Timestamp(naive.and_utc()))
    }

    fn boolean(&self, column: &str) -> Result<bool, Error> {
        Ok(self.try_get(column)?)
    }

    fn blob(&self, column: &str) -> Result<Vec<u8>, Error> {
        Ok(self.try_get(column)?)
    }

    /// Decode a value column, which holds arbitrary JSON.
    ///
    /// The column is declared `JSON`, which carries none of SQLite's affinity keywords
    /// and therefore takes NUMERIC affinity. The driver writes the JSON text, and the
    /// backend converts whatever looks like a number back into one so a variable
    /// holding `5` is stored as an integer while one holding `true` stays text. Both
    /// decode here.
    fn json(&self, column: &str) -> Result<Value, Error> {
        let text = match self.try_get::<String, _>(column) {
            Ok(text) => text,
            Err(_) => match self.try_get::<Option<i64>, _>(column) {
                Ok(Some(number)) => return Ok(number.into()),
                // A null column is a null value, which a variable may hold.
                Ok(None) => return Ok(Value::Null),
                Err(_) => {
                    let number: f64 = self.try_get(column)?;
                    return serde_json::Number::from_f64(number)
                        .map(Value::Number)
                        .ok_or_else(|| Error::Decode(format!("{number} is not a JSON number")));
                }
            },
        };

        serde_json::from_str(&text).map_err(|error| Error::Decode(error.to_string()))
    }

    fn json_object(&self, column: &str) -> Result<Map<String, Value>, Error> {
        json_text(self.try_get(column)?)
    }
}

impl FieldRead for PgRow {
    fn text(&self, column: &str) -> Result<String, Error> {
        Ok(self.try_get(column)?)
    }

    fn optional_text(&self, column: &str) -> Result<Option<String>, Error> {
        Ok(self.try_get(column)?)
    }

    fn uuid(&self, column: &str) -> Result<Uuid, Error> {
        Ok(self.try_get(column)?)
    }

    fn optional_uuid(&self, column: &str) -> Result<Option<Uuid>, Error> {
        Ok(self.try_get(column)?)
    }

    /// Decode a timestamp column, stored as a naive UTC timestamp.
    fn timestamp(&self, column: &str) -> Result<Timestamp, Error> {
        if let Ok(aware) = self.try_get::<DateTime<Utc>, _>(column) {
            return Ok(Timestamp(aware));
        }

        let naive: NaiveDateTime = self.try_get(column)?;
        Ok(Timestamp(naive.and_utc()))
    }

    fn boolean(&self, column: &str) -> Result<bool, Error> {
        Ok(self.try_get(column)?)
    }

    fn blob(&self, column: &str) -> Result<Vec<u8>, Error> {
        Ok(self.try_get(column)?)
    }

    fn json(&self, column: &str) -> Result<Value, Error> {
        Ok(self.try_get(column)?)
    }

    fn json_object(&self, column: &str) -> Result<Map<String, Value>, Error> {
        json_value(self.try_get(column)?)
    }
}

pub(crate) fn direction(text: String) -> Result<MessageDirection, Error> {
    match text.as_str() {
        "send" => Ok(MessageDirection::Send),
        "receive" => Ok(MessageDirection::Receive),
        other => Err(Error::Decode(format!(
            "{other:?} is not a message direction"
        ))),
    }
}

pub(crate) fn level(text: String) -> Result<Level, Error> {
    Level::parse(&text).map_err(Error::Decode)
}

/// Decode a JSON column stored as text.
pub(crate) fn json_text(text: String) -> Result<Map<String, Value>, Error> {
    serde_json::from_str(&text).map_err(|error| Error::Decode(error.to_string()))
}

/// Decode a JSON column delivered as a value.
fn json_value(value: Value) -> Result<Map<String, Value>, Error> {
    match value {
        Value::Object(map) => Ok(map),
        other => Err(Error::Decode(format!("{other} is not a JSON object"))),
    }
}
