// The sole gateway to Nuxt UI. Application code imports C-prefixed components from
// here and never names a U* component so restyling or replacing a primitive is a
// one-file change and this index is the inventory of what the console uses.
export { default as CApp } from '@nuxt/ui/components/App.vue'
export { default as CBadge } from '@nuxt/ui/components/Badge.vue'
export { default as CButton } from '@nuxt/ui/components/Button.vue'
export { default as CCard } from '@nuxt/ui/components/Card.vue'
export { default as CCheckbox } from '@nuxt/ui/components/Checkbox.vue'
export { default as CForm } from '@nuxt/ui/components/Form.vue'
export { default as CFormField } from '@nuxt/ui/components/FormField.vue'
export { default as CIcon } from '@nuxt/ui/components/Icon.vue'
export { default as CInput } from '@nuxt/ui/components/Input.vue'
export { default as CMenu } from '@nuxt/ui/components/DropdownMenu.vue'
export { default as CModal } from '@nuxt/ui/components/Modal.vue'
export { default as CPopover } from '@nuxt/ui/components/Popover.vue'
export { default as CSelect } from '@nuxt/ui/components/Select.vue'
export { default as CSelectMenu } from '@nuxt/ui/components/SelectMenu.vue'
export { default as CSwitch } from '@nuxt/ui/components/Switch.vue'
export { default as CTable } from '@nuxt/ui/components/Table.vue'
export { default as CTabs } from '@nuxt/ui/components/Tabs.vue'
export { default as CTooltip } from '@nuxt/ui/components/Tooltip.vue'
