#!/usr/bin/env uv run

"""Generate the reference pages in `docs/reference/` from the code they describe.

Every page here is a pure function of the source, so it is rendered and compared rather
than fingerprinted. `--check` fails when a page no longer matches what the code says,
which is the whole point: a surface cannot change without the page changing with it.

The CLI page is rendered from two halves. `reference` in `rust/ceres-cli/src/` dumps the
native command tree, which only a build of that crate can see because the table commands
are assembled at startup from the entity definitions, and this script joins it to the
arguments of the commands that run in the Python runtime. Run `make reference`, which
orders the two.
"""

import ast
import inspect
import json
import re
import sys
import types
from collections.abc import Callable
from importlib import import_module
from pathlib import Path
from typing import Annotated, Any, Union, get_args, get_origin

# ruff: disable[T201] # Allow print statements.

REFERENCE = Path("docs/reference")
"""Where the generated pages live, one directory so the whole set is obvious."""

BANNER = "<!-- @generated by scripts/update-reference.py. Run 'make reference' to update. -->"
"""Marks a page as generated, in a comment so it does not render."""

_SECTIONS: list[tuple[str, tuple[str, ...]]] = [
    ("Components", ("ceres.component", "ceres.engine", "ceres.loaded", "ceres.schedule")),
    ("Connections", ("ceres.connection", "ceres.connectivity", "ceres.server", "ceres.channel")),
    ("Particles", ("ceres.particle", "ceres.record")),
    ("Addressing", ("ceres.address", "ceres.reference", "ceres.directory")),
    (
        "Data",
        (
            "ceres.data",
            "ceres.entity",
            "ceres.item",
            "ceres.variable",
            "ceres.setting",
            "ceres.statistics",
        ),
    ),
    (
        "Events",
        (
            "ceres.event",
            "ceres.message",
            "ceres.alert",
            "ceres.logs",
            "ceres.notifier",
            "ceres.dispatcher",
            "ceres.level",
            "ceres.status",
            "ceres.sieves",
        ),
    ),
    ("Access Control", ("ceres.user", "ceres.group", "ceres.permission", "ceres.workspace")),
    ("Database", ("ceres.database",)),
    ("Configuration", ("ceres.config",)),
    ("Concurrency", ("ceres.concurrency",)),
    ("Utilities", ("ceres.timing", "ceres.version")),
]
"""Which page section each exporting module's names are documented under.

Curated rather than derived, because grouping by module alone would produce a section per
module and bury the handful a reader actually starts from. A module missing from here
fails the generator, so adding an export forces the choice of where it is documented.
"""


def _exports() -> dict[str, list[str]]:
    """Map each module to the names `ceres/__init__.py` re-exports from it.

    Read from the import statements rather than from the imported objects, because a type
    alias reports `typing` as its module and would lose the place it is defined.
    """
    tree = ast.parse(Path("ceres/__init__.py").read_text())
    found: dict[str, list[str]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom) or node.module is None:
            continue

        if node.module == "ceres.__internal__.lazy":
            continue

        found.setdefault(node.module, []).extend(alias.name for alias in node.names)

    return found


def _display(annotation: Any) -> str:
    """Name one member of a type alias the way a reader would write it."""
    name = getattr(annotation, "__name__", None)
    return name if isinstance(name, str) else str(annotation).replace("ceres.", "")


def _members(annotation: Any) -> list[str]:
    """Name what a type alias resolves to, through alias and annotation wrappers."""
    annotation = getattr(annotation, "__value__", annotation)
    origin = get_origin(annotation)
    if origin is Annotated:
        return _members(get_args(annotation)[0])

    if origin in (Union, types.UnionType):
        return [_display(argument) for argument in get_args(annotation)]

    return [_display(annotation)]


def _assigned(statement: ast.stmt) -> str | None:
    """Return the name a module-level statement binds, for the three alias spellings."""
    match statement:
        case ast.TypeAlias(name=ast.Name(id=name)):
            return name
        case ast.AnnAssign(target=ast.Name(id=name)):
            return name
        case ast.Assign(targets=[ast.Name(id=name)]):
            return name
        case _:
            return None


def _alias_docstring(module: str, name: str) -> str:
    """Return the docstring written under a type alias, which the runtime does not keep."""
    source = inspect.getsourcefile(import_module(module))
    if source is None:
        return ""

    body = ast.parse(Path(source).read_text()).body
    for statement, following in zip(body, body[1:], strict=False):
        if _assigned(statement) != name or not isinstance(following, ast.Expr):
            continue

        if isinstance(following.value, ast.Constant) and isinstance(following.value.value, str):
            return " ".join(following.value.value.split())

    return ""


def _documented(module: str, name: str) -> Any:
    """Return the object a name refers to in the module that defines it.

    Read from the defining module rather than from `ceres`, because importing a submodule
    binds it on the package and shadows any export sharing its name.
    """
    return getattr(import_module(module), name)


def render_python_api() -> str:
    """Render a mkdocstrings block for every name `ceres` exports."""
    exports = _exports()
    unassigned = sorted(set(exports) - {module for _, modules in _SECTIONS for module in modules})
    if unassigned:
        raise RuntimeError(f"{unassigned} export names but no section documents them")

    lines = [
        BANNER,
        "",
        "# Python API",
        "",
        "Every name `ceres` exports, grouped by what it is for. Each is importable straight",
        "from the package, `from ceres import Component`.",
    ]
    aliases: list[tuple[str, str, Any]] = []
    for title, modules in _SECTIONS:
        blocks: list[str] = []
        for module in modules:
            for name in sorted(exports.get(module, [])):
                documented = _documented(module, name)
                if inspect.isclass(documented) or inspect.isroutine(documented):
                    blocks += [f"::: {module}.{name}", "    options:", "      heading_level: 3", ""]
                elif name != "__version__":
                    aliases.append((name, module, documented))

        if blocks:
            lines += ["", f"## {title}", "", *blocks]

    lines += [
        "",
        "## Type Aliases",
        "",
        "Each accepts any one of the types listed under it.",
    ]
    for name, module, alias in sorted(aliases):
        described = _alias_docstring(module, name)
        accepts = ", ".join(f"`{member}`" for member in _members(alias))
        lines += ["", f"### `{name}`", ""]
        if described:
            lines += [described, ""]

        lines.append(accepts)

    lines += ["", "`ceres.__version__` holds the installed version as a string."]

    return "\n".join(lines).rstrip() + "\n"


def _section_types(annotation: Any) -> list[type]:
    """Return the configuration classes one top-level key accepts.

    A key is a section when something with fields sits under it. Scalars and lists of
    scalars resolve to nothing, and are described by their row in the top-level table.
    """
    annotation = getattr(annotation, "__value__", annotation)
    origin = get_origin(annotation)
    if origin is Annotated:
        return _section_types(get_args(annotation)[0])

    if origin in (Union, types.UnionType):
        return [found for argument in get_args(annotation) for found in _section_types(argument)]

    if origin in (list, tuple, set):
        return _section_types(get_args(annotation)[0])

    described = hasattr(annotation, "__pydantic_fields__") or hasattr(annotation, "__json_schema__")
    return [annotation] if inspect.isclass(annotation) and described else []


def _slug(heading: str) -> str:
    """Build the anchor a markdown heading gets, so links cannot drift from headings."""
    return re.sub(r"[^a-z0-9]+", "-", heading.lower()).strip("-")


def _resolve(node: dict[str, Any], defs: dict[str, Any], link: Callable[[str, str], str]) -> str:
    """Describe a schema node, handing every object type it names to `link`."""
    if reference := node.get("$ref"):
        name = reference.rsplit("/", 1)[-1]
        target = defs.get(name, {})
        if "properties" in target:
            return link(name, target.get("title", name))

        return _resolve(target, defs, link)

    if options := node.get("anyOf") or node.get("oneOf"):
        described = [
            _resolve(option, defs, link) for option in options if option != {"type": "null"}
        ]
        return " or ".join(described)

    if values := node.get("enum"):
        return " or ".join(f"`{value}`" for value in values)

    kind = node.get("type", "any")
    if isinstance(kind, list):
        kind = " or ".join(entry for entry in kind if entry != "null") or "any"

    if kind == "array":
        return f"list of {_resolve(node.get('items', {}), defs, link)}"

    return str(kind)


def _root(schema: dict[str, Any], defs: dict[str, Any]) -> dict[str, Any]:
    """Follow a schema whose root is only a reference, which Pydantic's models are."""
    reference = schema.get("$ref")
    if isinstance(reference, str):
        return defs.get(reference.rsplit("/", 1)[-1], schema)

    return schema


def _table(
    schema: dict[str, Any], defs: dict[str, Any], link: Callable[[str, str], str]
) -> list[str]:
    """Render one object schema's keys as a table."""
    required = set(schema.get("required", []))
    lines = ["| Key | Type | Default | Description |", "| --- | --- | --- | --- |"]
    for key, node in schema.get("properties", {}).items():
        default = node.get("default")
        shown = "required" if key in required else ("" if default is None else f"`{default!r}`")
        summary = " ".join(str(node.get("description", "")).split())
        written = key.replace("_", "-")
        lines.append(f"| `{written}` | {_resolve(node, defs, link)} | {shown} | {summary} |")

    return lines


def _describe(
    title: str, schema: dict[str, Any], defs: dict[str, Any], seen: dict[str, str]
) -> list[str]:
    """Render an object schema and every object type reachable from it.

    Nested types are headed by their own name rather than by the key path that reached
    them, because the same type is reached by several paths and the component tree nests
    into itself without bound.
    """
    pending: list[tuple[str, dict[str, Any]]] = []

    def link(name: str, shown: str) -> str:
        if name not in seen:
            seen[name] = _slug(shown)
            pending.append((shown, defs[name]))

        return f"[`{shown}`](#{seen[name]})"

    lines: list[str] = []
    described = [(title, _root(schema, defs))]
    while described or pending:
        heading, node = described.pop(0) if described else pending.pop(0)
        summary = " ".join(str(node.get("description", "")).split())
        lines += ["", f"## {heading}" if heading == title else f"### `{heading}`", ""]
        if summary:
            lines += [summary, ""]

        lines += _table(node, defs, link)

    return lines


def render_configuration() -> str:
    """Render every key `ceres.yaml` accepts, section by section."""
    from ceres.config import Config
    from ceres.data import to_json_schema

    lines = [
        BANNER,
        "",
        "# Configuration",
        "",
        "Every key a `ceres.yaml` accepts. Keys are written in kebab-case, and the snake_case",
        "spelling of any multi-word key is accepted too.",
        "",
        "## Top Level",
        "",
        "| Key | Accepts |",
        "| --- | --- |",
    ]
    sections: list[tuple[str, str, type]] = []
    for key, field in Config.__pydantic_fields__.items():
        found = _section_types(field.annotation)
        for section in found:
            tag = getattr(section, "__type_tag__", None)
            sections.append((f"`{key}` with `type: {tag}`" if tag else f"`{key}`", key, section))

        if found:
            accepts = ", ".join(
                f"[{title}](#{_slug(title)})" for title, named, _ in sections if named == key
            )
        else:
            schema = to_json_schema(field.annotation)
            accepts = _resolve(schema, schema.get("$defs", {}), lambda _, shown: f"`{shown}`")

        lines.append(f"| `{key}` | {accepts} |")

    seen: dict[str, str] = {}
    for title, _, section in sections:
        schema = to_json_schema(section)
        lines += _describe(title, schema, schema.get("$defs", {}), seen)

    return "\n".join(lines).rstrip() + "\n"


PLACEHOLDER_VERSION = "0.0.0"
"""Version stamped into the recorded API document.

The real version would rewrite the recorded file on every release and fail the check for a
change nobody made. A running engine serves the document with its own version.
"""


def _document() -> dict[str, Any]:
    """Return the OpenAPI document the engine serves, at the recorded version."""
    from ceres.__internal__.core import openapi_schema

    return json.loads(openapi_schema(PLACEHOLDER_VERSION))


def render_http_api() -> str:
    """Render every route the engine serves, grouped by the area it belongs to."""
    document = _document()
    lines = [
        BANNER,
        "",
        "# HTTP API",
        "",
        "Every route the engine serves. A running engine serves this same description as",
        "OpenAPI at `/api/openapi.json`, and `/api` redirects there. The recorded copy is",
        "[`openapi.json`](openapi.json), stamped with a placeholder version.",
        "",
        "A route marked `required` refuses any request without a bearer token, which",
        "`POST /api/auth/login` issues. A route marked `optional` accepts one and does not",
        "insist, which covers both the routes open to anyone and the routes that check the",
        "caller themselves against the resource they name.",
    ]
    grouped: dict[str, list[str]] = {}
    for path, operations in sorted(document.get("paths", {}).items()):
        for method, operation in operations.items():
            tag = (operation.get("tags") or ["other"])[0]
            requirements = operation.get("security") or []
            token = "optional" if any(not entry for entry in requirements) else "required"
            summary = " ".join(str(operation.get("summary", "")).split())
            grouped.setdefault(tag, []).append(
                f"| `{method.upper()}` | `{path}` | {token} | {summary} |"
            )

    for tag, rows in sorted(grouped.items()):
        lines += [
            "",
            f"## {tag.replace('-', ' ').title()}",
            "",
            "| Method | Path | Token | Description |",
            "| --- | --- | --- | --- |",
            *rows,
        ]

    return "\n".join(lines).rstrip() + "\n"


def render_openapi() -> str:
    """Return the OpenAPI document itself, for tooling that consumes it directly."""
    return json.dumps(_document(), indent=2, sort_keys=True) + "\n"


COMMANDS = Path("rust/target/reference/commands.json")
"""Where the native command tree is dumped, by `reference` in `rust/ceres-cli/src/`."""


def _one_line(text: str) -> str:
    """Collapse a description onto one line, a table row ending at the first newline."""
    return " ".join(text.split())


def _option_table(rows: list[str]) -> list[str]:
    """Wrap option rows in their header, or render nothing when there are none."""
    if not rows:
        return []

    return ["", "| Option | Required | Description |", "| --- | --- | --- |", *rows]


def _native_rows(node: dict[str, Any]) -> list[str]:
    """Render one native command's options."""
    rows: list[str] = []
    for argument in node["arguments"]:
        values = argument["values"]
        if argument["positional"]:
            spelling = f"`<{(values[0] if values else 'VALUE')}>`"
        else:
            spelling = f"`-{argument['short']}`, " if argument["short"] else ""
            spelling += f"`--{argument['long']}`"
            if values:
                spelling += f" `{' '.join(values)}`"

        required = "yes" if argument["required"] else ""
        rows.append(f"| {spelling} | {required} | {_one_line(argument['help'])} |")

    return rows


def _render_command(node: dict[str, Any], path: str, depth: int) -> list[str]:
    """Render one command and everything under it, headed by the words that invoke it."""
    invocation = f"{path} {node['name']}".strip()
    lines = ["", f"{'#' * depth} `{invocation}`"]
    if node["about"]:
        lines += ["", node["about"]]

    lines += _option_table(_native_rows(node))
    for subcommand in node["subcommands"]:
        lines += _render_command(subcommand, invocation, depth + 1)

    return lines


def render_cli() -> str:
    """Render every command `ceres` accepts, from both halves of its surface."""
    if not COMMANDS.exists():
        raise RuntimeError(f"{COMMANDS} is missing, run 'make reference'")

    root = json.loads(COMMANDS.read_text())
    lines = [
        BANNER,
        "",
        "# CLI",
        "",
        "Every command `ceres` accepts. The table commands near the end have no hand-written",
        "declaration at all, their whole surface being generated from the entity definitions,",
        "so a table's flags and the filter keys it serves can never disagree.",
        "",
        "Every command takes the global options, and an address argument accepts `all`, a",
        "component address, or a selector matching several.",
        "",
        "## Global Options",
        *_option_table(_native_rows(root)),
        "",
        "## Commands",
    ]
    for subcommand in root["subcommands"]:
        lines += _render_command(subcommand, "ceres", 3)

    return "\n".join(lines).rstrip() + "\n"


_PAGES = {
    "python-api.md": render_python_api,
    "configuration.md": render_configuration,
    "http-api.md": render_http_api,
    "openapi.json": render_openapi,
    "cli.md": render_cli,
}
"""Each generated page and what renders it."""


def main() -> int:
    check = "--check" in sys.argv
    stale: list[str] = []
    REFERENCE.mkdir(parents=True, exist_ok=True)

    for name, render in _PAGES.items():
        path = REFERENCE / name
        rendered = render()
        if check:
            if not path.exists() or path.read_text() != rendered:
                stale.append(name)
                print(f"{name}: out of date")
            else:
                print(f"{name}: up to date")

            continue

        changed = not path.exists() or path.read_text() != rendered
        path.write_text(rendered)
        print(f"{name}: {'updated' if changed else 'unchanged'}")

    if stale:
        print("\nRun 'make reference' to regenerate the pages from the code.")

    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
