#!/usr/bin/env uv run

"""Generate the entity model modules from the native table schemas.

The Rust entity definitions are the single source of truth for every table's fields,
families, operations, and docs. `cargo test -p ceres-database describe::` dumps them to
`rust/target/models/tables.json`, and this script renders one module per entity module
under `ceres/__internal__/models/`. Run `make models`, which orders the two, and
`--check` fails when a rendered module no longer matches what the code says.
"""

import json
import re
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Any

# ruff: disable[T201] # Allow print statements.

MODELS = Path("ceres/__internal__/models")
"""Where the generated modules live."""

DUMP = Path("rust/target/models/tables.json")
"""The native schema dump this script renders."""

BANNER = "# Generated by scripts/update-models.py. Run 'make models' to update."

WIDTH = 100
"""The project line width, which rendered docstrings wrap to."""

FILTER_TYPES = {
    "uuid": "MaybeSequence[UUID] | None",
    "text": "MaybeSequence[str] | None",
    "email": "MaybeSequence[EmailAddress] | None",
    "boolean": "bool | None",
    "json_value": "FromYAML[JSONSerializable] | None",
    "plain_address": "MaybeSequence[Address] | None",
    "level": "MaybeSequence[Level] | None",
}
"""Filter field annotations by family, for the families the tables use."""

ARGS_TYPES = {**FILTER_TYPES, "json_value": "JSONSerializable | None"}
"""FilterArgs annotations, which skip YAML coercion since TypedDicts never validate."""

CREATE_TYPES = {
    "uuid": "UUID",
    "text": "str",
    "email": "EmailAddress",
    "boolean": "bool",
    "json": "FromYAML[JSONSerializableDict]",
    "json_value": "FromYAML[JSONSerializable]",
    "plain_address": "Address",
    "level": "Level",
}
"""Create and update annotations by family."""

DATA_IMPORTS = (
    "BytesFromString",
    "BytesToString",
    "EmailAddress",
    "FromYAML",
    "JSONSerializable",
    "JSONSerializableDict",
    "MaybeSequence",
    "Name",
    "NonEmptyStr",
    "Password",
    "PasswordHash",
    "StrEnum",
    "Username",
)
"""Names importable from `ceres.data`, matched against the rendered body."""

CONFIG_IMPORTS = ("ComponentAccessLevel",)
"""Names importable from `ceres.config`, matched against the rendered body."""

ENTITY_BASES = tuple(
    f"Base{family}Entity{suffix}"
    for family in ("UUID", "Address", "")
    for suffix in ("Create", "Field", "Filter", "FilterArgs", "Order")
)
"""Base names importable from `ceres.__internal__.entity`, matched against the body."""

RECORD_BASES = tuple(
    f"BaseRecord{suffix}"
    for suffix in ("Create", "Field", "Filter", "FilterArgs", "Order", "Update")
)
"""Base names importable from `ceres.__internal__.record`, matched against the body."""

FILTER_NOUNS = {
    "email": "email addresses",
    "uuid": "UUIDs",
    "plain_address": "addresses",
    "values": "values",
    "bytes": "byte sequences",
}
"""What a filter equality docstring calls the given values, when not the key itself."""

VALUE_FILTER_DOC = (
    "Filter by `{key}` being exactly equal to the given JSON-serializable value.\n\n"
    "The value reads as YAML, matching how the create and update models take it, so a "
    "command line comparing against a number or a boolean compares against that rather "
    "than against its text."
)
"""The docstring of a `json_value` filter field."""

INTERNAL_DOC = (
    "Filter variables based on whether they are internal or not. Internal variables are "
    "those that start with and end with two underscores, for example `__enabled__`. If "
    "`None`, both internal and non-internal variables will be matched."
)


@dataclass(frozen=True)
class Enum:
    """One generated `StrEnum`, whose values come from a table's `values` family field."""

    name: str
    table: str
    key: str
    doc: str
    member_docs: MappingProxyType[str, str] | None = None
    """Docstrings by member value, or `None` for bare members."""
    aliases: bool = False
    """Whether to render `<Name>Raw` and `<Name>Input` aliases beside the enum."""


@dataclass(frozen=True)
class Entity:
    """One table's rendering configuration the dump does not carry."""

    table: str
    name: str
    hidden: frozenset[str] = frozenset()
    """Columns kept out of the `Field` and `Order` literals, a user's password hash."""
    computed_docs: MappingProxyType[str, str] = MappingProxyType({})
    """Docstrings for the table's computed filter keys."""
    defaults: MappingProxyType[str, Any] = MappingProxyType({})
    """Create defaults as JSON values, for record tables where the dump carries none."""


@dataclass(frozen=True)
class Module:
    """One generated file, covering the tables its source module declares."""

    file: str
    source: str
    """The module declaring the entity classes the filters forward-reference."""
    entities: tuple[Entity, ...]
    enums: tuple[Enum, ...] = ()
    preamble: tuple[str, ...] = ()
    """Literal lines rendered after the enums, for supporting type aliases."""
    extra_all: tuple[str, ...] = ()
    """Names beyond the model and enum sets to list in `__all__`."""


MODULES = [
    Module("users.py", "ceres.user", (Entity("users", "User", hidden=frozenset({"password"})),)),
    Module("settings.py", "ceres.setting", (Entity("settings", "Setting"),)),
    Module(
        "variables.py",
        "ceres.variable",
        (
            Entity(
                "variables",
                "Variable",
                computed_docs=MappingProxyType({"internal": INTERNAL_DOC}),
            ),
        ),
    ),
    Module(
        "workspaces.py",
        "ceres.workspace",
        (
            Entity("workspace_edits", "WorkspaceEdit"),
            Entity(
                "workspaces",
                "Workspace",
                computed_docs=MappingProxyType(
                    {
                        "placed_on_engine": (
                            "Filter by whether the workspace is placed on the engine root "
                            "rather than a component."
                        ),
                        "owned": "Filter by whether the workspace is private to an owner at all.",
                    }
                ),
            ),
        ),
    ),
    Module(
        "groups.py",
        "ceres.group",
        (
            Entity("groups", "Group"),
            Entity("group_memberships", "GroupMembership"),
        ),
    ),
    Module(
        "permissions.py",
        "ceres.permission",
        (
            Entity("user_permissions", "UserPermission"),
            Entity("group_permissions", "GroupPermission"),
        ),
        enums=(
            Enum(
                "PermissionTargetType",
                "user_permissions",
                "target_type",
                "Discriminator for the kind of target a permission grant applies to.",
                MappingProxyType(
                    {
                        "component": "Grant applies to a specific component by address.",
                        "tag": "Grant applies to all components carrying a given tag.",
                        "all": "Grant applies to every component. The target string is empty.",
                    }
                ),
            ),
        ),
    ),
    Module(
        "alerts.py",
        "ceres.alert",
        (Entity("alerts", "Alert", defaults=MappingProxyType({"data": {}})),),
    ),
    Module(
        "messages.py",
        "ceres.message",
        (Entity("messages", "Message", defaults=MappingProxyType({"connection": None})),),
        enums=(
            Enum(
                "MessageDirection",
                "messages",
                "direction",
                "Direction of a message on a connection, either outbound or inbound.",
                aliases=True,
            ),
        ),
        preamble=(
            "type MessageData = Annotated[",
            "    bytes,",
            '    BytesFromString("latin-1", "ignore"),',
            '    BytesToString("latin-1", "ignore"),',
            "]",
            '"""Raw message payload bytes, serialized to and from `latin-1` strings for transport."""',
        ),
        extra_all=("MessageData",),
    ),
    Module("logs.py", "ceres.logs", (Entity("logs", "LogEntry"),)),
]


def load_tables() -> dict[str, dict[str, Any]]:
    if not DUMP.is_file():
        print(f"{DUMP} is missing. Run `make models`, which dumps it first.")
        sys.exit(1)

    return {table["name"]: table for table in json.loads(DUMP.read_text())["tables"]}


def base_family(table: dict[str, Any]) -> str:
    """The base class family the table's key selects."""
    key = table["key"]
    if key == ["id"]:
        return "UUID"

    if "address" in key:
        return "Address"

    return ""


def docstring(text: str, indent: str) -> list[str]:
    """Render a docstring block, single-line where it fits and wrapped to width."""
    paragraphs = [
        textwrap.fill(paragraph.strip(), WIDTH - len(indent))
        for paragraph in text.split("\n\n")
        if paragraph.strip()
    ]
    if not paragraphs:
        return []

    if len(paragraphs) == 1 and "\n" not in paragraphs[0]:
        line = f'{indent}"""{paragraphs[0]}"""'
        if len(line) <= WIDTH:
            return [line]

    joined = "\n\n".join(paragraphs)
    lines = joined.splitlines()
    rendered = [f'{indent}"""{lines[0]}']
    rendered.extend(f"{indent}{line}".rstrip() for line in lines[1:])
    rendered.append(f'{indent}"""')
    return rendered


def field_doc(field: dict[str, Any]) -> str:
    """The first paragraph of a field's doc comment."""
    return field["doc"].split("\n\n")[0].replace("\n", " ").strip()


def filter_doc(field: dict[str, Any]) -> str:
    """The docstring of a filter equality field, phrased per family."""
    key = field["key"]
    family = field["family"]["name"]
    if family == "boolean":
        return f"Filter by `{key}` being either `True` or `False`."

    if family == "json_value":
        return VALUE_FILTER_DOC.format(key=key)

    noun = FILTER_NOUNS.get(family, f"{key}s")
    return f"Filter by `{key}` being equal to one or more given {noun}."


def filter_annotation(field: dict[str, Any], types: dict[str, str], input_form: str = "") -> str:
    """The filter or args annotation, parameterized by the Python type for `values` and
    `bytes` families. `input_form` widens a `values` annotation to the enum's input alias."""
    family = field["family"]["name"]
    if family == "values":
        return f"MaybeSequence[{field['python']}{input_form}] | None"

    if family == "bytes":
        return f"MaybeSequence[{field['python']}] | None"

    return types[family]


def create_annotation(field: dict[str, Any], described: dict[str, Any] | None) -> str:
    """The create and update annotation, nullable when the column defaults to null."""
    if field["family"]["name"] == "values":
        annotation = field["python"]
    else:
        annotation = field["python"] or CREATE_TYPES[field["family"]["name"]]
    if described is not None and described.get("value", ...) is None:
        annotation += " | None"

    return annotation


def default_expression(field: dict[str, Any], value: Any) -> str:
    """Render a column default as the expression the create model carries."""
    family = field["family"]["name"]
    if value is None:
        return "None"

    if family == "plain_address":
        return f'Address("{value}")'

    if family == "json":
        if value == {}:
            return "Field(default_factory=dict)"

        raise ValueError(f"no rendering for a non-empty json default: {value!r}")

    if isinstance(value, bool):
        return str(value)

    if isinstance(value, str):
        return f'"{value}"'

    return repr(value)


OPERATION_DOCS = {
    "contains": "containing one or more given substrings",
    "prefix": "starting with one or more given prefixes",
    "suffix": "ending with one or more given suffixes",
}

BYTES_OPERATION_DOCS = {
    "contains": "containing one or more given byte substrings",
    "prefix": "starting with one or more given byte prefixes",
    "suffix": "ending with one or more given byte suffixes",
}

JSON_OPERATION_DOCS = {
    "contains": "contains one or more given substrings",
    "prefix": "starts with one or more given prefixes",
    "suffix": "ends with one or more given suffixes",
}


def operation_doc(field: dict[str, Any], kind: str) -> str:
    """The docstring of one operation key, phrased per family."""
    key = field["key"]
    family = field["family"]["name"]
    if family == "json":
        return f"Filter by whether or not the JSON text of `{key}` {JSON_OPERATION_DOCS[kind]}."

    if family == "bytes":
        return f"Filter by `{key}` {BYTES_OPERATION_DOCS[kind]}."

    return f"Filter by `{key}` {OPERATION_DOCS[kind]}."


def operation_annotation(field: dict[str, Any]) -> str:
    """The annotation of one operation key, byte operations taking the payload type."""
    if field["family"]["name"] == "bytes":
        return f"MaybeSequence[{field['python']}] | None"

    return "MaybeSequence[str] | None"


def render_entity(table: dict[str, Any], entity: Entity, enums: tuple[Enum, ...]) -> list[str]:
    """Render one table's literals, filters, and operation models."""
    name = entity.name
    if table["kind"] == "record":
        base = "BaseRecord"
        base_keys = {"id", "address", "timestamp"}
    else:
        family = base_family(table)
        base = f"Base{family}Entity" if family else "BaseEntity"
        base_keys = {"id"} if family == "UUID" else {"address"} if family == "Address" else set()

    plain = base == "BaseEntity"
    aliased = {enum.name for enum in enums if enum.aliases}

    def selectable(field: dict[str, Any]) -> bool:
        return field["key"] not in base_keys and field["key"] not in entity.hidden

    def input_form(field: dict[str, Any]) -> str:
        return "Input" if field["python"] in aliased else ""

    columns = [column for column in table["columns"] if column["key"] not in base_keys]
    literals = [column["key"] for column in table["columns"] if selectable(column)]
    # Ordering resolves over the filterable fields, so a skipped column is selectable
    # but never orderable, and ordering by JSON text is not advertised.
    orderable = [
        field["key"]
        for field in table["fields"]
        if selectable(field) and field["family"]["name"] != "json"
    ]
    fields = [field for field in table["fields"] if field["key"] not in base_keys]
    regular = [field for field in fields if field["family"]["name"] != "json_value"]
    nullable = [field for field in fields if field["family"]["name"] == "json_value"]
    fixed = set(table["fixed"])
    defaults = {
        **table["defaults"],
        **{key: {"value": value} for key, value in entity.defaults.items()},
    }
    lines: list[str] = []

    # Field and order literals.
    def literal(alias: str, keys: list[str], suffixes: tuple[str, ...]) -> None:
        if not plain:
            lines.append(f"type {name}{alias} = (")
            lines.append(f"    {base}{alias}")
            lines.append("    | Literal[")
            for key in keys:
                for suffix in suffixes:
                    lines.append(f'        "{key}{suffix}",')
            lines.append("    ]")
            lines.append(")")
        else:
            lines.append(f"type {name}{alias} = Literal[")
            for key in keys:
                for suffix in suffixes:
                    lines.append(f'    "{key}{suffix}",')
            lines.append("]")

    literal("Field", literals, ("",))
    lines.append(f'"""Field names selectable in `{name}` queries."""')
    lines.append("")
    literal("Order", orderable, ("", ":asc", ":desc"))
    lines.append(f'"""Ordering keys accepted by `{name}` queries."""')
    lines.append("")
    lines.append("")

    # FilterArgs.
    lines.append(
        f"class {name}FilterArgs({base}FilterArgs[{name}Field, {name}Order], total=False):"
    )
    lines.append(f'    """Keyword-argument form of `{name}Filter` for ergonomic call sites."""')
    lines.append("")
    for field in regular:
        family_name = field["family"]["name"]
        if family_name != "json":
            lines.append(
                f"    {field['key']}: {filter_annotation(field, ARGS_TYPES, input_form(field))}"
            )
        if family_name == "level":
            lines.append(f"    min_{field['key']}: Level | None")
            lines.append(f"    max_{field['key']}: Level | None")
        for operation in field["operations"]:
            lines.append(f"    {operation['key']}: {operation_annotation(field)}")
    for computed in table["computed"]:
        lines.append(f"    {computed['key']}: bool | None")
    for field in nullable:
        lines.append(f"    {field['key']}: {filter_annotation(field, ARGS_TYPES)}")
    lines.append("")
    lines.append("")

    # Filter.
    lines.append(f'class {name}Filter({base}Filter["{name}", {name}Field, {name}Order]):')
    lines.append(f'    """Filter for selecting `{name}` records."""')
    lines.append("")
    lines.append(f'    __table__: ClassVar[str] = "{table["name"]}"')
    lines.append("")
    for field in regular:
        key = field["key"]
        family_name = field["family"]["name"]
        if family_name != "json":
            lines.append(f"    {key}: {filter_annotation(field, FILTER_TYPES)} = None")
            lines.extend(docstring(filter_doc(field), "    "))
        if family_name == "level":
            lines.append(f"    min_{key}: Level | None = None")
            lines.extend(
                docstring(
                    f"Filter by `{key}` being greater than or equal to the given level value.",
                    "    ",
                )
            )
            lines.append(f"    max_{key}: Level | None = None")
            lines.extend(
                docstring(
                    f"Filter by `{key}` being less than or equal to the given level value.",
                    "    ",
                )
            )
        for operation in field["operations"]:
            lines.append(f"    {operation['key']}: {operation_annotation(field)} = None")
            lines.extend(docstring(operation_doc(field, operation["kind"]), "    "))
    for computed in table["computed"]:
        lines.append(f"    {computed['key']}: bool | None = None")
        lines.extend(docstring(entity.computed_docs[computed["key"]], "    "))
    if nullable:
        keys = ", ".join(f'"{field["key"]}"' for field in nullable)
        lines.append(f"    __nullable_filters__: ClassVar[frozenset[str]] = frozenset({{{keys}}})")
        lines.append("")
        for field in nullable:
            lines.append(f"    {field['key']}: {filter_annotation(field, FILTER_TYPES)} = None")
            lines.extend(docstring(filter_doc(field), "    "))
    lines.append("")
    lines.append("")

    # Create.
    lines.append(f"class {name}Create({base}Create, slots=True):")
    lines.append(f'    """Payload for creating a new `{name}` record."""')
    lines.append("")
    for column in columns:
        key = column["key"]
        default = ""
        described = defaults.get(key)
        if described and "value" in described:
            default = f" = {default_expression(column, described['value'])}"
        lines.append(f"    {key}: {create_annotation(column, described)}{default}")
        lines.extend(docstring(field_doc(column), "    "))
    lines.append("")
    lines.append("")

    # Update.
    settable = [column for column in columns if column["key"] not in fixed]
    update_doc = f"Partial update for an existing `{name}` record."
    if not settable:
        update_doc += (
            "\n\nThe record is only created or deleted, so this update payload has no "
            "mutable fields."
        )
    update_base = "BaseRecordUpdate" if table["kind"] == "record" else "TypedDict"
    lines.append(f"class {name}Update({update_base}, total=False):")
    lines.extend(docstring(update_doc, "    "))
    if settable:
        lines.append("")
    for column in settable:
        lines.append(
            f"    {column['key']}: {create_annotation(column, defaults.get(column['key']))}"
        )
    return lines


def render_enum(table: dict[str, Any], enum: Enum) -> list[str]:
    """Render one generated `StrEnum` from a `values` family field."""
    field = next(field for field in table["columns"] if field["key"] == enum.key)
    values = field["family"]["values"]
    lines = [f"class {enum.name}(StrEnum):"]
    lines.extend(docstring(enum.doc, "    "))
    lines.append("")
    for value in values:
        lines.append(f'    {value.upper()} = "{value}"')
        if enum.member_docs is not None:
            lines.extend(docstring(enum.member_docs[value], "    "))
    if enum.aliases:
        quoted = ", ".join(f'"{value}"' for value in values)
        lines.extend(
            [
                "",
                "",
                f"type {enum.name}Raw = Literal[{quoted}]",
                f'"""Raw string form of `{enum.name}` accepted as input."""',
                "",
                f"type {enum.name}Input = {enum.name} | {enum.name}Raw",
                f'"""Either a `{enum.name}` enum or its raw string form."""',
            ]
        )
    return lines


def code_only(body: str) -> str:
    """The body with docstring lines removed, so prose never matches an import scan."""
    kept: list[str] = []
    inside = False
    for line in body.splitlines():
        stripped = line.strip()
        if not inside and stripped.startswith('"""'):
            inside = not (len(stripped) > 3 and stripped.endswith('"""'))
            continue

        if inside:
            inside = not stripped.endswith('"""')
            continue

        kept.append(line)

    return "\n".join(kept)


def header(module: Module, body: str) -> list[str]:
    """The module docstring and imports, derived from what the body references."""
    code = code_only(body)

    def used(symbol: str) -> bool:
        return re.search(rf"\b{symbol}\b", code) is not None

    typing = [
        symbol
        for symbol in ("Annotated", "Any", "ClassVar", "Literal", "TypedDict")
        if used(symbol)
    ]
    entity = sorted(base for base in ENTITY_BASES if used(base))
    record = sorted(base for base in RECORD_BASES if used(base))
    data = sorted(symbol for symbol in DATA_IMPORTS if used(symbol))
    config = sorted(symbol for symbol in CONFIG_IMPORTS if used(symbol))
    tables = ", ".join(f"`{entity.table}`" for entity in module.entities)
    names = ", ".join(sorted(entity.name for entity in module.entities))

    lines = [
        BANNER,
        "",
        f'"""Generated models for the {tables} table{"s" if len(module.entities) > 1 else ""}."""',
        "",
        f"from typing import TYPE_CHECKING, {', '.join(typing)}",
    ]
    if used("UUID"):
        lines.append("from uuid import UUID")
    lines.append("")
    if re.search(r"\bField\(", body):
        lines.append("from pydantic import Field")
        lines.append("")
    if entity:
        lines.append("from ceres.__internal__.entity import (")
        lines.extend(f"    {symbol}," for symbol in entity)
        lines.append(")")
    if record:
        lines.append("from ceres.__internal__.record import (")
        lines.extend(f"    {symbol}," for symbol in record)
        lines.append(")")
    if used("Address"):
        lines.append("from ceres.address import Address")
    if config:
        lines.append(f"from ceres.config import {', '.join(config)}")
    if data:
        lines.append("from ceres.data import (")
        lines.extend(f"    {symbol}," for symbol in data)
        lines.append(")")
    if used("Level"):
        lines.append("from ceres.level import Level")
    lines.extend(
        [
            "",
            "if TYPE_CHECKING:",
            "    # The filters name them only as forward references.",
            f"    from {module.source} import {names}  # noqa: F401",
            "",
            "__all__ = [",
        ]
    )
    exported = sorted(
        [
            f"{entity.name}{suffix}"
            for entity in module.entities
            for suffix in ("Create", "Field", "Filter", "FilterArgs", "Order", "Update")
        ]
        + [enum.name for enum in module.enums]
        + [
            f"{enum.name}{alias}"
            for enum in module.enums
            if enum.aliases
            for alias in ("Input", "Raw")
        ]
        + list(module.extra_all)
    )
    lines.extend(f'    "{name}",' for name in exported)
    lines.extend(["]", "", ""])
    return lines


def footer(module: Module) -> list[str]:
    """Reassign the models to the public module, which re-exports them.

    Reprs, pickling, and rendered documentation then name the public path rather than
    this package. The `type` aliases stay put, `TypeAliasType.__module__` is read-only.
    """
    models = ", ".join(
        [enum.name for enum in module.enums]
        + [
            f"{entity.name}{suffix}"
            for entity in module.entities
            for suffix in ("Create", "Filter", "FilterArgs", "Update")
        ]
    )
    return [
        "",
        "",
        "# Present the models as part of the public module that re-exports them.",
        f"for _model in ({models}):",
        f'    _model.__module__ = "{module.source}"',
    ]


def formatted(name: str, text: str) -> str:
    """Canonicalize with the project formatter, which wraps wide class headers."""
    result = subprocess.run(
        ["ruff", "format", "--stdin-filename", name, "-"],
        input=text,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def render_module(module: Module, tables: dict[str, dict[str, Any]]) -> str:
    bodies = [render_enum(tables[enum.table], enum) for enum in module.enums]
    if module.preamble:
        bodies.append(list(module.preamble))
    bodies.extend(
        render_entity(tables[entity.table], entity, module.enums) for entity in module.entities
    )
    body = "\n\n\n".join("\n".join(lines).rstrip() for lines in bodies)
    text = "\n".join(header(module, body)) + "\n" + body
    text = text.rstrip() + "\n" + "\n".join(footer(module)) + "\n"
    return formatted(module.file, text)


def main() -> int:
    check = "--check" in sys.argv
    tables = load_tables()
    MODELS.mkdir(parents=True, exist_ok=True)
    init = MODELS / "__init__.py"
    if not init.exists() and not check:
        init.write_text(BANNER + "\n")

    failed = False
    for module in MODULES:
        path = MODELS / module.file
        text = render_module(module, tables)
        if check:
            if not path.is_file() or path.read_text() != text:
                print(f"{path} is out of date. Run `make models`.")
                failed = True
        else:
            path.write_text(text)
            print(f"{path}: updated")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
