#!/usr/bin/env uv run

"""Generate the entity model modules from the native table schemas.

The Rust entity definitions are the single source of truth for every table's fields,
families, operations, and docs. `cargo test -p ceres-database describe::` dumps them to
`rust/target/models/tables.json`, and this script renders one module per entity module
under `ceres/__internal__/models/`. Run `make models`, which orders the two, and
`--check` fails when a rendered module no longer matches what the code says.
"""

import json
import re
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Any

# ruff: disable[T201] # Allow print statements.

MODELS = Path("ceres/__internal__/models")
"""Where the generated modules live."""

DUMP = Path("rust/target/models/tables.json")
"""The native schema dump this script renders."""

BANNER = "# Generated by scripts/update-models.py. Run 'make models' to update."

WIDTH = 100
"""The project line width, which rendered docstrings wrap to."""

FILTER_TYPES = {
    "uuid": "MaybeSequence[UUID] | None",
    "text": "MaybeSequence[str] | None",
    "email": "MaybeSequence[EmailAddress] | None",
    "boolean": "bool | None",
    "json_value": "FromYAML[JSONSerializable] | None",
}
"""Filter field annotations by family, for the families the entity tables use."""

ARGS_TYPES = {**FILTER_TYPES, "json_value": "JSONSerializable | None"}
"""FilterArgs annotations, which skip YAML coercion since TypedDicts never validate."""

CREATE_TYPES = {
    "uuid": "UUID",
    "text": "str",
    "email": "EmailAddress",
    "boolean": "bool",
    "json": "dict[str, Any]",
    "json_value": "FromYAML[JSONSerializable]",
    "plain_address": "Address",
}
"""Create and update annotations by family."""

DATA_IMPORTS = (
    "EmailAddress",
    "FromYAML",
    "JSONSerializable",
    "MaybeSequence",
    "Password",
    "PasswordHash",
    "Username",
)
"""Names importable from `ceres.data`, matched against the rendered body."""

ENTITY_BASES = tuple(
    f"Base{family}Entity{suffix}"
    for family in ("UUID", "Address", "")
    for suffix in ("Create", "Field", "Filter", "FilterArgs", "Order")
)
"""Base names importable from `ceres.__internal__.entity`, matched against the body."""

FILTER_NOUNS = {"email": "email addresses", "uuid": "UUIDs"}
"""What a filter equality docstring calls the given values, when not the key itself."""

VALUE_FILTER_DOC = (
    "Filter by `{key}` being exactly equal to the given JSON-serializable value.\n\n"
    "The value reads as YAML, matching how the create and update models take it, so a "
    "command line comparing against a number or a boolean compares against that rather "
    "than against its text."
)
"""The docstring of a `json_value` filter field."""

INTERNAL_DOC = (
    "Filter variables based on whether they are internal or not. Internal variables are "
    "those that start with and end with two underscores, for example `__enabled__`. If "
    "`None`, both internal and non-internal variables will be matched."
)


@dataclass(frozen=True)
class Entity:
    """One table's rendering configuration the dump does not carry."""

    table: str
    name: str
    hidden: frozenset[str] = frozenset()
    """Columns kept out of the `Field` and `Order` literals, a user's password hash."""
    computed_docs: MappingProxyType[str, str] = MappingProxyType({})
    """Docstrings for the table's computed filter keys."""


@dataclass(frozen=True)
class Module:
    """One generated file, covering the tables its source module declares."""

    file: str
    source: str
    """The module declaring the entity classes the filters forward-reference."""
    entities: tuple[Entity, ...]


MODULES = [
    Module("users.py", "ceres.user", (Entity("users", "User", hidden=frozenset({"password"})),)),
    Module("settings.py", "ceres.setting", (Entity("settings", "Setting"),)),
    Module(
        "variables.py",
        "ceres.variable",
        (
            Entity(
                "variables",
                "Variable",
                computed_docs=MappingProxyType({"internal": INTERNAL_DOC}),
            ),
        ),
    ),
]


def load_tables() -> dict[str, dict[str, Any]]:
    if not DUMP.is_file():
        print(f"{DUMP} is missing. Run `make models`, which dumps it first.")
        sys.exit(1)

    return {table["name"]: table for table in json.loads(DUMP.read_text())["tables"]}


def base_family(table: dict[str, Any]) -> str:
    """The base class family the table's key selects."""
    key = table["key"]
    if key == ["id"]:
        return "UUID"

    if "address" in key:
        return "Address"

    return ""


def docstring(text: str, indent: str) -> list[str]:
    """Render a docstring block, single-line where it fits and wrapped to width."""
    paragraphs = [
        textwrap.fill(paragraph.strip(), WIDTH - len(indent))
        for paragraph in text.split("\n\n")
        if paragraph.strip()
    ]
    if not paragraphs:
        return []

    if len(paragraphs) == 1 and "\n" not in paragraphs[0]:
        line = f'{indent}"""{paragraphs[0]}"""'
        if len(line) <= WIDTH:
            return [line]

    joined = "\n\n".join(paragraphs)
    lines = joined.splitlines()
    rendered = [f'{indent}"""{lines[0]}']
    rendered.extend(f"{indent}{line}".rstrip() for line in lines[1:])
    rendered.append(f'{indent}"""')
    return rendered


def field_doc(field: dict[str, Any]) -> str:
    """The first paragraph of a field's doc comment."""
    return field["doc"].split("\n\n")[0].replace("\n", " ").strip()


def filter_doc(field: dict[str, Any]) -> str:
    """The docstring of a filter equality field, phrased per family."""
    key = field["key"]
    family = field["family"]["name"]
    if family == "boolean":
        return f"Filter by `{key}` being either `True` or `False`."

    if family == "json_value":
        return VALUE_FILTER_DOC.format(key=key)

    noun = FILTER_NOUNS.get(family, f"{key}s")
    return f"Filter by `{key}` being equal to one or more given {noun}."


def create_annotation(field: dict[str, Any]) -> str:
    if field["python"]:
        return field["python"]

    return CREATE_TYPES[field["family"]["name"]]


OPERATION_DOCS = {
    "contains": "containing one or more given substrings",
    "prefix": "starting with one or more given prefixes",
    "suffix": "ending with one or more given suffixes",
}


def render_entity(table: dict[str, Any], entity: Entity) -> list[str]:
    """Render one table's literals, filters, and operation models."""
    name = entity.name
    family = base_family(table)
    base_keys = {"id"} if family == "UUID" else {"address"} if family == "Address" else set()

    def selectable(field: dict[str, Any]) -> bool:
        return field["key"] not in base_keys and field["key"] not in entity.hidden

    columns = [column for column in table["columns"] if column["key"] not in base_keys]
    literals = [column["key"] for column in table["columns"] if selectable(column)]
    orderable = [
        column["key"]
        for column in table["columns"]
        if selectable(column) and column["family"]["name"] not in ("json", "bytes")
    ]
    fields = [field for field in table["fields"] if field["key"] not in base_keys]
    regular = [field for field in fields if field["family"]["name"] != "json_value"]
    nullable = [field for field in fields if field["family"]["name"] == "json_value"]
    fixed = set(table["fixed"])
    defaults = table["defaults"]
    lines: list[str] = []

    # Field and order literals.
    def literal(alias: str, keys: list[str], suffixes: tuple[str, ...]) -> None:
        if family:
            lines.append(f"type {name}{alias} = (")
            lines.append(f"    Base{family}Entity{alias}")
            lines.append("    | Literal[")
            for key in keys:
                for suffix in suffixes:
                    lines.append(f'        "{key}{suffix}",')
            lines.append("    ]")
            lines.append(")")
        else:
            lines.append(f"type {name}{alias} = Literal[")
            for key in keys:
                for suffix in suffixes:
                    lines.append(f'    "{key}{suffix}",')
            lines.append("]")

    literal("Field", literals, ("",))
    lines.append(f'"""Field names selectable in `{name}` queries."""')
    lines.append("")
    literal("Order", orderable, ("", ":asc", ":desc"))
    lines.append(f'"""Ordering keys accepted by `{name}` queries."""')
    lines.append("")
    lines.append("")

    # FilterArgs.
    lines.append(
        f"class {name}FilterArgs(Base{family}EntityFilterArgs"
        f"[{name}Field, {name}Order], total=False):"
    )
    lines.append(f'    """Keyword-argument form of `{name}Filter` for ergonomic call sites."""')
    lines.append("")
    for field in regular:
        lines.append(f"    {field['key']}: {ARGS_TYPES[field['family']['name']]}")
        for operation in field["operations"]:
            lines.append(f"    {operation['key']}: MaybeSequence[str] | None")
    for computed in table["computed"]:
        lines.append(f"    {computed['key']}: bool | None")
    for field in nullable:
        lines.append(f"    {field['key']}: {ARGS_TYPES[field['family']['name']]}")
    lines.append("")
    lines.append("")

    # Filter.
    lines.append(
        f'class {name}Filter(Base{family}EntityFilter["{name}", {name}Field, {name}Order]):'
    )
    lines.append(f'    """Filter for selecting `{name}` records."""')
    lines.append("")
    lines.append(f'    __table__: ClassVar[str] = "{table["name"]}"')
    lines.append("")
    for field in regular:
        key = field["key"]
        lines.append(f"    {key}: {FILTER_TYPES[field['family']['name']]} = None")
        lines.extend(docstring(filter_doc(field), "    "))
        for operation in field["operations"]:
            lines.append(f"    {operation['key']}: MaybeSequence[str] | None = None")
            lines.extend(
                docstring(f"Filter by `{key}` {OPERATION_DOCS[operation['kind']]}.", "    ")
            )
    for computed in table["computed"]:
        lines.append(f"    {computed['key']}: bool | None = None")
        lines.extend(docstring(entity.computed_docs[computed["key"]], "    "))
    if nullable:
        keys = ", ".join(f'"{field["key"]}"' for field in nullable)
        lines.append(f"    __nullable_filters__: ClassVar[frozenset[str]] = frozenset({{{keys}}})")
        lines.append("")
        for field in nullable:
            lines.append(f"    {field['key']}: {FILTER_TYPES[field['family']['name']]} = None")
            lines.extend(docstring(filter_doc(field), "    "))
    lines.append("")
    lines.append("")

    # Create.
    lines.append(f"class {name}Create(Base{family}EntityCreate, slots=True):")
    lines.append(f'    """Payload for creating a new `{name}` record."""')
    lines.append("")
    for column in columns:
        key = column["key"]
        default = ""
        described = defaults.get(key)
        if described and "value" in described:
            default = f" = {described['value']!r}"
        lines.append(f"    {key}: {create_annotation(column)}{default}")
        lines.extend(docstring(field_doc(column), "    "))
    lines.append("")
    lines.append("")

    # Update.
    lines.append(f"class {name}Update(TypedDict, total=False):")
    lines.append(f'    """Partial update for an existing `{name}` record."""')
    lines.append("")
    for column in columns:
        if column["key"] in fixed:
            continue
        lines.append(f"    {column['key']}: {create_annotation(column)}")
    return lines


def header(module: Module, body: str) -> list[str]:
    """The module docstring and imports, derived from what the body references."""

    def used(symbol: str) -> bool:
        return re.search(rf"\b{symbol}\b", body) is not None

    typing = [symbol for symbol in ("Any", "ClassVar", "Literal", "TypedDict") if used(symbol)]
    entity = sorted(base for base in ENTITY_BASES if used(base))
    data = sorted(symbol for symbol in DATA_IMPORTS if used(symbol))
    tables = ", ".join(f"`{entity.table}`" for entity in module.entities)
    names = ", ".join(entity.name for entity in module.entities)

    lines = [
        BANNER,
        "",
        f'"""Generated models for the {tables} table{"s" if len(module.entities) > 1 else ""}."""',
        "",
        f"from typing import TYPE_CHECKING, {', '.join(typing)}",
    ]
    if used("UUID"):
        lines.append("from uuid import UUID")
    lines.append("")
    lines.append("from ceres.__internal__.entity import (")
    lines.extend(f"    {symbol}," for symbol in entity)
    lines.append(")")
    if data:
        lines.append("from ceres.data import (")
        lines.extend(f"    {symbol}," for symbol in data)
        lines.append(")")
    if used("Address"):
        lines.append("from ceres.address import Address")
    lines.extend(
        [
            "",
            "if TYPE_CHECKING:",
            "    # The filters name them only as forward references.",
            f"    from {module.source} import {names}  # noqa: F401",
            "",
            "__all__ = [",
        ]
    )
    exported = sorted(
        f"{entity.name}{suffix}"
        for entity in module.entities
        for suffix in ("Create", "Field", "Filter", "FilterArgs", "Order", "Update")
    )
    lines.extend(f'    "{name}",' for name in exported)
    lines.extend(["]", "", ""])
    return lines


def render_module(module: Module, tables: dict[str, dict[str, Any]]) -> str:
    bodies = [render_entity(tables[entity.table], entity) for entity in module.entities]
    body = "\n\n\n".join("\n".join(lines).rstrip() for lines in bodies)
    text = "\n".join(header(module, body)) + "\n" + body
    return text.rstrip() + "\n"


def main() -> int:
    check = "--check" in sys.argv
    tables = load_tables()
    MODELS.mkdir(parents=True, exist_ok=True)
    init = MODELS / "__init__.py"
    if not init.exists() and not check:
        init.write_text(BANNER + "\n")

    failed = False
    for module in MODULES:
        path = MODELS / module.file
        text = render_module(module, tables)
        if check:
            if not path.is_file() or path.read_text() != text:
                print(f"{path} is out of date. Run `make models`.")
                failed = True
        else:
            path.write_text(text)
            print(f"{path}: updated")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
