#!/usr/bin/env uv run

"""Generate the entity model modules from the native table schemas.

The Rust entity definitions are the single source of truth for every table's fields,
families, operations, and docs. `cargo test -p ceres-database describe::` dumps them to
`rust/target/models/tables.json`, and this script renders one module per table under
`ceres/__internal__/models/`. Run `make models`, which orders the two, and `--check`
fails when a rendered module no longer matches what the code says.
"""

import json
import sys
from pathlib import Path
from typing import Any

MODELS = Path("ceres/__internal__/models")
"""Where the generated modules live."""

DUMP = Path("rust/target/models/tables.json")
"""The native schema dump this script renders."""

BANNER = "# Generated by scripts/update-models.py. Run 'make models' to update."

FILTER_TYPES = {
    "uuid": "MaybeSequence[UUID] | None",
    "text": "MaybeSequence[str] | None",
    "email": "MaybeSequence[EmailAddress] | None",
    "boolean": "bool | None",
    "json_value": "Any | None",
}
"""Filter field annotations by family, for the families the entity tables use."""

CREATE_TYPES = {
    "uuid": "UUID",
    "text": "str",
    "email": "EmailAddress",
    "boolean": "bool",
    "json": "dict[str, Any]",
    "json_value": "Any",
    "plain_address": "Address",
}
"""Create and update annotations by family."""

REFINEMENT_IMPORTS = {
    "Username": "ceres.data",
    "Password": "ceres.data",
    "PasswordHash": "ceres.data",
    "EmailAddress": "ceres.data",
    "MaybeSequence": "ceres.data",
    "Address": "ceres.address",
    "UUID": "uuid",
    "Any": "typing",
}
"""Where each refinement name imports from, for the module header."""

# Rendered per-table configuration the dump does not carry: the Python entity name and
# the base family its key selects.
NAMES = {
    "users": "User",
}


def load_tables() -> dict[str, dict[str, Any]]:
    if not DUMP.is_file():
        print(f"{DUMP} is missing. Run `make models`, which dumps it first.")
        sys.exit(1)

    return {table["name"]: table for table in json.loads(DUMP.read_text())["tables"]}


def docstring(text: str, indent: str) -> list[str]:
    """Render a docstring block, single-line where it fits."""
    lines = [line for line in text.splitlines()]
    if not lines:
        return []
    if len(lines) == 1:
        return [f'{indent}"""{lines[0]}"""']

    rendered = [f'{indent}"""{lines[0]}']
    rendered.extend(f"{indent}{line}".rstrip() for line in lines[1:])
    rendered.append(f'{indent}"""')
    return rendered


def field_doc(field: dict[str, Any], fallback: str) -> str:
    """The first paragraph of a field's doc, or a written fallback."""
    doc = field["doc"].split("\n\n")[0].replace("\n", " ").strip()
    return doc or fallback


def filter_annotation(field: dict[str, Any]) -> str:
    return FILTER_TYPES[field["family"]["name"]]


def create_annotation(field: dict[str, Any]) -> str:
    if field["python"]:
        return field["python"]

    return CREATE_TYPES[field["family"]["name"]]


def render_users(table: dict[str, Any]) -> str:
    """Render the users module, the proving ground for the generator."""
    name = NAMES[table["name"]]
    base_keys = {"id"}
    fields = [field for field in table["fields"] if field["key"] not in base_keys]
    columns = [column for column in table["columns"] if column["key"] not in base_keys]
    fixed = set(table["fixed"])
    defaults = table["defaults"]

    lines: list[str] = [
        BANNER,
        "",
        f'"""Generated models for the `{table["name"]}` table."""',
        "",
        "from typing import Any, Literal, TypedDict",
        "from uuid import UUID",
        "",
        "from ceres.__internal__.entity import (",
        "    BaseUUIDEntityCreate,",
        "    BaseUUIDEntityField,",
        "    BaseUUIDEntityFilter,",
        "    BaseUUIDEntityFilterArgs,",
        "    BaseUUIDEntityOrder,",
        ")",
        "from ceres.data import (",
        "    EmailAddress,",
        "    MaybeSequence,",
        "    Password,",
        "    PasswordHash,",
        "    Username,",
        ")",
        "",
        "__all__ = [",
        f'    "{name}Create",',
        f'    "{name}Field",',
        f'    "{name}Filter",',
        f'    "{name}FilterArgs",',
        f'    "{name}Order",',
        f'    "{name}Update",',
        "]",
        "",
        "",
    ]

    # Field and order literals.
    lines.append(f"type {name}Field = (")
    lines.append("    BaseUUIDEntityField")
    lines.append("    | Literal[")
    for field in fields:
        lines.append(f'        "{field["key"]}",')
    lines.append("    ]")
    lines.append(")")
    lines.append(f'"""Field names selectable in `{name}` queries."""')
    lines.append("")
    lines.append(f"type {name}Order = (")
    lines.append("    BaseUUIDEntityOrder")
    lines.append("    | Literal[")
    for field in fields:
        if field["family"]["name"] in ("json", "bytes"):
            continue
        for suffix in ("", ":asc", ":desc"):
            lines.append(f'        "{field["key"]}{suffix}",')
    lines.append("    ]")
    lines.append(")")
    lines.append(f'"""Ordering keys accepted by `{name}` queries."""')
    lines.append("")
    lines.append("")

    # FilterArgs.
    lines.append(
        f"class {name}FilterArgs(BaseUUIDEntityFilterArgs[{name}Field, {name}Order], total=False):"
    )
    lines.append(f'    """Keyword-argument form of `{name}Filter` for ergonomic call sites."""')
    lines.append("")
    for field in fields:
        lines.append(f"    {field['key']}: {filter_annotation(field)}")
        for operation in field["operations"]:
            lines.append(f"    {operation['key']}: MaybeSequence[str] | None")
    lines.append("")
    lines.append("")

    # Filter.
    lines.append(f'class {name}Filter(BaseUUIDEntityFilter["{name}", {name}Field, {name}Order]):')
    lines.append(f'    """Filter for selecting `{name}` records."""')
    lines.append("")
    lines.append(f'    __table__: ClassVar[str] = "{table["name"]}"')
    lines.append("")
    operation_docs = {
        "contains": "containing one or more given substrings",
        "prefix": "starting with one or more given prefixes",
        "suffix": "ending with one or more given suffixes",
    }
    for field in fields:
        key = field["key"]
        lines.append(f"    {key}: {filter_annotation(field)} = None")
        lines.extend(
            docstring(field_doc(field, f"Filter by `{key}`."), "    "),
        )
        for operation in field["operations"]:
            lines.append(f"    {operation['key']}: MaybeSequence[str] | None = None")
            lines.extend(
                docstring(f"Filter by `{key}` {operation_docs[operation['kind']]}.", "    ")
            )
    lines.append("")
    lines.append("")

    # Create.
    lines.append(f"class {name}Create(BaseUUIDEntityCreate, slots=True):")
    lines.append(f'    """Payload for creating a new `{name}` record."""')
    lines.append("")
    for column in columns:
        key = column["key"]
        annotation = create_annotation(column)
        default = ""
        described = defaults.get(key)
        if described and "value" in described:
            default = f" = {described['value']!r}"
        lines.append(f"    {key}: {annotation}{default}")
        lines.extend(docstring(field_doc(column, f"The {key} of the {name.lower()}."), "    "))
    lines.append("")
    lines.append("")

    # Update.
    lines.append(f"class {name}Update(TypedDict, total=False):")
    lines.append(f'    """Partial update for an existing `{name}` record."""')
    lines.append("")
    for column in columns:
        if column["key"] in fixed:
            continue
        lines.append(f"    {column['key']}: {create_annotation(column)}")
    lines.append("")

    text = "\n".join(lines)
    if "ClassVar" in text:
        text = text.replace(
            "from typing import Any, Literal, TypedDict",
            "from typing import Any, ClassVar, Literal, TypedDict",
        )

    return text.rstrip() + "\n"


def main() -> int:
    check = "--check" in sys.argv
    tables = load_tables()
    MODELS.mkdir(parents=True, exist_ok=True)
    init = MODELS / "__init__.py"
    if not init.exists() and not check:
        init.write_text(BANNER + "\n")

    rendered = {MODELS / "users.py": render_users(tables["users"])}

    failed = False
    for path, text in rendered.items():
        if check:
            if not path.is_file() or path.read_text() != text:
                print(f"{path} is out of date. Run `make models`.")
                failed = True
        else:
            path.write_text(text)
            print(f"{path}: updated")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
