// The renderer, included by the build script so it links the schema crates as build
// dependencies. See `build.rs` for the entry point.

use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use ceres_entities::{FilterValues, MessageDirection, PermissionTargetType};
use serde_json::Value;

const BANNER: &str = "# @generated by ceres-models. Run 'make models' to update.";

/// The project line width, which rendered docstrings wrap to.
const WIDTH: usize = 100;

/// One generated `StrEnum`, read from the Rust enum's `FilterValues` derive.
struct EnumSpec {
    name: &'static str,
    doc: &'static str,
    values: &'static [&'static str],
    value_docs: &'static [&'static str],
    /// Whether to render `<Name>Raw` and `<Name>Input` aliases beside the enum.
    aliases: bool,
}

/// One generated file, covering the tables its public module declares.
struct ModuleSpec {
    file: &'static str,
    /// The dump tables to render, in the order the module lays them out.
    tables: &'static [&'static str],
    enums: &'static [EnumSpec],
    /// Literal lines rendered after the enums, for supporting type aliases.
    preamble: &'static [&'static str],
    /// Names beyond the model and enum sets to list in `__all__`.
    extra_all: &'static [&'static str],
}

const MODULES: &[ModuleSpec] = &[
    ModuleSpec {
        file: "users.py",
        tables: &["users"],
        enums: &[],
        preamble: &[],
        extra_all: &[],
    },
    ModuleSpec {
        file: "settings.py",
        tables: &["settings"],
        enums: &[],
        preamble: &[],
        extra_all: &[],
    },
    ModuleSpec {
        file: "variables.py",
        tables: &["variables"],
        enums: &[],
        preamble: &[],
        extra_all: &[],
    },
    ModuleSpec {
        file: "workspaces.py",
        tables: &["workspace_edits", "workspaces"],
        enums: &[],
        preamble: &[],
        extra_all: &[],
    },
    ModuleSpec {
        file: "groups.py",
        tables: &["groups", "group_memberships"],
        enums: &[],
        preamble: &[],
        extra_all: &[],
    },
    ModuleSpec {
        file: "permissions.py",
        tables: &["user_permissions", "group_permissions"],
        enums: &[EnumSpec {
            name: PermissionTargetType::NAME,
            doc: PermissionTargetType::DOC,
            values: PermissionTargetType::VALUES,
            value_docs: PermissionTargetType::VALUE_DOCS,
            aliases: false,
        }],
        preamble: &[],
        extra_all: &[],
    },
    ModuleSpec {
        file: "alerts.py",
        tables: &["alerts"],
        enums: &[],
        preamble: &[],
        extra_all: &[],
    },
    ModuleSpec {
        file: "messages.py",
        tables: &["messages"],
        enums: &[EnumSpec {
            name: MessageDirection::NAME,
            doc: MessageDirection::DOC,
            values: MessageDirection::VALUES,
            value_docs: MessageDirection::VALUE_DOCS,
            aliases: true,
        }],
        preamble: &[
            "type MessageData = Annotated[",
            "    bytes,",
            "    BytesFromString(\"latin-1\", \"ignore\"),",
            "    BytesToString(\"latin-1\", \"ignore\"),",
            "]",
            "\"\"\"Raw message payload bytes, serialized to and from `latin-1` strings for transport.\"\"\"",
        ],
        extra_all: &["MessageData"],
    },
    ModuleSpec {
        file: "logs.py",
        tables: &["logs"],
        enums: &[],
        preamble: &[],
        extra_all: &[],
    },
];

/// Filter field annotations by family, for the families the tables use.
fn filter_type(family: &str) -> &'static str {
    match family {
        "uuid" => "MaybeSequence[UUID] | None",
        "text" => "MaybeSequence[str] | None",
        "email" => "MaybeSequence[EmailAddress] | None",
        "boolean" => "bool | None",
        "json_value" => "JSONSerializable | None",
        "plain_address" => "MaybeSequence[Address] | None",
        "level" => "MaybeSequence[Level] | None",
        other => panic!("no filter annotation for the `{other}` family"),
    }
}

/// Create and update annotations by family. JSON columns take their values as passed,
/// the CLI and HTTP edges parse text before it reaches a model.
fn create_type(family: &str) -> &'static str {
    match family {
        "uuid" => "UUID",
        "text" => "str",
        "email" => "EmailAddress",
        "boolean" => "bool",
        "json" => "JSONSerializableDict",
        "json_value" => "JSONSerializable",
        "plain_address" => "Address",
        "level" => "Level",
        other => panic!("no create annotation for the `{other}` family"),
    }
}

/// Names importable from `ceres.data`, matched against the rendered body.
const DATA_IMPORTS: &[&str] = &[
    "BytesFromString",
    "BytesToString",
    "EmailAddress",
    "FromYAML",
    "JSONSerializable",
    "JSONSerializableDict",
    "MaybeSequence",
    "Name",
    "NonEmptyStr",
    "Password",
    "PasswordHash",
    "StrEnum",
    "Username",
];

/// Names importable from `ceres.config`, matched against the rendered body.
const CONFIG_IMPORTS: &[&str] = &["ComponentAccessLevel"];

/// Base name suffixes shared by every base family.
const BASE_SUFFIXES: &[&str] = &["Create", "Field", "Filter", "FilterArgs", "Order"];

/// What a filter equality docstring calls the given values, when not the key itself.
fn filter_noun(family: &str, key: &str) -> String {
    // Keys whose plain plural reads poorly.
    if key == "content" {
        return "strings".to_string();
    }

    match family {
        "email" => "email addresses".to_string(),
        "uuid" => "UUIDs".to_string(),
        "plain_address" => "addresses".to_string(),
        "values" => "values".to_string(),
        "bytes" => "byte sequences".to_string(),
        _ => format!("{key}s"),
    }
}

fn text<'a>(value: &'a Value, key: &str) -> &'a str {
    value[key].as_str().unwrap_or_default()
}

fn family_name(field: &Value) -> &str {
    text(&field["family"], "name")
}

fn entries<'a>(value: &'a Value, key: &str) -> &'a [Value] {
    static EMPTY: &[Value] = &[];
    value[key].as_array().map_or(EMPTY, Vec::as_slice)
}

fn keys<'a>(value: &'a Value, key: &str) -> Vec<&'a str> {
    entries(value, key)
        .iter()
        .filter_map(Value::as_str)
        .collect()
}

/// Greedy wrap over whitespace-separated words, the way Python's `textwrap.fill` reads
/// the prose these docstrings hold.
fn fill(prose: &str, width: usize) -> String {
    let mut lines: Vec<String> = Vec::new();
    let mut current = String::new();
    let mut count = 0;
    for word in prose.split_whitespace() {
        let length = word.chars().count();
        if current.is_empty() {
            current.push_str(word);
            count = length;
        } else if count + 1 + length <= width {
            current.push(' ');
            current.push_str(word);
            count += 1 + length;
        } else {
            lines.push(std::mem::take(&mut current));
            current.push_str(word);
            count = length;
        }
    }

    if !current.is_empty() {
        lines.push(current);
    }

    lines.join("\n")
}

/// Render a docstring block, single-line where it fits and wrapped to width.
fn docstring(prose: &str, indent: &str) -> Vec<String> {
    let paragraphs: Vec<String> = prose
        .split("\n\n")
        .map(str::trim)
        .filter(|paragraph| !paragraph.is_empty())
        .map(|paragraph| fill(paragraph, WIDTH - indent.chars().count()))
        .collect();
    if paragraphs.is_empty() {
        return Vec::new();
    }

    if paragraphs.len() == 1 && !paragraphs[0].contains('\n') {
        let line = format!("{indent}\"\"\"{}\"\"\"", paragraphs[0]);
        if line.chars().count() <= WIDTH {
            return vec![line];
        }
    }

    let joined = paragraphs.join("\n\n");
    let mut wrapped = joined.lines();
    let mut rendered = vec![format!(
        "{indent}\"\"\"{}",
        wrapped.next().unwrap_or_default()
    )];
    for line in wrapped {
        if line.is_empty() {
            rendered.push(String::new());
        } else {
            rendered.push(format!("{indent}{line}"));
        }
    }

    rendered.push(format!("{indent}\"\"\""));
    rendered
}

/// The first paragraph of a field's doc comment.
fn field_doc(field: &Value) -> String {
    text(field, "doc")
        .split("\n\n")
        .next()
        .unwrap_or_default()
        .replace('\n', " ")
        .trim()
        .to_string()
}

/// The docstring of a filter equality field, phrased per family.
fn filter_doc(field: &Value) -> String {
    let key = text(field, "key");
    let family = family_name(field);
    match family {
        "boolean" => format!("Filter by `{key}` being either `True` or `False`."),
        "json_value" => {
            format!("Filter by `{key}` being exactly equal to the given JSON-serializable value.")
        }
        _ => format!(
            "Filter by `{key}` being equal to one or more given {}.",
            filter_noun(family, key)
        ),
    }
}

/// The filter or args annotation, parameterized by the Python type for the `values`
/// and `bytes` families. `input_form` widens `values` to the enum's input alias.
fn filter_annotation(field: &Value, input_form: &str) -> String {
    let python = text(field, "python");
    match family_name(field) {
        "values" => format!("MaybeSequence[{python}{input_form}] | None"),
        "bytes" => format!("MaybeSequence[{python}] | None"),
        family => filter_type(family).to_string(),
    }
}

/// The create and update annotation, nullable when the column defaults to null.
fn create_annotation(field: &Value, described: Option<&Value>) -> String {
    let python = text(field, "python");
    let mut annotation = if python.is_empty() {
        create_type(family_name(field)).to_string()
    } else {
        python.to_string()
    };
    if described.is_some_and(|described| described.get("value").is_some_and(Value::is_null)) {
        annotation.push_str(" | None");
    }

    annotation
}

/// Render a column default as the expression the create model carries.
fn default_expression(field: &Value, value: &Value) -> String {
    match value {
        Value::Null => "None".to_string(),
        _ if family_name(field) == "plain_address" => {
            format!("Address(\"{}\")", value.as_str().unwrap_or_default())
        }
        Value::Object(map) if map.is_empty() && family_name(field) == "json" => {
            "Field(default_factory=dict)".to_string()
        }
        Value::Bool(true) => "True".to_string(),
        Value::Bool(false) => "False".to_string(),
        Value::String(inner) => format!("\"{inner}\""),
        other => other.to_string(),
    }
}

/// The docstring of one operation key, phrased per family.
fn operation_doc(field: &Value, kind: &str) -> String {
    let key = text(field, "key");
    match family_name(field) {
        "json" => {
            let phrase = match kind {
                "contains" => "contains one or more given substrings",
                "prefix" => "starts with one or more given prefixes",
                _ => "ends with one or more given suffixes",
            };
            format!("Filter by whether or not the JSON text of `{key}` {phrase}.")
        }
        "bytes" => {
            let phrase = match kind {
                "contains" => "containing one or more given byte substrings",
                "prefix" => "starting with one or more given byte prefixes",
                _ => "ending with one or more given byte suffixes",
            };
            format!("Filter by `{key}` {phrase}.")
        }
        _ => {
            let phrase = match kind {
                "contains" => "containing one or more given substrings",
                "prefix" => "starting with one or more given prefixes",
                _ => "ending with one or more given suffixes",
            };
            format!("Filter by `{key}` {phrase}.")
        }
    }
}

/// The annotation of one operation key, byte operations taking the payload type.
fn operation_annotation(field: &Value) -> String {
    if family_name(field) == "bytes" {
        format!("MaybeSequence[{}] | None", text(field, "python"))
    } else {
        "MaybeSequence[str] | None".to_string()
    }
}

/// The base class family the table's key selects.
fn base_of(table: &Value) -> (&'static str, Vec<&'static str>) {
    if text(table, "kind") == "record" {
        return ("BaseRecord", vec!["id", "address", "timestamp"]);
    }

    let key = keys(table, "key");
    if key == ["id"] {
        ("BaseUUIDEntity", vec!["id"])
    } else if key.contains(&"address") {
        ("BaseAddressEntity", vec!["address"])
    } else {
        ("BaseEntity", Vec::new())
    }
}

/// Render one table's literals, filters, and operation models.
fn render_entity(table: &Value, aliased: &[&str]) -> Vec<String> {
    let name = text(table, "entity");
    let (base, base_keys) = base_of(table);
    let plain = base == "BaseEntity";

    let selectable = |field: &Value| {
        let key = text(field, "key");
        !base_keys.contains(&key) && !field["hidden"].as_bool().unwrap_or_default()
    };
    let input_form = |field: &Value| {
        if aliased.contains(&text(field, "python")) {
            "Input"
        } else {
            ""
        }
    };

    let columns: Vec<&Value> = entries(table, "columns")
        .iter()
        .filter(|column| !base_keys.contains(&text(column, "key")))
        .collect();
    let literals: Vec<&str> = entries(table, "columns")
        .iter()
        .filter(|column| selectable(column))
        .map(|column| text(column, "key"))
        .collect();
    // Ordering resolves over the filterable fields, so a skipped column is selectable
    // but never orderable, and ordering by JSON text is not advertised.
    let orderable: Vec<&str> = entries(table, "fields")
        .iter()
        .filter(|field| selectable(field) && family_name(field) != "json")
        .map(|field| text(field, "key"))
        .collect();
    let fields: Vec<&Value> = entries(table, "fields")
        .iter()
        .filter(|field| !base_keys.contains(&text(field, "key")))
        .collect();
    let regular: Vec<&&Value> = fields
        .iter()
        .filter(|field| family_name(field) != "json_value")
        .collect();
    let nullable: Vec<&&Value> = fields
        .iter()
        .filter(|field| family_name(field) == "json_value")
        .collect();
    let fixed = keys(table, "fixed");
    let defaults = &table["defaults"];
    let mut lines: Vec<String> = Vec::new();

    // Field and order literals.
    let literal = |lines: &mut Vec<String>, alias: &str, keys: &[&str], suffixes: &[&str]| {
        if !plain {
            lines.push(format!("type {name}{alias} = ("));
            lines.push(format!("    {base}{alias}"));
            lines.push("    | Literal[".to_string());
            for key in keys {
                for suffix in suffixes {
                    lines.push(format!("        \"{key}{suffix}\","));
                }
            }
            lines.push("    ]".to_string());
            lines.push(")".to_string());
        } else {
            lines.push(format!("type {name}{alias} = Literal["));
            for key in keys {
                for suffix in suffixes {
                    lines.push(format!("    \"{key}{suffix}\","));
                }
            }
            lines.push("]".to_string());
        }
    };

    literal(&mut lines, "Field", &literals, &[""]);
    lines.push(format!(
        "\"\"\"Field names selectable in `{name}` queries.\"\"\""
    ));
    lines.push(String::new());
    literal(&mut lines, "Order", &orderable, &["", ":asc", ":desc"]);
    lines.push(format!(
        "\"\"\"Ordering keys accepted by `{name}` queries.\"\"\""
    ));
    lines.push(String::new());
    lines.push(String::new());

    // FilterArgs.
    lines.push(format!(
        "class {name}FilterArgs({base}FilterArgs[{name}Field, {name}Order], total=False):"
    ));
    lines.push(format!(
        "    \"\"\"Keyword-argument form of `{name}Filter` for ergonomic call sites.\"\"\""
    ));
    lines.push(String::new());
    for field in &regular {
        let key = text(field, "key");
        let family = family_name(field);
        if family != "json" {
            lines.push(format!(
                "    {key}: {}",
                filter_annotation(field, input_form(field))
            ));
        }
        if family == "level" {
            lines.push(format!("    min_{key}: Level | None"));
            lines.push(format!("    max_{key}: Level | None"));
        }
        for operation in entries(field, "operations") {
            lines.push(format!(
                "    {}: {}",
                text(operation, "key"),
                operation_annotation(field)
            ));
        }
    }
    for computed in entries(table, "computed") {
        lines.push(format!("    {}: bool | None", text(computed, "key")));
    }
    for field in &nullable {
        lines.push(format!(
            "    {}: {}",
            text(field, "key"),
            filter_annotation(field, "")
        ));
    }
    lines.push(String::new());
    lines.push(String::new());

    // Filter.
    lines.push(format!(
        "class {name}Filter({base}Filter[\"{name}\", {name}Field, {name}Order]):"
    ));
    lines.push(format!(
        "    \"\"\"Filter for selecting `{name}` records.\"\"\""
    ));
    lines.push(String::new());
    lines.push(format!(
        "    __table__: ClassVar[str] = \"{}\"",
        text(table, "name")
    ));
    lines.push(String::new());
    for field in &regular {
        let key = text(field, "key");
        let family = family_name(field);
        if family != "json" {
            lines.push(format!(
                "    {key}: {} = None",
                filter_annotation(field, "")
            ));
            lines.extend(docstring(&filter_doc(field), "    "));
        }
        if family == "level" {
            lines.push(format!("    min_{key}: Level | None = None"));
            lines.extend(docstring(
                &format!("Filter by `{key}` being greater than or equal to the given level value."),
                "    ",
            ));
            lines.push(format!("    max_{key}: Level | None = None"));
            lines.extend(docstring(
                &format!("Filter by `{key}` being less than or equal to the given level value."),
                "    ",
            ));
        }
        for operation in entries(field, "operations") {
            lines.push(format!(
                "    {}: {} = None",
                text(operation, "key"),
                operation_annotation(field)
            ));
            lines.extend(docstring(
                &operation_doc(field, text(operation, "kind")),
                "    ",
            ));
        }
    }
    for computed in entries(table, "computed") {
        lines.push(format!("    {}: bool | None = None", text(computed, "key")));
        lines.extend(docstring(text(computed, "doc"), "    "));
    }
    if !nullable.is_empty() {
        let named: Vec<String> = nullable
            .iter()
            .map(|field| format!("\"{}\"", text(field, "key")))
            .collect();
        let named = named.join(", ");
        lines.push(format!(
            "    __nullable_filters__: ClassVar[frozenset[str]] = frozenset({{{named}}})"
        ));
        lines.push(format!(
            "    __yaml_filters__: ClassVar[frozenset[str]] = frozenset({{{named}}})"
        ));
        lines.push(String::new());
        for field in &nullable {
            lines.push(format!(
                "    {}: {} = None",
                text(field, "key"),
                filter_annotation(field, "")
            ));
            lines.extend(docstring(&filter_doc(field), "    "));
        }
    }
    lines.push(String::new());
    lines.push(String::new());

    // Create.
    lines.push(format!("class {name}Create({base}Create, slots=True):"));
    lines.push(format!(
        "    \"\"\"Payload for creating a new `{name}` record.\"\"\""
    ));
    lines.push(String::new());
    for column in &columns {
        let key = text(column, "key");
        let described = defaults.get(key);
        let default = match described.and_then(|described| described.get("value")) {
            Some(value) => format!(" = {}", default_expression(column, value)),
            None => String::new(),
        };
        lines.push(format!(
            "    {key}: {}{default}",
            create_annotation(column, described)
        ));
        lines.extend(docstring(&field_doc(column), "    "));
    }
    lines.push(String::new());
    lines.push(String::new());

    // Update.
    let settable: Vec<&&Value> = columns
        .iter()
        .filter(|column| !fixed.contains(&text(column, "key")))
        .collect();
    let mut update_doc = format!("Partial update for an existing `{name}` record.");
    if settable.is_empty() {
        update_doc.push_str(
            "\n\nThe record is only created or deleted, so this update payload has no \
             mutable fields.",
        );
    }
    let update_base = if text(table, "kind") == "record" {
        "BaseRecordUpdate"
    } else {
        "TypedDict"
    };
    lines.push(format!("class {name}Update({update_base}, total=False):"));
    lines.extend(docstring(&update_doc, "    "));
    if !settable.is_empty() {
        lines.push(String::new());
    }
    for column in settable {
        lines.push(format!(
            "    {}: {}",
            text(column, "key"),
            create_annotation(column, defaults.get(text(column, "key")))
        ));
    }

    lines
}

/// Render one generated `StrEnum` from its Rust enum's `FilterValues` derive.
fn render_enum(spec: &EnumSpec) -> Vec<String> {
    let mut lines = vec![format!("class {}(StrEnum):", spec.name)];
    lines.extend(docstring(spec.doc, "    "));
    lines.push(String::new());
    for (index, value) in spec.values.iter().enumerate() {
        lines.push(format!("    {} = \"{value}\"", value.to_uppercase()));
        if let Some(doc) = spec.value_docs.get(index).filter(|doc| !doc.is_empty()) {
            lines.extend(docstring(doc, "    "));
        }
    }

    if spec.aliases {
        let quoted: Vec<String> = spec
            .values
            .iter()
            .map(|value| format!("\"{value}\""))
            .collect();
        let name = spec.name;
        lines.push(String::new());
        lines.push(String::new());
        lines.push(format!("type {name}Raw = Literal[{}]", quoted.join(", ")));
        lines.push(format!(
            "\"\"\"Raw string form of `{name}` accepted as input.\"\"\""
        ));
        lines.push(String::new());
        lines.push(format!("type {name}Input = {name} | {name}Raw"));
        lines.push(format!(
            "\"\"\"Either a `{name}` enum or its raw string form.\"\"\""
        ));
    }

    lines
}

/// The body with docstring lines removed, so prose never matches an import scan.
fn code_only(body: &str) -> String {
    let mut kept: Vec<&str> = Vec::new();
    let mut inside = false;
    for line in body.lines() {
        let stripped = line.trim();
        if !inside && stripped.starts_with("\"\"\"") {
            inside = !(stripped.len() > 3 && stripped.ends_with("\"\"\""));
            continue;
        }

        if inside {
            inside = !stripped.ends_with("\"\"\"");
            continue;
        }

        kept.push(line);
    }

    kept.join("\n")
}

/// Whether the code references the symbol as a whole word.
fn used(code: &str, symbol: &str) -> bool {
    let is_word = |byte: u8| byte == b'_' || byte.is_ascii_alphanumeric();
    let bytes = code.as_bytes();
    let mut start = 0;
    while let Some(position) = code[start..].find(symbol) {
        let begin = start + position;
        let end = begin + symbol.len();
        let clear_before = begin == 0 || !is_word(bytes[begin - 1]);
        let clear_after = end == bytes.len() || !is_word(bytes[end]);
        if clear_before && clear_after {
            return true;
        }

        start = begin + 1;
    }

    false
}

/// The module docstring and imports, derived from what the body references.
fn header(module: &ModuleSpec, tables: &[&Value], body: &str) -> Vec<String> {
    let code = code_only(body);
    let used = |symbol: &str| used(&code, symbol);

    let typing: Vec<&str> = ["Annotated", "Any", "ClassVar", "Literal", "TypedDict"]
        .into_iter()
        .filter(|symbol| used(symbol))
        .collect();
    let mut entity: Vec<String> = ["BaseUUIDEntity", "BaseAddressEntity", "BaseEntity"]
        .into_iter()
        .flat_map(|family| {
            BASE_SUFFIXES
                .iter()
                .map(move |suffix| format!("{family}{suffix}"))
        })
        .filter(|base| used(base))
        .collect();
    entity.sort();
    let mut record: Vec<String> = ["Create", "Field", "Filter", "FilterArgs", "Order", "Update"]
        .into_iter()
        .map(|suffix| format!("BaseRecord{suffix}"))
        .filter(|base| used(base))
        .collect();
    record.sort();
    let data: Vec<&str> = DATA_IMPORTS
        .iter()
        .copied()
        .filter(|symbol| used(symbol))
        .collect();
    let config: Vec<&str> = CONFIG_IMPORTS
        .iter()
        .copied()
        .filter(|symbol| used(symbol))
        .collect();
    let described: Vec<String> = tables
        .iter()
        .map(|table| format!("`{}`", text(table, "name")))
        .collect();
    let mut names: Vec<&str> = tables.iter().map(|table| text(table, "entity")).collect();
    names.sort_unstable();
    let source = text(tables[0], "python_module");

    let mut lines = vec![
        BANNER.to_string(),
        String::new(),
        format!(
            "\"\"\"Generated models for the {} table{}.\"\"\"",
            described.join(", "),
            if tables.len() > 1 { "s" } else { "" }
        ),
        String::new(),
        format!("from typing import TYPE_CHECKING, {}", typing.join(", ")),
    ];
    if used("UUID") {
        lines.push("from uuid import UUID".to_string());
    }
    lines.push(String::new());
    if code.contains("Field(") {
        lines.push("from pydantic import Field".to_string());
        lines.push(String::new());
    }
    if !entity.is_empty() {
        lines.push("from ceres.__internal__.entity import (".to_string());
        lines.extend(entity.iter().map(|symbol| format!("    {symbol},")));
        lines.push(")".to_string());
    }
    if !record.is_empty() {
        lines.push("from ceres.__internal__.record import (".to_string());
        lines.extend(record.iter().map(|symbol| format!("    {symbol},")));
        lines.push(")".to_string());
    }
    if used("Address") {
        lines.push("from ceres.address import Address".to_string());
    }
    if !config.is_empty() {
        lines.push(format!("from ceres.config import {}", config.join(", ")));
    }
    if !data.is_empty() {
        lines.push("from ceres.data import (".to_string());
        lines.extend(data.iter().map(|symbol| format!("    {symbol},")));
        lines.push(")".to_string());
    }
    if used("Level") {
        lines.push("from ceres.level import Level".to_string());
    }
    lines.extend([
        String::new(),
        "if TYPE_CHECKING:".to_string(),
        "    # The filters name them only as forward references.".to_string(),
        format!(
            "    from {source} import {}  # noqa: F401",
            names.join(", ")
        ),
        String::new(),
        "__all__ = [".to_string(),
    ]);
    let mut exported: Vec<String> = tables
        .iter()
        .flat_map(|table| {
            let name = text(table, "entity");
            ["Create", "Field", "Filter", "FilterArgs", "Order", "Update"]
                .into_iter()
                .map(move |suffix| format!("{name}{suffix}"))
        })
        .chain(module.enums.iter().map(|spec| spec.name.to_string()))
        .chain(
            module
                .enums
                .iter()
                .filter(|spec| spec.aliases)
                .flat_map(|spec| {
                    ["Input", "Raw"]
                        .into_iter()
                        .map(move |alias| format!("{}{alias}", spec.name))
                }),
        )
        .chain(module.extra_all.iter().map(ToString::to_string))
        .collect();
    exported.sort();
    lines.extend(exported.iter().map(|name| format!("    \"{name}\",")));
    lines.extend(["]".to_string(), String::new(), String::new()]);
    lines
}

/// Reassign the models to the public module, which re-exports them.
///
/// Reprs, pickling, and rendered documentation then name the public path rather than
/// this package. The `type` aliases stay put, `TypeAliasType.__module__` is read-only.
fn footer(module: &ModuleSpec, tables: &[&Value]) -> Vec<String> {
    let models: Vec<String> = module
        .enums
        .iter()
        .map(|spec| spec.name.to_string())
        .chain(tables.iter().flat_map(|table| {
            let name = text(table, "entity");
            ["Create", "Filter", "FilterArgs", "Update"]
                .into_iter()
                .map(move |suffix| format!("{name}{suffix}"))
        }))
        .collect();
    vec![
        String::new(),
        String::new(),
        "# Present the models as part of the public module that re-exports them.".to_string(),
        format!("for _model in ({}):", models.join(", ")),
        format!(
            "    _model.__module__ = \"{}\"",
            text(tables[0], "python_module")
        ),
    ]
}

/// Canonicalize with the project's ruff, which wraps wide class headers.
///
/// Ruff is looked up beside the repository's own environment first, the way the stub
/// generator finds it, so the render matches what `make lint` checks.
fn formatted(root: &Path, name: &str, source: &str) -> String {
    let venv_ruff = root.join(".venv/bin/ruff");
    let ruff = if venv_ruff.is_file() {
        venv_ruff
    } else {
        PathBuf::from("ruff")
    };

    // The stdin filename carries the real path so ruff discovers the project
    // configuration, the line width included, regardless of the working directory.
    let path = root.join("ceres/__internal__/models").join(name);
    let mut child = Command::new(&ruff)
        .args(["format", "--stdin-filename"])
        .arg(&path)
        .arg("-")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .expect("the project ruff runs");
    std::io::Write::write_all(
        &mut child.stdin.take().expect("a piped stdin"),
        source.as_bytes(),
    )
    .expect("the source pipes to ruff");
    let output = child.wait_with_output().expect("ruff finishes");
    assert!(output.status.success(), "ruff format refused {name}");
    String::from_utf8(output.stdout).expect("ruff emits UTF-8")
}

/// Whether the project's ruff is reachable, without which the render must not write.
///
/// An unformatted module would read as drift against the committed one, so a build
/// with no ruff keeps the committed modules and warns instead.
fn ruff_available(root: &Path) -> bool {
    if root.join(".venv/bin/ruff").is_file() {
        return true;
    }

    Command::new("ruff")
        .arg("--version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok_and(|status| status.success())
}

fn render_module(root: &Path, module: &ModuleSpec, dump: &Value) -> String {
    let all = entries(dump, "tables");
    let tables: Vec<&Value> = module
        .tables
        .iter()
        .map(|name| {
            all.iter()
                .find(|table| text(table, "name") == *name)
                .unwrap_or_else(|| panic!("the dump carries a `{name}` table"))
        })
        .collect();
    let aliased: Vec<&str> = module
        .enums
        .iter()
        .filter(|spec| spec.aliases)
        .map(|spec| spec.name)
        .collect();

    let mut bodies: Vec<Vec<String>> = module.enums.iter().map(render_enum).collect();
    if !module.preamble.is_empty() {
        bodies.push(module.preamble.iter().map(ToString::to_string).collect());
    }
    bodies.extend(tables.iter().map(|table| render_entity(table, &aliased)));
    let body = bodies
        .iter()
        .map(|lines| lines.join("\n").trim_end().to_string())
        .collect::<Vec<_>>()
        .join("\n\n\n");

    let mut source = header(module, &tables, &body).join("\n");
    source.push('\n');
    source.push_str(&body);
    let mut source = source.trim_end().to_string();
    source.push('\n');
    source.push_str(&footer(module, &tables).join("\n"));
    source.push('\n');
    formatted(root, module.file, &source)
}

/// Render every model module into the package, skipping when ruff is unreachable.
fn generate(root: &Path) {
    if !ruff_available(root) {
        println!(
            "cargo::warning=ruff is unavailable, keeping the committed model modules; \
             regenerate with `make models` once the environment is installed"
        );
        return;
    }

    let models = root.join("ceres/__internal__/models");
    std::fs::create_dir_all(&models).expect("the models directory exists");
    let dump = ceres_database::describe::tables();

    let init = models.join("__init__.py");
    if !init.is_file() {
        std::fs::write(&init, format!("{BANNER}\n")).expect("the package init writes");
    }

    for module in MODULES {
        let path = models.join(module.file);
        let rendered = render_module(root, module, &dump);
        std::fs::write(&path, rendered).expect("the module writes");
    }
}
