const icons = {
  add: 'add',
  arrowDown: 'arrow_drop_down',
  arrowLeft: 'arrow_left',
  arrowRight: 'arrow_right',
  arrowUp: 'arrow_drop_up',
  arrowBack: 'arrow_back',
  arrowDownward: 'arrow_downward',
  arrowForward: 'arrow_forward',
  arrowUpward: 'arrow_upward',
  cancel: 'cancel',
  chevronLeft: 'chevron_left',
  chevronRight: 'chevron_right',
  circle: 'circle',
  clearLocalStorage: 'delete_sweep',
  close: 'close',
  connection: 'route',
  darkMode: 'dark_mode',
  dashboard: 'space_dashboard',
  delete: 'delete',
  help: 'help',
  job: 'build',
  json: 'data_object',
  lightMode: 'light_mode',
  menu: 'menu',
  radioChecked: 'radio_button_checked',
  radioUnchecked: 'radio_button_unchecked',
  remove: 'remove',
  reset: 'refresh',
  script: 'code',
  search: 'search',
  send: 'send',
  settings: 'settings',
  switchLeft: 'switch_left',
  switchRight: 'switch_right',
  tools: 'construction',
  unit: 'fiber_manual_record',
  units: 'workspaces',
  user: 'person',
} as const

export default icons
