name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
      - name: Install
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Build
        run: make build
      - name: Ensure Generated Files Match
        run: git diff --exit-code
