# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import os
import pathlib
import typing

__all__ = [
    "ConsoleConfig",
    "LoggingConfig",
    "ServerAuthenticationConfig",
    "ServerCORSConfig",
    "ServerCompressionConfig",
    "ServerConfig",
    "ServerSSLConfig",
    "ServiceConfig",
]

class ConsoleConfig:
    r"""
    Branding and layout options for the engine's web console.
    """
    @property
    def title(self) -> builtins.str | None:
        r"""
        Title shown in the console's browser tab and header.
        """
    @property
    def favicon(self) -> pathlib.Path | None:
        r"""
        Path to a favicon image served by the console.
        """
    def __new__(
        cls,
        *,
        title: builtins.str | None = None,
        favicon: builtins.str | os.PathLike | pathlib.Path | None = None,
    ) -> ConsoleConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class LoggingConfig:
    r"""
    Per-component or per-engine logging configuration.

    `output` and `store` set minimum levels for the streamed and persisted log streams, and
    the toggle fields enable optional logging of specific record types, accepting either a
    boolean or a minimum level.
    """
    @property
    def output(self) -> builtins.str:
        r"""
        Minimum severity that reaches the engine's streamed log output.
        """
    @property
    def store(self) -> builtins.str:
        r"""
        Minimum severity persisted to the engine's log store.
        """
    @property
    def events(self) -> bool | str:
        r"""
        Whether to log events, or the minimum severity to log them at.
        """
    @property
    def messages(self) -> bool | str:
        r"""
        Whether to log raw connection messages, or the minimum severity to log them at.
        """
    @property
    def particles(self) -> bool | str:
        r"""
        Whether to log parsed particles, or the minimum severity to log them at.
        """
    @property
    def alerts(self) -> bool | str:
        r"""
        Whether to log alerts, or the minimum severity to log them at.
        """
    def __new__(
        cls,
        *,
        output: builtins.str | None = None,
        store: builtins.str | None = None,
        events: builtins.bool | str | None = None,
        messages: builtins.bool | str | None = None,
        particles: builtins.bool | str | None = None,
        alerts: builtins.bool | str | None = None,
    ) -> LoggingConfig: ...
    def merged(self, other: LoggingConfig) -> LoggingConfig:
        r"""
        Overlay another configuration's explicitly-set fields onto this one.
        """
    def provided(self) -> dict[str, typing.Any]:
        r"""
        Return the explicitly-set fields as a plain dictionary.

        Supports rebuilding an equivalent configuration without turning resolved defaults
        into explicit settings.
        """
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServerAuthenticationConfig:
    r"""
    Authentication settings for the engine's HTTP server.
    """
    @property
    def secret(self) -> builtins.str:
        r"""
        Secret used to sign and verify authentication tokens.
        """
    @property
    def duration(self) -> datetime.timedelta:
        r"""
        Lifetime of an issued authentication token.
        """
    @property
    def allow_impersonate(self) -> builtins.bool:
        r"""
        Whether an administrator may take on another user's identity without their password.
        """
    def __new__(
        cls,
        *,
        secret: builtins.str | None = None,
        duration: datetime.timedelta | int | float | str | None = None,
        allow_impersonate: builtins.bool | None = None,
    ) -> ServerAuthenticationConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServerCORSConfig:
    r"""
    Cross-origin resource sharing settings for the engine's HTTP server.
    """
    @property
    def enabled(self) -> builtins.bool:
        r"""
        Whether cross-origin resource sharing is enabled.
        """
    @property
    def allow_origins(self) -> str | list[str]:
        r"""
        Origins allowed to make cross-origin requests.
        """
    @property
    def allow_origin_regex(self) -> builtins.str | None:
        r"""
        Pattern matching additional allowed origins.
        """
    @property
    def allow_methods(self) -> str | list[str]:
        r"""
        Methods allowed for cross-origin requests.
        """
    @property
    def allow_headers(self) -> str | list[str]:
        r"""
        Headers allowed in cross-origin requests.
        """
    @property
    def allow_credentials(self) -> builtins.bool:
        r"""
        Whether credentialed cross-origin requests are allowed.
        """
    @property
    def expose_headers(self) -> str | list[str]:
        r"""
        Headers exposed to cross-origin callers.
        """
    @property
    def max_age(self) -> builtins.int:
        r"""
        How long preflight responses may be cached, in seconds.
        """
    def __new__(
        cls,
        *,
        enabled: builtins.bool | None = None,
        allow_origins: typing.Any | None = None,
        allow_origin_regex: builtins.str | None = None,
        allow_methods: typing.Any | None = None,
        allow_headers: typing.Any | None = None,
        allow_credentials: builtins.bool | None = None,
        expose_headers: typing.Any | None = None,
        max_age: builtins.int | None = None,
    ) -> ServerCORSConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServerCompressionConfig:
    r"""
    Response compression settings for the engine's HTTP server.
    """
    @property
    def enabled(self) -> builtins.bool:
        r"""
        Whether response compression is enabled.
        """
    @property
    def min_size(self) -> builtins.int:
        r"""
        Minimum response size in bytes before compression is applied.
        """
    @property
    def zstd(self) -> builtins.bool:
        r"""
        Whether zstd compression is offered.
        """
    @property
    def zstd_level(self) -> builtins.int:
        r"""
        Zstd compression level.
        """
    @property
    def brotli(self) -> builtins.bool:
        r"""
        Whether brotli compression is offered.
        """
    @property
    def brotli_quality(self) -> builtins.int:
        r"""
        Brotli compression quality.
        """
    @property
    def gzip(self) -> builtins.bool:
        r"""
        Whether gzip compression is offered.
        """
    @property
    def gzip_level(self) -> builtins.int:
        r"""
        Gzip compression level.
        """
    def __new__(
        cls,
        *,
        enabled: builtins.bool | None = None,
        min_size: builtins.int | str | None = None,
        zstd: builtins.bool | None = None,
        zstd_level: builtins.int | None = None,
        brotli: builtins.bool | None = None,
        brotli_quality: builtins.int | None = None,
        gzip: builtins.bool | None = None,
        gzip_level: builtins.int | None = None,
    ) -> ServerCompressionConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServerConfig:
    r"""
    Configuration for the engine's HTTP server.
    """
    @property
    def host(self) -> builtins.str:
        r"""
        Address the server binds to.
        """
    @property
    def port(self) -> builtins.int | None:
        r"""
        Port the server listens on, omit to disable the server.
        """
    @property
    def ssl(self) -> ServerSSLConfig | None:
        r"""
        TLS settings, omit to serve plain HTTP.
        """
    @property
    def authentication(self) -> ServerAuthenticationConfig | None:
        r"""
        Authentication settings, omit to disable authentication.
        """
    @property
    def cors(self) -> ServerCORSConfig | None:
        r"""
        Cross-origin resource sharing settings.
        """
    @property
    def compression(self) -> ServerCompressionConfig | None:
        r"""
        Response compression settings.
        """
    def __new__(
        cls,
        *,
        host: builtins.str | None = None,
        port: builtins.int | None = None,
        ssl: builtins.ServerSSLConfig | dict[str, typing.Any] | None = None,
        authentication: builtins.ServerAuthenticationConfig | dict[str, typing.Any] | None = None,
        cors: builtins.ServerCORSConfig | dict[str, typing.Any] | None = None,
        compression: builtins.ServerCompressionConfig | dict[str, typing.Any] | None = None,
    ) -> ServerConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServerSSLConfig:
    r"""
    TLS configuration for the engine's HTTP server.
    """
    @property
    def key(self) -> pathlib.Path | None:
        r"""
        Path to the server private key file.
        """
    @property
    def key_password(self) -> builtins.str | None:
        r"""
        Password for an encrypted private key.
        """
    @property
    def cert(self) -> pathlib.Path | None:
        r"""
        Path to the server certificate file.
        """
    @property
    def version(self) -> builtins.int | None:
        r"""
        `ssl` protocol constant selecting the TLS version.
        """
    @property
    def ca_certs(self) -> pathlib.Path | None:
        r"""
        Path to a CA bundle used when validating client certificates.
        """
    def __new__(
        cls,
        *,
        key: builtins.str | os.PathLike | pathlib.Path | None = None,
        key_password: builtins.str | None = None,
        cert: builtins.str | os.PathLike | pathlib.Path | None = None,
        version: builtins.int | None = None,
        ca_certs: builtins.str | os.PathLike | pathlib.Path | None = None,
    ) -> ServerSSLConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServiceConfig:
    r"""
    Process-level options applied when running the engine as a system service.
    """
    @property
    def name(self) -> builtins.str | None:
        r"""
        Service name registered with the operating system.
        """
    @property
    def user(self) -> builtins.str | None:
        r"""
        User the service runs as.
        """
    @property
    def stdout(self) -> pathlib.Path | None:
        r"""
        Optional path to redirect standard output to.
        """
    @property
    def stderr(self) -> pathlib.Path | None:
        r"""
        Optional path to redirect standard error to.
        """
    def __new__(
        cls,
        *,
        name: builtins.str | None = None,
        user: builtins.str | None = None,
        stdout: builtins.str | os.PathLike | pathlib.Path | None = None,
        stderr: builtins.str | os.PathLike | pathlib.Path | None = None,
    ) -> ServiceConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.

        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.

        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...
