# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import os
import pathlib
import typing
__all__ = [
    "ConsoleConfig",
    "LoggingConfig",
    "ServerAuthenticationConfig",
    "ServerCORSConfig",
    "ServerCompressionConfig",
    "ServerConfig",
    "ServerSSLConfig",
    "ServiceConfig",
]

class ConsoleConfig:
    r"""
    Branding and layout options for the engine's web console.
    """
    @property
    def title(self) -> typing.Optional[builtins.str]:
        r"""
        Title shown in the console's browser tab and header.
        """
    @property
    def favicon(self) -> typing.Optional[pathlib.Path]:
        r"""
        Path to a favicon image served by the console.
        """
    def __new__(cls, *, title: typing.Optional[builtins.str] = None, favicon: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None) -> ConsoleConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.
        
        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.
        
        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class LoggingConfig:
    r"""
    Per-component or per-engine logging configuration.
    
    `output` and `store` set minimum levels for the streamed and persisted log streams, and
    the toggle fields enable optional logging of specific record types, accepting either a
    boolean or a minimum level.
    """
    @property
    def output(self) -> builtins.str:
        r"""
        Minimum severity that reaches the engine's streamed log output.
        """
    @property
    def store(self) -> builtins.str:
        r"""
        Minimum severity persisted to the engine's log store.
        """
    @property
    def events(self) -> bool | str:
        r"""
        Whether to log events, or the minimum severity to log them at.
        """
    @property
    def messages(self) -> bool | str:
        r"""
        Whether to log raw connection messages, or the minimum severity to log them at.
        """
    @property
    def particles(self) -> bool | str:
        r"""
        Whether to log parsed particles, or the minimum severity to log them at.
        """
    @property
    def alerts(self) -> bool | str:
        r"""
        Whether to log alerts, or the minimum severity to log them at.
        """
    def __new__(cls, *, output: typing.Optional[builtins.str] = None, store: typing.Optional[builtins.str] = None, events: typing.Optional[builtins.bool | str] = None, messages: typing.Optional[builtins.bool | str] = None, particles: typing.Optional[builtins.bool | str] = None, alerts: typing.Optional[builtins.bool | str] = None) -> LoggingConfig: ...
    def merged(self, other: LoggingConfig) -> LoggingConfig:
        r"""
        Overlay another configuration's explicitly-set fields onto this one.
        """
    def provided(self) -> dict[str, typing.Any]:
        r"""
        Return the explicitly-set fields as a plain dictionary.
        
        Supports rebuilding an equivalent configuration without turning resolved defaults
        into explicit settings.
        """
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.
        
        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.
        
        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServerAuthenticationConfig:
    r"""
    Authentication settings for the engine's HTTP server.
    """
    @property
    def secret(self) -> builtins.str:
        r"""
        Secret used to sign and verify authentication tokens.
        """
    @property
    def duration(self) -> datetime.timedelta:
        r"""
        Lifetime of an issued authentication token.
        """
    @property
    def allow_impersonate(self) -> builtins.bool:
        r"""
        Whether an administrator may take on another user's identity without their password.
        """
    def __new__(cls, *, secret: typing.Optional[builtins.str] = None, duration: typing.Optional[datetime.timedelta  |  int  |  float  |  str] = None, allow_impersonate: typing.Optional[builtins.bool] = None) -> ServerAuthenticationConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.
        
        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.
        
        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServerCORSConfig:
    r"""
    Cross-origin resource sharing settings for the engine's HTTP server.
    """
    @property
    def enabled(self) -> builtins.bool:
        r"""
        Whether cross-origin resource sharing is enabled.
        """
    @property
    def allow_origins(self) -> str | list[str]:
        r"""
        Origins allowed to make cross-origin requests.
        """
    @property
    def allow_origin_regex(self) -> typing.Optional[builtins.str]:
        r"""
        Pattern matching additional allowed origins.
        """
    @property
    def allow_methods(self) -> str | list[str]:
        r"""
        Methods allowed for cross-origin requests.
        """
    @property
    def allow_headers(self) -> str | list[str]:
        r"""
        Headers allowed in cross-origin requests.
        """
    @property
    def allow_credentials(self) -> builtins.bool:
        r"""
        Whether credentialed cross-origin requests are allowed.
        """
    @property
    def expose_headers(self) -> str | list[str]:
        r"""
        Headers exposed to cross-origin callers.
        """
    @property
    def max_age(self) -> builtins.int:
        r"""
        How long preflight responses may be cached, in seconds.
        """
    def __new__(cls, *, enabled: typing.Optional[builtins.bool] = None, allow_origins: typing.Optional[typing.Any] = None, allow_origin_regex: typing.Optional[builtins.str] = None, allow_methods: typing.Optional[typing.Any] = None, allow_headers: typing.Optional[typing.Any] = None, allow_credentials: typing.Optional[builtins.bool] = None, expose_headers: typing.Optional[typing.Any] = None, max_age: typing.Optional[builtins.int] = None) -> ServerCORSConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.
        
        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.
        
        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServerCompressionConfig:
    r"""
    Response compression settings for the engine's HTTP server.
    """
    @property
    def enabled(self) -> builtins.bool:
        r"""
        Whether response compression is enabled.
        """
    @property
    def min_size(self) -> builtins.int:
        r"""
        Minimum response size in bytes before compression is applied.
        """
    @property
    def zstd(self) -> builtins.bool:
        r"""
        Whether zstd compression is offered.
        """
    @property
    def zstd_level(self) -> builtins.int:
        r"""
        Zstd compression level.
        """
    @property
    def brotli(self) -> builtins.bool:
        r"""
        Whether brotli compression is offered.
        """
    @property
    def brotli_quality(self) -> builtins.int:
        r"""
        Brotli compression quality.
        """
    @property
    def gzip(self) -> builtins.bool:
        r"""
        Whether gzip compression is offered.
        """
    @property
    def gzip_level(self) -> builtins.int:
        r"""
        Gzip compression level.
        """
    def __new__(cls, *, enabled: typing.Optional[builtins.bool] = None, min_size: typing.Optional[builtins.int | str] = None, zstd: typing.Optional[builtins.bool] = None, zstd_level: typing.Optional[builtins.int] = None, brotli: typing.Optional[builtins.bool] = None, brotli_quality: typing.Optional[builtins.int] = None, gzip: typing.Optional[builtins.bool] = None, gzip_level: typing.Optional[builtins.int] = None) -> ServerCompressionConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.
        
        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.
        
        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServerConfig:
    r"""
    Configuration for the engine's HTTP server.
    """
    @property
    def host(self) -> builtins.str:
        r"""
        Address the server binds to.
        """
    @property
    def port(self) -> typing.Optional[builtins.int]:
        r"""
        Port the server listens on, omit to disable the server.
        """
    @property
    def ssl(self) -> typing.Optional[ServerSSLConfig]:
        r"""
        TLS settings, omit to serve plain HTTP.
        """
    @property
    def authentication(self) -> typing.Optional[ServerAuthenticationConfig]:
        r"""
        Authentication settings, omit to disable authentication.
        """
    @property
    def cors(self) -> typing.Optional[ServerCORSConfig]:
        r"""
        Cross-origin resource sharing settings.
        """
    @property
    def compression(self) -> typing.Optional[ServerCompressionConfig]:
        r"""
        Response compression settings.
        """
    def __new__(cls, *, host: typing.Optional[builtins.str] = None, port: typing.Optional[builtins.int] = None, ssl: typing.Optional[builtins.ServerSSLConfig | dict[str, typing.Any]] = None, authentication: typing.Optional[builtins.ServerAuthenticationConfig | dict[str, typing.Any]] = None, cors: typing.Optional[builtins.ServerCORSConfig | dict[str, typing.Any]] = None, compression: typing.Optional[builtins.ServerCompressionConfig | dict[str, typing.Any]] = None) -> ServerConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.
        
        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.
        
        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServerSSLConfig:
    r"""
    TLS configuration for the engine's HTTP server.
    """
    @property
    def key(self) -> typing.Optional[pathlib.Path]:
        r"""
        Path to the server private key file.
        """
    @property
    def key_password(self) -> typing.Optional[builtins.str]:
        r"""
        Password for an encrypted private key.
        """
    @property
    def cert(self) -> typing.Optional[pathlib.Path]:
        r"""
        Path to the server certificate file.
        """
    @property
    def version(self) -> typing.Optional[builtins.int]:
        r"""
        `ssl` protocol constant selecting the TLS version.
        """
    @property
    def ca_certs(self) -> typing.Optional[pathlib.Path]:
        r"""
        Path to a CA bundle used when validating client certificates.
        """
    def __new__(cls, *, key: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, key_password: typing.Optional[builtins.str] = None, cert: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, version: typing.Optional[builtins.int] = None, ca_certs: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None) -> ServerSSLConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.
        
        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.
        
        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ServiceConfig:
    r"""
    Process-level options applied when running the engine as a system service.
    """
    @property
    def name(self) -> typing.Optional[builtins.str]:
        r"""
        Service name registered with the operating system.
        """
    @property
    def user(self) -> typing.Optional[builtins.str]:
        r"""
        User the service runs as.
        """
    @property
    def stdout(self) -> typing.Optional[pathlib.Path]:
        r"""
        Optional path to redirect standard output to.
        """
    @property
    def stderr(self) -> typing.Optional[pathlib.Path]:
        r"""
        Optional path to redirect standard error to.
        """
    def __new__(cls, *, name: typing.Optional[builtins.str] = None, user: typing.Optional[builtins.str] = None, stdout: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, stderr: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None) -> ServiceConfig: ...
    def __to_dict__(self) -> dict[str, typing.Any]:
        r"""
        Return the configuration as a plain dictionary of JSON-compatible values.
        
        Called through `ceres.data.to_dict` rather than directly.
        """
    @staticmethod
    def __json_schema__() -> dict[str, typing.Any]:
        r"""
        Return the JSON Schema describing this configuration section.
        
        Called through `ceres.data.to_json_schema` rather than directly.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

